include::partial$variables.adoc[]
= Swift
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie, wie Sie den Swift-Compiler mit WebAssembly-Unterstützung über SwiftWasm verwenden, um Werkzeuge zum Erstellen von {project-name} Richtlinien zu nutzen.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "Richtlinien schreiben", "swift"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "Richtlinien schreiben", "swift"]
:sidebar_label: Swift
:sidebar_position: 50
:current-version: {page-origin-branch}

Wie auf der https://swift.org/[offiziellen Website] angegeben:

____
Swift ist eine universelle Programmiersprache, die für Neulinge zugänglich und für Experten leistungsstark ist.
Sie ist schnell, modern, sicher und macht das Schreiben zu einer Freude.
____

Der Swift-Compiler hat noch keine WebAssembly-Unterstützung, jedoch bietet das https://swiftwasm.org/[SwiftWasm] Projekt einen gepatchten Compiler mit dieser Fähigkeit.

Das SwiftWasm-Team arbeitet daran, diese Änderungen in das Swift-Projekt zu integrieren.
In der Zwischenzeit können Sie die vom SwiftWasm-Projekt bereitgestellte Toolchain verwenden, um {project-name} Richtlinien zu erstellen.

[NOTE]
====

Sie benötigen kein Apple-System, um Swift-Code zu schreiben oder auszuführen. Alles kann auch auf einer Linux-Maschine oder unter Windows (mit Docker für Windows) erledigt werden.
====


== Aktueller Zustand

Richtlinienautoren können die folgenden Ressourcen nutzen:

* https://github.com/kubewarden/policy-sdk-swift[{short-project-name} Swift SDK]: dies bietet eine Reihe von ``struct``s und Funktionen, die den Prozess des Schreibens von Richtlinien vereinfachen.
* https://github.com/kubewarden/swift-policy-template[{short-project-name} Swift-Vorlagenprojekt]: verwenden Sie diese Vorlage, um eine auf Swift basierende Richtlinie zu erstellen.
Die Vorlage enthält eine funktionierende Richtlinie und eine Reihe von GitHub Actions, um ihren Lebenszyklus zu automatisieren.

Es gibt keine schwerwiegenden Einschränkungen mit Swift, nur einige kleinere Probleme:

* Es ist entscheidend, einige Post-Build-Optimierungen durchzuführen, bevor Sie die Richtlinie _"in Produktion"_ verwenden:
 .. Strippen Sie das Wasm-Modul über `wasm-strip`, um seine Größe zu reduzieren
 .. Optimieren Sie das Wasm-Modul über `wasm-opt`

Die vom Template-Repository bereitgestellte GitHub-Aktion kümmert sich bereits darum.

== Weitere Beispiele

https://github.com/kubewarden/pod-runtime-class-policy/tree/swift-implementation[Dieser Branch des GitHub-Repositories] hat eine {short-project-name} Richtlinie, die in Swift geschrieben ist.
