include::partial$variables.adoc[]
= Distribuyendo una directiva de Gatekeeper con {project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Distribuye directivas de Gatekeeper a través de clústeres de Kubernetes anotando los archivos de directivas con metadatos y desplegándolos mediante ClusterAdmissionPolicy.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "gatekeeper", "rego"]
:current-version: {page-origin-branch}

Las directivas deben ser anotadas para que puedan ser enviadas y, eventualmente, ejecutadas por el {project-name} `policy-server` en un clúster de Kubernetes.

Anotar y distribuir una directiva de Gatekeeper es similar a distribuir una de Open Policy Agent.

== Anotando la directiva

Vas a escribir un archivo `metadata.yaml` en tu directorio de directivas con el contenido:

[subs="+attributes",yaml]
----
rules:
- apiGroups: [""]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["CREATE"]
mutating: false
contextAware: false
executionMode: gatekeeper
annotations:
  io.kubewarden.policy.title: no-default-namespace
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: This policy will reject any resource created inside the default namespace
  io.kubewarden.policy.author: The {short-project-name} Authors
  io.kubewarden.policy.url: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.source: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
      This policy is just an example.

      You can write interesting descriptions about the policy here.
----

Puedes ver que todo es igual que los metadatos de la versión de Open Policy Agent, excepto por el `executionMode: gatekeeper`.

Adelante, anota la directiva:

[subs="+attributes",console]
----
$ kwctl annotate policy.wasm --metadata-path metadata.yaml --output-path annotated-policy.wasm
----

== Enviando la directiva

Envía tu directiva a un registro OCI:

[subs="+attributes",console]
----
$ kwctl push annotated-policy.wasm registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
Policy successfully pushed
----

== Desplegando en Kubernetes

Primero tienes que extraer tu directiva a tu almacén local `kwctl`:

[subs="+attributes",console]
----
$ kwctl pull registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
pulling policy...
----

Ahora puedes crear un recurso `ClusterAdmissionPolicy` de andamiaje:

[subs="+attributes",console]
----
$ kwctl scaffold manifest registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1 --type ClusterAdmissionPolicy
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Ahora utiliza este recurso `ClusterAdmissionPolicy` para desplegar tu directiva en un clúster de Kubernetes.
