include::partial$variables.adoc[]
= Criando uma política
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprenda a criar e configurar políticas de validação que controlam solicitações de criação de Pods com base em critérios de rejeição personalizáveis.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "creating-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "criação de políticas"]
:sidebar_label: Criando uma política
:current-version: {page-origin-branch}

Como exemplo, você cria uma política de validação simples que processa solicitações de criação de Pods.

A política analisa o atributo `metadata.name` do Pod e rejeita Pods com nomes inválidos.
A lista de nomes inválidos deve ser configurável pelos usuários finais da política.

As configurações da política são algo como:

[subs="+attributes",yaml]
----
invalid_names:
- bad_name1
- bad_name2
----

A política deve aceitar a criação de um Pod como o seguinte:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

A política deve rejeitar a criação de um Pod como:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: bad_name1
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

== Estruturando o novo projeto de política

Você pode criar um novo projeto de política usando `cargo generate` com o https://github.com/kubewarden/rust-policy-template[projeto de template].

Primeiro, instale `cargo-generate`. Isso requer https://pkgs.org/download/openssl-devel[openssl-devel].

[subs="+attributes",shell]
----
cargo install cargo-generate
----

Agora estruture o projeto da seguinte forma:

[subs="+attributes",shell]
----
cargo generate --git https://github.com/kubewarden/rust-policy-template \
               --branch main \
               --name demo
----

O comando produz uma saída como:

[subs="+attributes",console]
----
🔧   Creating project called `+demo+`...
✨   Done! New project created /<some-path-name>/demo
----

Isso cria o novo projeto de política no subdiretório `demo`.

[NOTE]
====

Se você planeja usar a funcionalidade do registro de contêiner do GitHub na demonstração, você precisa https://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry#enabling-the-container-registry-for-your-personal-account[habilitar suporte aprimorado a contêineres].
====


=== qualidade

Você pode tentar:

[subs="+attributes",console]
----
cargo test
----

Isso testa a estrutura gerada. Se tudo estiver corretamente no lugar, você verá uma série de mensagens de compilação terminando com uma saída como:

[subs="+attributes",console]
----
running 4 tests
test settings::tests::validate_settings ... ok
test tests::accept_request_with_non_pod_resource ... ok
test tests::accept_pod_with_valid_name ... ok
test tests::reject_pod_with_invalid_name ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
----
