include::partial$variables.adoc[]
= Escrevendo lógica de validação
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Escreva a lógica de validação para verificar a validade das solicitações recebidas, analisando os payloads e verificando os objetos Pod.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "validation-logic"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "política", "escrita", "rust", "lógica de validação"]
:sidebar_label: Escrevendo lógica de validação
:current-version: {page-origin-branch}

É hora de escrever o código de validação real.
Está definido no arquivo `src/lib.rs`.
Neste arquivo, você pode encontrar uma função chamada `validate`.

Esta é a função fornecida como esqueleto:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: ValidationRequest<Settings> = ValidationRequest::new(payload)?; <1>

    info!(LOG_DRAIN, "starting validation");
    if validation_request.request.kind.kind != apicore::Pod::KIND {
        warn!(LOG_DRAIN, "Policy validates Pods only. Accepting resource"; "kind" => &validation_request.request.kind.kind);
        return kubewarden::accept_request();
    }
    // TODO: you can unmarshal any Kubernetes API type you are interested in <2>
    match serde_json::from_value::<apicore::Pod>(validation_request.request.object) {
        Ok(pod) => {
            // TODO: your logic goes here <3>
            if pod.metadata.name == Some("invalid-pod-name".to_string()) {
                let pod_name = pod.metadata.name.unwrap();
                info!(
                    LOG_DRAIN,
                    "rejecting pod";
                    "pod_name" => &pod_name
                );
                kubewarden::reject_request(
                    Some(format!("pod name {} is not accepted", &pod_name)),
                    None,
                    None,
                    None,
                )
            } else {
                info!(LOG_DRAIN, "accepting resource");
                kubewarden::accept_request()
            }
        }
        Err(_) => {
            // TODO: handle as you wish
            // We were forwarded a request we cannot unmarshal or
            // understand, just accept it
            warn!(LOG_DRAIN, "cannot unmarshal resource: this policy does not know how to evaluate this resource; accept it");
            kubewarden::accept_request() <4>
        }
    }
}
----


Analisando a listagem de código:

* Na linha marcada ➀. Analise o `payload` recebido em um objeto `ValidationRequest<Setting>`.
Isso preenche automaticamente a instância `Settings` dentro do `ValidationRequest` com os parâmetros fornecidos pelo usuário.
* Na linha marcada ➁. Converta o objeto JSON bruto do Kubernetes embutido na solicitação em uma instância do https://arnavion.github.io/k8s-openapi/v0.25.x/k8s_openapi/api/core/v1/struct.Pod.html[struct Pod]
* Na linha marcada ➂. A solicitação contém um objeto Pod, o código aprova apenas as solicitações que não têm `metadata.name` igual ao valor fixo `invalid-pod-name`.
* Na linha marcada ➃. A solicitação não contém um objeto Pod, portanto, a política aceita a solicitação.

Como você pode ver, o código já está realizando uma validação que se assemelha àquela que você deseja implementar.
Você só precisa remover o valor fixo e usar os valores fornecidos pelo usuário por meio das configurações da política.

Você pode fazer isso substituindo a função de esqueleto `validate` em `src/lib.rs` por esta:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: ValidationRequest<Settings> = ValidationRequest::new(payload)?;

    info!(LOG_DRAIN, "starting validation");
    if validation_request.request.kind.kind != apicore::Pod::KIND {
        warn!(LOG_DRAIN, "Policy validates Pods only. Accepting resource"; "kind" => &validation_request.request.kind.kind);
        return kubewarden::accept_request();
    }

    match serde_json::from_value::<apicore::Pod>(validation_request.request.object) {
        Ok(pod) => {
            let pod_name = pod.metadata.name.unwrap_or_default();
            if validation_request
                .settings
                .invalid_names
                .contains(&pod_name)
            {
                kubewarden::reject_request(
                    Some(format!("pod name {:?} is not accepted", pod_name)),
                    None,
                    None,
                    None,
                )
            } else {
                kubewarden::accept_request()
            }
        }
        Err(_) => {
            // We were forwarded a request we cannot unmarshal or
            // understand, just accept it
            kubewarden::accept_request()
        }
    }
}
----

== Testes de unidade

Finalmente, você pode criar testes de unidade para verificar se o código de validação funciona como esperado.

O arquivo `lib.rs` já possui testes definidos na parte inferior do arquivo e, como você pode ver, o SDK Rust do {short-project-name} também fornece auxiliares de teste.

Além disso, o projeto de esqueleto já vem com os https://en.wikipedia.org/wiki/Test_fixture#Software[test fixtures] padrão no diretório `test_data`. Você vai usar estas solicitações de admissão gravadas para escrever seus testes de unidade.

Altere o conteúdo da seção de teste no final de `src/lib.rs` para ficar assim:

[subs="+attributes",rust]
----
#[cfg(test)]
mod tests {
    use super::*;

    use kubewarden_policy_sdk::test::Testcase;
    use std::collections::HashSet;

    #[test]
    fn accept_pod_with_valid_name() -> Result<(), ()> {
        let mut invalid_names = HashSet::new();
        invalid_names.insert(String::from("bad_name1"));
        let settings = Settings { invalid_names };

        let request_file = "test_data/pod_creation.json";
        let tc = Testcase {
            name: String::from("Pod creation with valid name"),
            fixture_file: String::from(request_file),
            expected_validation_result: true,
            settings,
        };

        let res = tc.eval(validate).unwrap();
        assert!(
            res.mutated_object.is_none(),
            "Something mutated with test case: {}",
            tc.name,
        );

        Ok(())
    }

    #[test]
    fn reject_pod_with_invalid_name() -> Result<(), ()> {
        let mut invalid_names = HashSet::new();
        invalid_names.insert(String::from("nginx"));
        let settings = Settings { invalid_names };

        let request_file = "test_data/pod_creation.json";
        let tc = Testcase {
            name: String::from("Pod creation with invalid name"),
            fixture_file: String::from(request_file),
            expected_validation_result: false,
            settings,
        };

        let res = tc.eval(validate).unwrap();
        assert!(
            res.mutated_object.is_none(),
            "Something mutated with test case: {}",
            tc.name,
        );

        Ok(())
    }

    #[test]
    fn accept_request_with_non_pod_resource() -> Result<(), ()> {
        let mut invalid_names = HashSet::new();
        invalid_names.insert(String::from("prod"));
        let settings = Settings { invalid_names };

        let request_file = "test_data/ingress_creation.json";
        let tc = Testcase {
            name: String::from("Ingress creation"),
            fixture_file: String::from(request_file),
            expected_validation_result: true,
            settings,
        };

        let res = tc.eval(validate).unwrap();
        assert!(
            res.mutated_object.is_none(),
            "Something mutated with test case: {}",
            tc.name,
        );

        Ok(())
    }
}
----

Agora você tem três testes de unidade definidos em `lib.rs`:

* `accept_pod_with_valid_name`: aceita um Pod com um nome válido
* `reject_pod_with_invalid_name`: rejeita um Pod com um nome inválido
* `accept_request_with_non_pod_resource`: aceita solicitações que não têm um `Pod` como objeto

Você pode executar os testes de unidade novamente:

[subs="+attributes",shell]
----
$ cargo test
   Compiling demo v0.1.0 (/home/flavio/hacking/kubernetes/kubewarden/demo)
    Finished test [unoptimized + debuginfo] target(s) in 3.45s
     Running target/debug/deps/demo-24670dd6a538fd72

running 5 tests
test settings::tests::accept_settings_with_a_list_of_invalid_names ... ok
test settings::tests::reject_settings_without_a_list_of_invalid_names ... ok
test tests::accept_request_with_non_pod_resource ... ok
test tests::accept_pod_with_valid_name ... ok
test tests::reject_pod_with_invalid_name ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
----

Isso é tudo que é necessário se você precisar escrever uma política de validação simples.
