include::partial$variables.adoc[]
= Roh-Richtlinien
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie mehr über rohe Richtlinien, die beliebige JSON-Dokumente auswerten, und sehen Sie sich Beispiele zur Implementierung von Richtlinien in Rust an.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["writing-policies", "rust", "raw-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "rohe Richtlinien", "rust"]
:sidebar_label: Roh-Richtlinien
:current-version: {page-origin-branch}

Roh-Richtlinien sind Richtlinien, die beliebige JSON-Dokumente auswerten können.
Für weitere Informationen zu Roh-Richtlinien verweisen Sie bitte auf die xref:howtos/raw-policies.adoc[Roh-Richtlinien] Seite.

== Beispiele

Die folgenden Beispiele sollten Ihnen vertraut sein, wenn Sie die xref:tutorials/writing-policies/rust/05-mutation-policy.adoc[Validierung]-Seite dieses Tutorials abgeschlossen haben.

[NOTE]
====
Denken Sie daran, die Richtlinie als `raw` zu kennzeichnen, indem Sie das `policyType` Feld in der `metadata.yml` Konfiguration verwenden.
Bitte beziehen Sie sich auf die xref:tutorials/writing-policies/metadata.adoc[Metadaten] Spezifikation für weitere Informationen.
====


=== Validation

Lassen Sie uns eine Richtlinie schreiben, die eine Anfrage im folgenden Format akzeptiert:

[subs="+attributes",json]
----
{
  "request": {
    "user": "alice",
    "action": "delete",
    "resource": "products"
  }
}
----

und validiert, dass:

* `user` ist in der Liste der gültigen Benutzer
* `action` ist in der Liste der gültigen Aktionen
* `resource` ist in der Liste der gültigen Ressourcen

Beginnen Sie damit, die Richtlinie mit der https://github.com/kubewarden/rust-policy-template[Rust-Richtlinie-Vorlage] zu erstellen.

Zuerst definieren wir die Typen, die die Nutzlast der Anfrage darstellen.
Wir werden einen benutzerdefinierten `RawValidationRequest` Typ deklarieren, der die `Request` und die `Settings` enthält, anstatt den `ValidationRequest` Typ zu verwenden, der vom SDK bereitgestellt wird:

[subs="+attributes",rust]
----
/// RawValidationRequest represents the request that is sent to the validate function by the Policy Server.
#[derive(Deserialize)]
pub(crate) struct RawValidationRequest {
    pub(crate) request: Request,
    pub(crate) settings: Settings,
}

#[derive(Serialize, Deserialize)]
/// Request represents the payload of the request.
pub(crate) struct Request {
    pub(crate) user: String,
    pub(crate) resource: String,
    pub(crate) action: String,
}
----

Dann müssen wir den `Settings` Typ definieren und das `Validatable` Trait implementieren:

[subs="+attributes",rust]
----
/// Settings represents the settings of the policy.
#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(default, rename_all = "camelCase")]
pub(crate) struct Settings {
    pub(crate) valid_users: Vec<String>,
    pub(crate) valid_actions: Vec<String>,
    pub(crate) valid_resources: Vec<String>,
}

impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        info!(LOG_DRAIN, "starting settings validation");

        if self.valid_users.is_empty() {
            return Err("validUsers cannot be empty".to_string());
        }

        if self.valid_actions.is_empty() {
            return Err("validActions cannot be empty".to_string());
        }

        if self.valid_resources.is_empty() {
            return Err("validResources cannot be empty".to_string());
        }

        Ok(())
    }
}
----

Schließlich definieren wir die `validate` Funktion:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: RawValidationRequest =
        if let Ok(validation_request) = serde_json::from_slice(payload) {
            validation_request
        } else {
            return kubewarden::reject_request(
                Some("cannot unmarshal request".to_string()),
                None,
                None,
                None,
            );
        };

    info!(LOG_DRAIN, "starting validation");

    let request = validation_request.request;
    let settings = validation_request.settings;

    if settings.valid_users.contains(&request.user)
        && settings.valid_actions.contains(&request.action)
        && settings.valid_resources.contains(&request.resource)
    {
        info!(LOG_DRAIN, "accepting resource");
        kubewarden::accept_request()
    } else {
        kubewarden::reject_request(
            Some("this request is not accepted".to_string()),
            None,
            None,
            None,
        )
    }
}
----

=== Mutation

Lassen Sie uns das vorherige Beispiel ändern, um die Anfrage zu verändern, anstatt sie abzulehnen.
In diesem Fall werden die Einstellungen die `defaultUser`, `defaultAction` und `defaultRequest` enthalten, die verwendet werden, um die Anfrage zu verändern, wenn der Benutzer, die Aktion oder die Ressource nicht gültig ist.

Wir müssen den `Settings` Typ mit den neuen Feldern aktualisieren:

[subs="+attributes",rust]
----
/// Settings represents the settings of the policy.
#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(default, rename_all = "camelCase")]
pub(crate) struct Settings {
    pub(crate) valid_users: Vec<String>,
    pub(crate) valid_actions: Vec<String>,
    pub(crate) valid_resources: Vec<String>,
    pub(crate) default_user: String,
    pub(crate) default_action: String,
    pub(crate) default_resource: String,
}

impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        info!(LOG_DRAIN, "starting settings validation");

        if self.valid_users.is_empty() {
            return Err("validUsers cannot be empty".to_string());
        }

        if self.valid_actions.is_empty() {
            return Err("validActions cannot be empty".to_string());
        }

        if self.valid_resources.is_empty() {
            return Err("validResources cannot be empty".to_string());
        }

        if self.default_user.is_empty() {
            return Err("defaultUser cannot be empty".to_string());
        }

        if self.default_action.is_empty() {
            return Err("defaultAction cannot be empty".to_string());
        }

        if self.default_resource.is_empty() {
            return Err("defaultResource cannot be empty".to_string());
        }

        Ok(())
    }
}
----

und die `validate` Funktion zur Einführung der Mutation:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: RawValidationRequest =
        if let Ok(validation_request) = serde_json::from_slice(payload) {
            validation_request
        } else {
            return kubewarden::reject_request(
                Some("cannot unmarshal request".to_string()),
                None,
                None,
                None,
            );
        };

    info!(LOG_DRAIN, "starting validation");

    let request = validation_request.request;
    let settings = validation_request.settings;

    if settings.valid_users.contains(&request.user)
        && settings.valid_actions.contains(&request.action)
        && settings.valid_resources.contains(&request.resource)
    {
        info!(LOG_DRAIN, "accepting request");
        return kubewarden::accept_request();
    }

    info!(LOG_DRAIN, "mutating request");
    let mut request = request;

    if !settings.valid_users.contains(&request.user) {
        request.user = settings.default_user;
    }

    if !settings.valid_actions.contains(&request.action) {
        request.action = settings.default_action;
    }

    if !settings.valid_resources.contains(&request.resource) {
        request.resource = settings.default_resource;
    }

    let mutated_request = serde_json::to_value(request)?;
    kubewarden::mutate_request(mutated_request)
}
----
