include::partial$variables.adoc[]
= Gatekeeper-UnterstĂĽtzung
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-04
:page-revdate: {revdate}
:description: Zugriff auf zentrale Gatekeeper-Richtlinien und erfahren Sie, wie Sie diese mit den Admission Controllern von Kubernetes integrieren kĂ¶nnen.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "einfĂĽhrung"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "rego", "gatekeeper"]
:current-version: {page-origin-branch}

[NOTE]
====
Die UnterstĂĽtzung fĂĽr Gatekeeper beginnt mit diesen Versionen:

* kwctl: v0.2.0
* policy-server: v0.2.0
====


Gatekeeper ist ein Projekt, das auf Kubernetes abzielt und sofort einsatzbereite Funktionen fĂĽr die Integration bietet.

== KompatibilitĂ¤t mit vorhandenen Richtlinien

Alle bestehenden Gatekeeper-Richtlinien sollten mit {short-project-name} kompatibel sein, wie in diesem Kapitel erklĂ¤rt.

[IMPORTANT]
====
Wenn Sie feststellen, dass dies fĂĽr Ihre Gatekeeper-Richtlinien nicht zutrifft, melden Sie dies bitte, und wir werden daran arbeiten, sicherzustellen, dass Ihre Gatekeeper-Richtlinien mit {short-project-name} funktionieren.
====


Richtlinien mĂĽssen mit der `opa` Kommandozeilenschnittstelle fĂĽr das Ziel `wasm` kompiliert werden.

FĂĽr die AusfĂĽhrung von Richtlinien kĂ¶nnen Sie mehr ĂĽber den Open Policy Agent und seine xref:tutorials/writing-policies/rego/02-builtin-support.adoc[integrierte UnterstĂĽtzung] in {short-project-name} lesen.
