include::partial$variables.adoc[]
= Proteja webhooks com mTLS com K3s
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-04
:page-revdate: {revdate}
:sidebar_label: Ative mTLS com K3s
:description: Implemente protocolos de TLS mﾃｺtuo (mTLS) para webhooks seguros com K3s em sua distribuiﾃｧﾃ｣o SUSE Kubernetes.
:keywords: ["{admc-name}", kubewarden, kubernetes, seguranﾃｧa]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual-do-operador, seguranﾃｧa

Este guia mostra como ativar o protocolo TLS mﾃｺtuo (mTLS) para webhooks do stack {admc-name} ao usar https://k3s.io/[K3s] como sua distribuiﾃｧﾃ｣o Kubernetes.

Para mais informaﾃｧﾃｵes sobre como fortalecer os webhooks, consulte a xref:/reference/security-hardening/webhooks-hardening.adoc[pﾃ｡gina de referﾃｪncia].

== Prﾃｩ-requisitos

Antes de instalar o K3s, vocﾃｪ precisa criar uma CA (autoridade certificadora) e um certificado de cliente. Vocﾃｪ usa para proteger a comunicaﾃｧﾃ｣o entre os {admc-short-name} webhooks e o servidor API do Kubernetes.

Como primeiro passo, crie o diretﾃｳrio `/etc/rancher/k3s/admission/certs`:

[source,console]
----
sudo mkdir -p /etc/rancher/k3s/admission/certs
----

=== Crie uma CA raiz e o certificado de cliente

Como usuﾃ｡rio `root`, mude o diretﾃｳrio para o diretﾃｳrio `/etc/rancher/k3s/admission/certs` e crie todos os certificados necessﾃ｡rios:

[source,console]
----
export FQDN=mtls.kubewarden.io

# Create openssl config file
cat > openssl.cnf <<EOL
[ req ]
default_keyfile     = rootCA.key
distinguished_name  = req_distinguished_name
x509_extensions     = v3_ca
string_mask         = utf8only

[ req_distinguished_name ]
countryName         = Country Name (2 letter code)
countryName_default = US
stateOrProvinceName = State or Province Name (full name)
localityName        = Locality Name (eg, city)
organizationName    = Organization Name (eg, company)
commonName          = Common Name (eg, your domain or your CA name)

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true, pathlen:1
keyUsage = critical, keyCertSign, cRLSign
EOL

# Create CA
openssl req -nodes -batch -x509 -sha256 -days 3650 -newkey rsa:4096 -keyout rootCA.key -out rootCA.crt \
  -config openssl.cnf

# Create CSR
openssl req -nodes -batch -newkey rsa:4096 -keyout client.key -out client.csr \
    -addext "subjectAltName = DNS:$FQDN"  -config openssl.cnf

# Create CRT
openssl x509 -req -CA rootCA.crt -CAkey rootCA.key -in client.csr -out client.crt -days 3650 -CAcreateserial \
    -extfile <(echo "subjectAltName=DNS:$FQDN")

# Print CRT

openssl x509 -text -noout -in client.crt
----

Isso cria os seguintes arquivos:

* `client.crt`
* `client.csr`
* `client.key`
* `rootCA.crt`
* `rootCA.key`
* `rootCA.srl`

=== Crie o arquivo de configuraﾃｧﾃ｣o do Kubernetes

Crie o arquivo `/etc/rancher/k3s/admission/admission.yaml` com o seguinte conteﾃｺdo:

[source,yaml]
----
# /etc/rancher/k3s/admission/admission.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
- name: MutatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
----

Por fim, crie um arquivo `kubeconfig` em `/etc/rancher/k3s/admission/kubeconfig`:

[source,yaml]
----
# /etc/rancher/admission/kubeconfig
apiVersion: v1
kind: Config
users:
- name: "*.kubewarden.svc" # namespace where the kubewarden stack is deployed
  user:
    client-certificate: /etc/rancher/k3s/admission/certs/client.crt
    client-key: /etc/rancher/k3s/admission/certs/client.key
----

=== Crie um arquivo de configuraﾃｧﾃ｣o do K3s

Crie um arquivo de configuraﾃｧﾃ｣o do K3s em `/etc/rancher/k3s/config.yaml`:

[source,yaml]
----
# /etc/rancher/k3s/config.yaml
kube-apiserver-arg:
- admission-control-config-file=/etc/rancher/k3s/admission/admission.yaml
----

== Instale o K3s

Instale o K3s usando o seguinte comando:

[source,console]
----
curl -sfL https://get.k3s.io | sh -
----

Aguarde a conclusﾃ｣o da instalaﾃｧﾃ｣o.

== Instale o {admc-short-name} stack

=== Prﾃｩ-requisitos

O certificado da CA raiz, que emitiu o certificado do cliente Kubernetes, precisa estar disponﾃｭvel para o {admc-short-name} stack.

A CA raiz estﾃ｡ disponﾃｭvel em `/etc/rancher/k3s/admission/certs/rootCA.crt` no nﾃｳ Kubernetes. Vocﾃｪ precisa do seu conteﾃｺdo em um `ConfigMap` sob o namespace `kubewarden`. Vocﾃｪ armazena o conteﾃｺdo do arquivo `rootCA.crt` na chave chamada `client-ca.crt`.

Primeiro, crie o namespace `kubewarden`:

[source,console]
----
kubectl create namespace kubewarden
----

Depois, crie o `ConfigMap` nele. O seguinte comando, executado no nﾃｳ Kubernetes, faz isso:

[source,console]
----
kubectl create configmap -n kubewarden api-server-mtls \
    --from-file=client-ca.crt=/etc/rancher/k3s/admission/certs/rootCA.crt
----

O nome do `ConfigMap` resultante ﾃｩ `api-server-mtls`.

=== Instale o {admc-short-name} stack

Instale o {admc-short-name} stack conforme descrito no xref:/quick-start.adoc[guia de inﾃｭcio rﾃ｡pido]. Siga todos os passos, mas ao instalar o chart Helm `kubewarden-controller`, certifique-se de habilitar os seguintes valores:

* `mTLS.enable`: deve ser `true`.
* `mTLS.configMapName`: deve ser o nome do `ConfigMap` criado anteriormente.

O nome do `ConfigMap` ﾃｩ `api-server-mtls`. O comando Helm para instalar o `kubewarden-controller` ﾃｩ:

[source,console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller \
    --set mTLS.enable=true \
    --set mTLS.configMapName=api-server-mtls
----

Uma vez que este comando termine, o mTLS garante a instalaﾃｧﾃ｣o do {admc-short-name} stack e seus webhooks.