include::partial$variables.adoc[]
= Consignation
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configurez l'initialisation du logger pour la journalisation structurée dans votre stratégie en utilisant l'intégration du SDK Go du projet oneLog.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["Kubewarden", "rédaction de stratégies", "golang", "journalisation"]
:doc-type: ["tutorial"]
:keywords: ["Kubewarden", "kubernetes", "rédaction de stratégies", "golang", "go", "journalisation"]
:current-version: {page-origin-branch}

Le SDK Go s'intègre au projet
https://github.com/francoispqt/onelog[`onelog`]
presque prêt à l'emploi.
// TODO: Last release 2019. Still good?

Le projet a choisi cette bibliothèque comme :

* Il fonctionne avec des binaires WebAssembly.
D'autres solutions de journalisation populaires ne peuvent pas être compilées pour cibler WebAssembly.
* Il offre https://github.com/francoispqt/onelog#benchmarks[de bonnes performances].
* Il prend en charge la journalisation structurée.

== Initialiser le logger

Vous devez initialiser une structure de logger.
En effectuant cette initialisation dans une variable globale,
vous pouvez journaliser depuis les deux principaux points d'entrée de la stratégie : `validate` et
`validate_settings`.

Dans le paquet principal, `main.go` il y a une initialisation pour le logger :

[,go]
----
var (
    logWriter = kubewarden.KubewardenLogWriter{}
    logger    = onelog.New(
        &logWriter,
        onelog.ALL, // shortcut for onelog.DEBUG|onelog.INFO|onelog.WARN|onelog.ERROR|onelog.FATAL
    )
)
----

== Utiliser le logger

Maintenant, vous pouvez utiliser l'objet `logger` pour journaliser depuis n'importe où dans votre stratégie :

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.Info("validating request")
    // ...
}
----

Vous pouvez ajouter une journalisation structurée :

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.WarnWithFields("logging something important", func(e onelog.Entry) {
        e.String("one_field", "a value")
        e.String("another_field", "another value")
    })
    // ...
}
----

Vous pouvez vous référer à la
https://pkg.go.dev/github.com/francoispqt/onelog?utm_source=godoc[`onelog` documentation]
pour plus d'informations.

La journalisation de la stratégie va vers l'évaluateur de stratégie (par exemple, `kwctl` ou `policy-server`), et celui-ci journalise au nom de la stratégie.
Ils utilisent des mécanismes qui sont interopérables avec d'autres composants qui permettent le traçage distribué, tels que https://www.jaegertracing.io/[Jaeger].
