include::partial$variables.adoc[]
= 原始策略
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 将原始策略配置为通用策略评估引擎，使用 {project-name}。
:doc-persona: ["kubewarden-distributor", "kubewarden-integrator", "kubewarden-operator", "kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "kubernetes", "raw-policies"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "support", "raw policies"]
:sidebar_label: 原始策略
:sidebar_position: 60
:current-version: {page-origin-branch}

从 `v1.9.0` 开始，{project-name} 支持在 Kubernetes 集群外部编写和执行策略的能力，作为通用策略评估引擎。
策略服务器公开了 `/validate_raw` 端点，可用于验证任意 JSON 文档与 {short-project-name} 策略的匹配。

在本指南中，我们将使用以下原始策略：

* https://github.com/kubewarden/raw-validation-policy[raw-validation-policy]
* https://github.com/kubewarden/raw-mutation-policy[raw-mutation-policy]

[NOTE]
====
请确保策略作者在元数据中将策略标记为 `policyType: raw`。
您可以使用 `kwctl` 检查元数据。

[subs="+attributes",bash]
----
kwctl inspect ghcr.io/kubewarden/tests/raw-mutation-policy:v0.1.0
----
====


== 在 Kubernetes 外部运行策略服务器

策略服务器可以作为独立容器在 Kubernetes 外部运行。

首先，创建一个 `policies.yml` 文件，并包含以下内容：

[subs="+attributes",yaml]
----
raw-validation:
  module: ghcr.io/kubewarden/tests/raw-validation-policy:v0.1.0
  settings:
    validUsers:
      - alice
      - bob
    validActions:
      - read
      - write
    validResources:
      - orders
      - products

raw-mutation:
  module: ghcr.io/kubewarden/tests/raw-mutation-policy:v0.1.0
  allowedToMutate: true
  settings:
    forbiddenResources:
      - privateResource
      - secretResource
    defaultResource: publicResource
----

要启动策略服务器：

[subs="+attributes",bash]
----
# Create a docker volume to store the policies
docker volume create --driver local \
                --opt type=tmpfs \
                --opt device=tmpfs \
                --opt o=ui=65533 \
                policy-store

# Start the policy server
docker run --rm -it \
    -p 3000:3000 \
    -v $(pwd)/policies.yml:/policies.yml \
    -v policy-store:/registry \
    ghcr.io/kubewarden/policy-server:1.9.0 \
    --ignore-kubernetes-connection-failure=true
----

NOTE: 标志 `--ignore-kubernetes-connection-failure=true` 是在没有 Kubernetes 的情况下启动策略服务器所必需的。
但是，可以在 Kubernetes 中启动策略服务器并使用原始验证端点。
原始策略可以访问上下文感知的 xref:../explanations/context-aware-policies.adoc[capabilities]，就像标准策略一样。

== 在 Kubernetes 中运行策略服务器而不使用 {short-project-name} 控制器

无法使用由 {short-project-name} 控制器管理的策略服务器实例来托管原始策略。
控制器将不允许用户更改策略服务器 ConfigMap 以添加原始策略，因为它会试图协调并还原更改。
因此，必须启动一个专用的策略服务器。

创建一个 `policy-server.yaml` 文件，并包含以下内容：

[subs="+attributes",yaml]
----
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-server
  template:
    metadata:
      labels:
        app: policy-server
    spec:
      containers:
        - name: policy-server
          image: ghcr.io/kubewarden/policy-server:v1.9.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: policy-store
              mountPath: /registry
            - name: policies-config
              mountPath: /policies.yml
              subPath: policies.yml
      volumes:
        - name: policy-store
          emptyDir: {}
        - name: policies-config
          configMap:
            name: policies-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: policy-server-service
spec:
  selector:
    app: policy-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-configmap
data:
  policies.yml: |
    raw-validation:
      module: ghcr.io/kubewarden/tests/raw-validation-policy:v0.1.0
      settings:
        validUsers:
          - alice
          - bob
        validActions:
          - read
          - write
        validResources:
          - orders
          - products
    raw-mutation:
      module: ghcr.io/kubewarden/tests/raw-mutation-policy:v0.1.0
      allowedToMutate: true
      settings:
        forbiddenResources:
          - privateResource
          - secretResource
        defaultResource: publicResource
----

应用配置：

[subs="+attributes",bash]
----
kubectl apply -f policy-server.yaml
----

[IMPORTANT]
====
部署的策略服务器实例将能够访问可由上下文感知策略使用的 Kubernetes 资源。
对 Kubernetes 资源的访问级别由用于运行策略服务器工作负载的服务账户决定。

在前面的示例中，部署规范中未定义服务账户；因此将使用 `default` 服务账户。
====


== 使用 validate_raw 端点

=== Validation

原始验证端点在 `/validate_raw` 处公开，并接受 `POST` 请求。
由于我们已经部署了一个服务，我们可以设置端口转发以通过 `kubectl port-forward service/policy-server-service 3000:3000 -n default` 访问它。

让我们尝试根据 `raw-validation` 策略验证一个 JSON 文档：

[subs="+attributes",bash]
----
curl -X POST \
  http://localhost:3000/validate_raw/raw-validation \
  -H 'Content-Type: application/json' \
  -d '{
  "request": {
    "user": "alice",
    "action": "read",
    "resource": "customers"
  }
}'
----

请求将不会被接受，因为 `alice` 尚未被授予对 `customers` 资源的访问：

[subs="+attributes",json]
----
{
  "response": {
    "uid": "",
    "allowed": false,
    "auditAnnotations": null,
    "warnings": null
  }
}
----

让我们再试一次，使用一个有效的资源：

[subs="+attributes",bash]
----
curl -X POST \
  http://localhost:3000/validate_raw/raw-validation \
  -H 'Content-Type: application/json' \
  -d '{
  "request": {
    "user": "alice",
    "action": "read",
    "resource": "orders"
  }
}'
----

这次，请求将被接受：

[subs="+attributes",json]
----
{
  "response": {
    "uid": "",
    "allowed": true,
    "auditAnnotations": null,
    "warnings": null
  }
}
----

[NOTE]
====
如果请求负载中提供了 `uid` 字段，它将作为响应的一部分返回。
====


=== 变更

现在，让我们尝试根据 `raw-mutation` 策略变更一个 JSON 文档：

[subs="+attributes",bash]
----
curl -X POST \
  http://localhost:3000/validate_raw/raw-mutation \
  -H 'Content-Type: application/json' \
  -d '{
  "request": {
    "user": "alice",
    "action": "read",
    "resource": "privateResource"
  }
}'
----

请求将被变更，响应将包含一个 JSONPatch：

[subs="+attributes",json]
----
{
  "response": {
    "uid": "",
    "allowed": true,
    "patchType": "JSONPatch",
    "patch": "W3sib3AiOiJyZXBsYWNlIiwicGF0aCI6Ii9yZXNvdXJjZSIsInZhbHVlIjoicHVibGljUmVzb3VyY2UifV0=",
    "auditAnnotations": null,
    "warnings": null
  }
}
----

== 编写原始策略

与验证 Kubernetes 资源的策略类似，原始策略是使用 {short-project-name} SDK 在 WebAssembly 中编写的。
如果您有兴趣编写原始策略，请参考特定语言的文档以获取更多信息：

* xref:../tutorials/writing-policies/go/10-raw-policies.adoc[转至]
* xref:../tutorials/writing-policies/rust/08-raw-policies.adoc[Rust]
* xref:../tutorials/writing-policies/rego/open-policy-agent/05-raw-policies.adoc[OPA]
* xref:../tutorials/writing-policies/wasi/02-raw-policies.adoc[WASI]
