include::partial$variables.adoc[]
= Swift
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprenda a usar o compilador Swift com suporte a WebAssembly através do SwiftWasm para acessar ferramentas para construir {project-name} políticas.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "swift"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "escrevendo políticas", "swift"]
:sidebar_label: Swift
:sidebar_position: 50
:current-version: {page-origin-branch}

Conforme declarado no https://swift.org/[site oficial]:

____
Swift é uma linguagem de programação de propósito geral que é acessível para iniciantes e poderosa para especialistas.
É rápida, moderna, segura e um prazer de escrever.
____

O compilador Swift ainda não tem suporte a WebAssembly, no entanto, o projeto https://swiftwasm.org/[SwiftWasm] fornece um compilador patchado com essa capacidade.

A equipe do SwiftWasm está trabalhando para mesclar essas mudanças no projeto Swift.
Enquanto isso, você pode usar a cadeia de ferramentas fornecida pelo projeto SwiftWasm para construir {project-name} políticas.

[NOTE]
====

Você não precisa de um sistema Apple para escrever ou executar código Swift. Tudo pode ser feito também em uma máquina Linux ou no Windows (usando Docker para Windows).
====


== Estado atual

Os autores de políticas podem usar os seguintes recursos:

* https://github.com/kubewarden/policy-sdk-swift[{short-project-name} Swift SDK]: isso fornece um conjunto de ``struct``s e funções que simplificam o processo de escrita de políticas.
* https://github.com/kubewarden/swift-policy-template[{short-project-name} projeto de template Swift]: use este template para estruturar uma política baseada em Swift.
O template vem com uma política funcional e um conjunto de Ações do GitHub para automatizar seu ciclo de vida.

Não há limitações severas com o Swift, apenas alguns problemas menores:

* É crítico realizar algumas otimizações pós-compilação antes de usar a política _"em produção"_:
 .. Remova o módulo Wasm via `wasm-strip` para reduzir seu tamanho
 .. Otimize o módulo Wasm via `wasm-opt`

A Ação do GitHub fornecida pelo repositório do template já cuida disso.

== Mais exemplos

https://github.com/kubewarden/pod-runtime-class-policy/tree/swift-implementation[Este branch do repositório do GitHub] tem uma {short-project-name} política escrita em Swift.
