include::partial$variables.adoc[]
= ビルトインサポート
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: WebAssemblyモジュールで利用可能なビルトイン関数を特定し、それらの実装とRegoポリシー開発における使用法を理解します。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "built-in-support"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "ビルトインWasmサポート"]
:sidebar_label: ビルトインサポート
:current-version: {page-origin-branch}

`wasm`ターゲットのポリシーを構築するには、そのターゲットが実行中である必要があります。

Open Policy Agent (OPA)チームには、https://www.openpolicyagent.org/docs/latest/policy-reference/#built-in-functions[ビルトインサポート]を確認できるページがあります。

RegoポリシーをWebAssemblyモジュールに構築する際、これらのビルトイン関数の一部はWasmファイル自体に含まれています。
それらは、リンクされたビルトインページで緑のチェックマークが付けられたビルトインです。
モジュールを評価するWebAssemblyランタイムは、他のビルトインを提供します。

`SDK-dependent`としてマークされたビルトインは、ホストが実装しなければならないものであり、この場合は{project-name}です。
OPAとGatekeeperは、ポリシーのニーズに応じてそれらを使用することがあります。
いずれにせよ、これらのビルトインはポリシーに公開されており、新しいポリシーまたは既存のポリシーはそれらに依存する可能性があります。

まだ{short-project-name}によって提供されていない特定のビルトインがありますが、公開されているポリシーに基づいて、すでにサポートされているものはほとんどのKubernetesユーザーにとって十分であるはずです。

https://github.com/kubewarden/policy-evaluator/issues/56[このGitHubの問題]は、まだ実装していないRegoのビルトインを追跡します。
私たちの作業の優先順位を決めるために、自由にコメントしてください。

== 不足しているビルトインでポリシーを実行する

ポリシーが`kwctl`または`policy-server`で実行されると、ポリシーで使用されるビルトインのリストが検査されます。
使用されているビルトインのいずれかが不足している場合、プログラムは実行を停止し、欠落しているビルトインを報告する致命的なエラーをログに記録します。
