include::partial$variables.adoc[]
= Proteja webhooks com mTLS com K3s
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Ative mTLS com K3s
:description: Implemente protocolos de TLS mĂştuo (mTLS) para webhooks seguros com K3s em sua distribuiĂ§ĂŁo SUSE Kubernetes.
:keywords: ["{project-name}", kubewarden, kubernetes, seguranĂ§a]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual-do-operador, seguranĂ§a

Este guia mostra como ativar o protocolo TLS mĂştuo (mTLS) para webhooks do stack {project-name} ao usar https://k3s.io/[K3s] como sua distribuiĂ§ĂŁo Kubernetes.

Para mais informaĂ§Ăµes sobre como fortalecer os webhooks, consulte a xref:/reference/security-hardening/webhooks-hardening.adoc[pĂˇgina de referĂŞncia].

== PrĂ©-requisitos

Antes de instalar o K3s, vocĂŞ precisa criar uma CA (autoridade certificadora) e um certificado de cliente. VocĂŞ usa para proteger a comunicaĂ§ĂŁo entre os {short-project-name} webhooks e o servidor API do Kubernetes.

Como primeiro passo, crie o diretĂłrio `/etc/rancher/k3s/admission/certs`:

[source,console]
----
sudo mkdir -p /etc/rancher/k3s/admission/certs
----

=== Crie uma CA raiz e o certificado de cliente

Como usuĂˇrio `root`, mude o diretĂłrio para o diretĂłrio `/etc/rancher/k3s/admission/certs` e crie todos os certificados necessĂˇrios:

[source,console]
----
export FQDN=mtls.kubewarden.io

# Create openssl config file
cat > openssl.cnf <<EOL
[ req ]
default_keyfile     = rootCA.key
distinguished_name  = req_distinguished_name
x509_extensions     = v3_ca
string_mask         = utf8only

[ req_distinguished_name ]
countryName         = Country Name (2 letter code)
countryName_default = US
stateOrProvinceName = State or Province Name (full name)
localityName        = Locality Name (eg, city)
organizationName    = Organization Name (eg, company)
commonName          = Common Name (eg, your domain or your CA name)

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true, pathlen:1
keyUsage = critical, keyCertSign, cRLSign
EOL

# Create CA
openssl req -nodes -batch -x509 -sha256 -days 3650 -newkey rsa:4096 -keyout rootCA.key -out rootCA.crt \
  -config openssl.cnf

# Create CSR
openssl req -nodes -batch -newkey rsa:4096 -keyout client.key -out client.csr \
    -addext "subjectAltName = DNS:$FQDN"  -config openssl.cnf

# Create CRT
openssl x509 -req -CA rootCA.crt -CAkey rootCA.key -in client.csr -out client.crt -days 3650 -CAcreateserial \
    -extfile <(echo "subjectAltName=DNS:$FQDN")

# Print CRT

openssl x509 -text -noout -in client.crt
----

Isso cria os seguintes arquivos:

* `client.crt`
* `client.csr`
* `client.key`
* `rootCA.crt`
* `rootCA.key`
* `rootCA.srl`

=== Crie o arquivo de configuraĂ§ĂŁo do Kubernetes

Crie o arquivo `/etc/rancher/k3s/admission/admission.yaml` com o seguinte conteĂşdo:

[source,yaml]
----
# /etc/rancher/k3s/admission/admission.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
- name: MutatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
----

Por fim, crie um arquivo `kubeconfig` em `/etc/rancher/k3s/admission/kubeconfig`:

[source,yaml]
----
# /etc/rancher/admission/kubeconfig
apiVersion: v1
kind: Config
users:
- name: "*.kubewarden.svc" # namespace where the kubewarden stack is deployed
  user:
    client-certificate: /etc/rancher/k3s/admission/certs/client.crt
    client-key: /etc/rancher/k3s/admission/certs/client.key
----

=== Crie um arquivo de configuraĂ§ĂŁo do K3s

Crie um arquivo de configuraĂ§ĂŁo do K3s em `/etc/rancher/k3s/config.yaml`:

[source,yaml]
----
# /etc/rancher/k3s/config.yaml
kube-apiserver-arg:
- admission-control-config-file=/etc/rancher/k3s/admission/admission.yaml
----

== Instale o K3s

Instale o K3s usando o seguinte comando:

[source,console]
----
curl -sfL https://get.k3s.io | sh -
----

Aguarde a conclusĂŁo da instalaĂ§ĂŁo.

== Instale o {short-project-name} stack

=== PrĂ©-requisitos

O certificado da CA raiz, que emitiu o certificado do cliente Kubernetes, precisa estar disponĂ­vel para o {short-project-name} stack.

A CA raiz estĂˇ disponĂ­vel em `/etc/rancher/k3s/admission/certs/rootCA.crt` no nĂł Kubernetes. VocĂŞ precisa do seu conteĂşdo em um `ConfigMap` sob o namespace `kubewarden`. VocĂŞ armazena o conteĂşdo do arquivo `rootCA.crt` na chave chamada `client-ca.crt`.

Primeiro, crie o namespace `kubewarden`:

[source,console]
----
kubectl create namespace kubewarden
----

Depois, crie o `ConfigMap` nele. O seguinte comando, executado no nĂł Kubernetes, faz isso:

[source,console]
----
kubectl create configmap -n kubewarden api-server-mtls \
    --from-file=client-ca.crt=/etc/rancher/k3s/admission/certs/rootCA.crt
----

O nome do `ConfigMap` resultante Ă© `api-server-mtls`.

=== Instale o {short-project-name} stack

Instale o {short-project-name} stack conforme descrito no xref:/quick-start.adoc[guia de inĂ­cio rĂˇpido]. Siga todos os passos, mas ao instalar o chart Helm `kubewarden-controller`, certifique-se de habilitar os seguintes valores:

* `mTLS.enable`: deve ser `true`.
* `mTLS.configMapName`: deve ser o nome do `ConfigMap` criado anteriormente.

O nome do `ConfigMap` Ă© `api-server-mtls`. O comando Helm para instalar o `kubewarden-controller` Ă©:

[source,console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller \
    --set mTLS.enable=true \
    --set mTLS.configMapName=api-server-mtls
----

Uma vez que este comando termine, o mTLS garante a instalaĂ§ĂŁo do {short-project-name} stack e seus webhooks.