include::partial$variables.adoc[]

= InstalaciĂ³n en entorno aislado con Hauler
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-04
:page-revdate: {revdate}
:description: Utiliza Hauler para instalar {admc-name} en entornos aislados.
:keywords: ["{admc-name}", kubewarden, kubernetes, instalaciĂ³n en entorno aislado, hauler]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual-del-operador, entorno aislado, instalaciĂ³n, hauler

Esta guĂ­a te muestra cĂ³mo instalar {admc-name} en entornos aislados utilizando link:https://docs.hauler.dev/docs/intro[Hauler]. Hauler es una herramienta que ayuda a los usuarios a ejecutar cargas de trabajo en entornos aislados. Mueve los recursos necesarios para las aplicaciones a esos entornos aislados.

{admc-short-name} proporciona un archivo de manifiesto con todos los recursos necesarios para ejecutar {admc-short-name} en un entorno privado. Esta documentaciĂ³n describe cĂ³mo puedes utilizarlo. Consulta la documentaciĂ³n de Hauler para aprender mĂ¡s sobre ello.

El flujo de trabajo bĂ¡sico utilizando el manifiesto de Hauler es:

. ConsĂ­guelo desde una pĂ¡gina de lanzamiento de {admc-short-name}
. Carga todos los recursos necesarios para ejecutar {admc-short-name} en un almacĂ©n local
. ExpĂ³rtalos a un archivo
. Mueve el archivo al entorno privado.
. Carga los recursos en Hauler ejecutĂ¡ndose dentro del entorno privado.
. Copia todo en un registro, para ser utilizado en el proceso de instalaciĂ³n, en tu entorno aislado.

== Descarga el manifiesto de Hauler desde la pĂ¡gina de lanzamiento del grĂ¡fico de Helm

Descarga `hauler_manifest.yml` desde la {admc-short-name}link:https://github.com/kubewarden/helm-charts/releases/[pĂ¡gina de lanzamiento].

Sincroniza los recursos definidos en el manifiesto a tu almacĂ©n de Hauler:

[source,shell]
----
hauler store sync --filename hauler_manifest.yaml
----

Hauler descarga todos los recursos del manifiesto al almacĂ©n local. Este proceso tarda unos minutos. Cuando se complete, podrĂ¡s ver los recursos sincronizados con el comando `hauler store info`.

== Genera el archivo tarball con todos los recursos de {admc-short-name}.

Ejecuta el comando Hauler para exportar todos los recursos previamente cargados en el almacĂ©n a un archivo:

[source,shell]
----
hauler store save --filename kubewarden-resources.tar.zst
----

[NOTE]
====

Las imĂ¡genes de contenedor de {admc-short-name} son compatibles con arquitecturas x86_64 y de la familia de arquitecturas ARM. Por lo tanto, cuando guardes el recurso en el archivo, podrĂ¡s ver mensajes de advertencia como este:

[source,shell]
----
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kyverno/policy-reporter:3.3.3]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kyverno/policy-reporter-ui:2.4.1]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/policy-server:v1.27.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/audit-scanner:v1.27.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/rancher/kuberlr-kubectl:v5.0.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/kubewarden-controller:v1.27.0]
----

Para evitar este mensaje de advertencia, puedes establecer la bandera CLI `--platform` para definir quĂ© arquitectura de plataforma deseas guardar en el archivo.

====

== Transfiere el tarball a tu entorno aislado.

Ahora que tienes todos los recursos de {admc-short-name} en `kubewarden-resources.tar.zst`, cĂ³pialo en tu entorno aislado y cĂ¡rgalo en el almacĂ©n de Hauler allĂ­:

[source,shell]
----
hauler store load --filename kubewarden-resources.tar.zst
# Check if the resources are loaded
hauler store info
----

Ahora todos los recursos necesarios para instalar {admc-short-name} estĂ¡n en el almacĂ©n de Hauler en tu entorno aislado.

== Poblar el registro privado

Para utilizar los recursos de tu almacĂ©n de Hauler, es necesario hacerlos disponibles en un registro interno. Puedes usar comandos de Hauler para copiarlos en tu registro privado.

[source,shell]
----
hauler store copy registry://localhost:5000
----

TambiĂ©n puedes ejecutar Hauler para iniciar un registro con todos los recursos del almacĂ©n. Este registro no es seguro, y necesitas adaptar la configuraciĂ³n del clĂºster:

[source,shell]
----
# Find IP address of your host
# hostname -I

# Update registries.yaml for k3s based cluster to allow insecure access
# mirrors:
#   "<HOST_IP>:5000":
#     endpoint:
#       - "http://<HOST_IP>:5000"
# configs:
#   "<HOST_IP>:5000":
#     tls:
#       insecure_skip_verify: true

# Configure policy-server to allow pulling policies from insecure sources
# helm install .. kubewarden-defaults .. --set policyServer.insecureSources[0]=<HOST_IP:5000>

hauler store serve registry
----

Esto inicia un registro en la direcciĂ³n `localhost:5000`. A partir de este momento, puedes usar otros comandos como Skopeo para copiar todas las imĂ¡genes de contenedor, mĂ³dulos de directiva y grĂ¡ficos de Helm utilizados por {admc-short-name} en tu registro privado.

== Instalar {admc-short-name}

Ahora que tu registro privado tiene todo lo necesario, puedes instalar {admc-short-name}. La diferencia con una instalaciĂ³n estĂ¡ndar de {admc-short-name} es que necesitas cambiar el registro en las imĂ¡genes de contenedor y directivas para que sea el registro privado. AdemĂ¡s, necesitas instalar los grĂ¡ficos de Helm de los artefactos OCI.

Instala el {admc-short-name}stack:

[source,shell]
----
helm install --wait -n kubewarden kubewarden-crds --create-namespace \
    oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-crds
helm install --wait -n kubewarden kubewarden-controller \
    --set "global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>" \
    oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-controller
----

[CAUTION]
====

Para usar el subgrĂ¡fico Policy Reporter disponible en el `kubewarden-controller` grĂ¡fico, necesitas definir otros valores especĂ­ficos para el subgrĂ¡fico en un entorno aislado. Consulta un ejemplo a continuaciĂ³n:

[source,shell]
----
helm install --wait -n kubewarden kubewarden-controller oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-controller \
    --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set auditScanner.policyReporter=true \
    --set policy-reporter.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.image.repository=kyverno/policy-reporter \
    --set policy-reporter.ui.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.ui.image.repository=kyverno/policy-reporter-ui
----

Es necesario definir `auditScanner.policyReporter` y otros cuatro valores para habilitar el subgrĂ¡fico y configurar el registro y el repositorio con la ubicaciĂ³n del almacĂ©n de imĂ¡genes de Policy Reporter. Para mĂ¡s informaciĂ³n sobre los valores del subgrĂ¡fico de informes de directivas, consulta la \link:https://kyverno.github.io/policy-reporter-docs/getting-started/helm.html[documentaciĂ³n de Policy Reporter].

====

[source,shell]
----
helm install --wait -n kubewarden \
  kubewarden-defaults oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-defaults \
  --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>
----

Finalmente, configura cada Servidor de Directivas para obtener directivas de tu registro privado. Consulta la xref:/howtos/policy-servers/02-private-registry.adoc[secciĂ³n usando registro privado] de la documentaciĂ³n.

Ahora crea {admc-short-name} directivas en tu clĂºster. Las directivas deben estar disponibles en tu registro privado.

[source,yaml]
----
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://<REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policies/pod-privileged:v0.2.2
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
  mutating: false
EOF
----

[CAUTION]
====

Los `PolicyServer`recursos deben utilizar la imagen disponible en tu registro privado.
Por ejemplo:

[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: reserved-instance-for-tenant-a
spec:
  image: <REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policy-server:v1.3.0
  replicas:
----

====