include::partial$variables.adoc[]
= Directivas de verificaciĂ³n de firmas
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-04
:page-revdate: {revdate}
:description: Implementa directivas seguras para tu clĂºster utilizando la directiva de verificador proporcionada, o amplĂ­ala con el SDK de tu lenguaje elegido.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "signature-verifier-policies"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "especificaciĂ³n de directivas", "verificador de firmas"]
:sidebar_label: Directivas de verificaciĂ³n de firmas
:current-version: {page-origin-branch}

{admc-name} implementa soporte para el
https://www.sigstore.dev/[Sigstore]
proyecto.
Esto permite implementar un "Sistema de Suministro Seguro" para tu clĂºster.

Parte de la funciĂ³n del sistema de suministro seguro es asegurar que todas las imĂ¡genes de contenedor que se ejecutan en el clĂºster estĂ©n firmadas y verificadas.
Esto prueba que provienen de sus autores declarados, sin alteraciones.
Para mĂ¡s informaciĂ³n, consulta la documentaciĂ³n sobre
xref:/howtos/security-hardening/secure-supply-chain.adoc[cĂ³mo implementamos un Sistema de Suministro Seguro para las directivas mismas].

Las firmas de Sigstore se almacenan dentro de los registros de contenedores,
junto al objeto OCI que se estĂ¡ firmando.
Pueden ser una imagen de contenedor o un artefacto OCI mĂ¡s genĂ©rico,
como una {admc-short-name} directiva.
Cuando un objeto es firmado,
sus firmas se almacenan como capas de un objeto OCI creado por Sigstore.
Las directivas que necesitan verificar las firmas de los contenedores deben comprobar esas capas,
y necesitan extraer las capas de firma para verificar las firmas mismas.

Obtener y operar con esas capas OCI debe ocurrir fuera del invitado de WebAssembly (la directiva).
Por lo tanto, esto lo realiza el tiempo de ejecuciĂ³n de WebAssembly,
{admc-short-name}'s `policy-server` o `kwctl`.

Los diferentes SDK de lenguaje para directivas de {admc-short-name} se encargan de esto.
Proporcionan funciones para la verificaciĂ³n de imĂ¡genes de contenedor,
{admc-short-name} directivas, grĂ¡ficos de Helm y otros tipos de artefactos OCI.
Esto asegura una vĂ­a de cĂ³digo segura y probada para la verificaciĂ³n.

Extraer datos de un registro y verificar criptogrĂ¡ficamente las firmas puede ser costoso en tiempo y recursos computacionales, por lo que el tiempo de ejecuciĂ³n de WebAssembly (PolicyServer, `kwctl`) asegura que tanto las extracciones de firmas como los cĂ¡lculos de verificaciĂ³n estĂ©n en cachĂ©.
Las entradas en cachĂ© expiran automĂ¡ticamente despuĂ©s de 60 segundos para ayudar a prevenir que se sirvan datos obsoletos.

== Almacenamiento en el cachĂ©.

Los resultados de la verificaciĂ³n de firmas se almacenan en cachĂ© durante un minuto.

Los SDKs proporcionan funciones similares a las siguientes:

* {blank}
+
[subs="+attributes",rust]
----
verify_pub_keys_image(
    image_url: string,
    vector_of_pub_keys: vector<string>,
    vector_of_sigstore_annotations: Vector<(key, value: string)>
    )
    returns (is_trusted: bool, digest_of_verified_image: string)
----

* {blank}
+
[subs="+attributes",rust]
----
verify_keyless_exact_match(
    image_url: string,
    vector_of_tuples_issuer_and_subject: vector<(issuer, subject: string)>,
    vector_of_sigstore_annotations: vector<(key, value: string)>
    )
    returns (is_trusted: bool, digest_of_verified_image: string)
----

Ambas funciones verifican que la imagen estĂ© firmada y satisfaga las restricciones.

[NOTE]
====
En caso de Ă©xito, las funciones devuelven el resumen de la imagen verificada.
Ahora es responsabilidad de la directiva asegurar que los contenedores se instancien a partir de ese resumen, y no de una etiqueta que puede no coincidir con esa suma de comprobaciĂ³n (y por lo tanto estar comprometida).
====


== Un ejemplo

El equipo de {admc-short-name} https://github.com/kubewarden/verify-image-signatures[proporciona una directiva de verificador] que impone las firmas de Sigstore para todos los contenedores.
EstĂ¡ construido utilizando Rust y con el SDK de Rust.
La directiva asegura que los contenedores estĂ©n firmados, y opcionalmente, muta las solicitudes. La mutaciĂ³n aĂ±ade la suma de comprobaciĂ³n verificada a la etiqueta de la imagen.
Consulta la documentaciĂ³n para mĂ¡s detalles.

Esta directiva puede cubrir todas tus necesidades, pero en caso de que prefieras una experiencia de usuario diferente, por supuesto puedes construir sobre ella o sobre cualquiera de los otros SDKs.

== Contrato del protocolo WaPC

En caso de que estĂ©s implementando tu propio SDK de lenguaje, estas son las funciones que una directiva, que verifica firmas, puede usar:

=== funciĂ³n waPC - `v2/verify`

==== `SigstorePubKeyVerify` entrada

[,hcl]
----
{
  type: "SigstorePubKeyVerify",

  # **mandatory**: image URI to verify
  "image": string,
  "pub_keys": [
    # PEM-encoded public keys
    string
    ],
  # optional:
  "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
}
----

==== `SigstorePubKeyVerify` salida

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `SigstoreKeylessVerify` entrada

[,hcl]
----
{
  type: "SigstoreKeylessVerify",

  # mandatory: image URI to verify
  "image": string,
  "keyless": [
    # list of (issuer, subject) tuples
    {
      # OIDC issuer
      "issuer": string,
      # signature subject (mail, CI URL, ...)
      "subject": string
    }
  ],
  # optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `SigstoreKeylessVerify` salida

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `SigstoreKeylessPrefixVerify` entrada

[,hcl]
----
{
  type: "SigstoreKeylessPrefixVerify",

  # mandatory: image URI to verify
  "image": string,
  "keyless_prefix": [
    # list of (issuer, url_prefix) tuples
    {
      # OIDC issuer
      "issuer": string,
      # URL Prefix of subject (CI URL, ...)
      "url_prefix": string
    }
  ],
  # optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `SigstoreKeylessPrefixVerify` salida

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `SigstoreGithubActionsVerify` entrada

[,hcl]
----
{
  type: "SigstoreGithubActionsVerify",

  # mandatory: image URI to verify
  "image": string,
  # GitHub owner
  "owner": string,
  # optional:
  # GitHub repository
  "repo": string
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `SigstoreGithubActionsVerify` salida

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `SigstoreCertificateVerify` entrada

[,hcl]
----
{
  type: "SigstoreCertificateVerify",

  # mandatory: image URI to verify
  "image": string,
  # PEM-encoded certificated used to
  # verify the signature.
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM encoded
  # certificate string.
  "certificate": [byte(int), ..., byte(int)],
  # Optional - certificate chain used to
  # verify the provided certificate.
  # When not specified, the certificate
  # is assumed to be trusted.
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM encoded
  # certificate string.
  "certificate_chain": [
    [byte(int), ..., byte(int)],
    ...
    [byte(int), ..., byte(int)]
  ],
  # Require the signature layer to have
  # a Rekor bundle.
  # Having a Rekor bundle allows further
  # checks to be performed, e.g. ensuring
  # the signature has been produced during
  # the validity time frame of the cert.
  # Recommended to set to `+true+`
  require_rekor_bundle: bool,
  # Optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `SigstoreCertificateVerify` salida

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

=== funciĂ³n waPC - `v1/verify`

==== `SigstorePubKeyVerify` entrada

[,hcl]
----
{
  "SigstorePubKeyVerify": {
    # **mandatory**: image URI to verify
    "image": string,
    "pub_keys": [
      # PEM-encoded public keys
      string
    ],
    # optional:
    "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
  }
}
----

==== `SigstorePubKeyVerify` salida

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `SigstoreKeylessVerify` entrada

[,hcl]
----
{
  "SigstoreKeylessVerify": {
    # mandatory: image URI to verify
    "image": string,
    "keyless": [
      # list of (issuer, subject) tuples
      {
        # OIDC issuer
        "issuer": string,
        # signature subject (mail, CI URL, ...)
        "subject": string
      }
    ],
    # optional:
    "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
  }
}
----

==== `SigstoreKeylessVerify` salida

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----
