include::partial$variables.adoc[]
= CreaciĂ³n de una nueva directiva
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-04-30
:page-revdate: {revdate}
:description: Crea una directiva que evalĂºe todos los recursos con espacio de nombres y prohĂ­ba su creaciĂ³n en el espacio de nombres predeterminado para el aprendizaje prĂ¡ctico.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "create-policy"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "creating a policy", "open policy agent", "opa", "rego"]
:sidebar_label: CreaciĂ³n de una nueva directiva
:current-version: {page-origin-branch}

Puedes crear una directiva de ejemplo que ayude a entender los conceptos importantes.

[NOTE]
====
Hay una https://github.com/kubewarden/opa-policy-template[kubewarden/opa-policy-template] que puedes usar para portar una directiva existente.
====


== Requisitos

EscribirĂ¡s, compilarĂ¡s y ejecutarĂ¡s una directiva en esta secciĂ³n.
Necesitas estas herramientas para completar este tutorial:

* https://github.com/open-policy-agent/opa/releases[`opa`]: usarĂ¡s la CLI de `opa` para construir tu directiva como un objetivo `wasm`.
* https://github.com/kubewarden/kwctl/releases[`kwctl`]: usarĂ¡s `kwctl` para ejecutar tu directiva construida.

== La directiva

Vas a crear una directiva que evalĂºe cualquier tipo de recurso con espacio de nombres.
Su objetivo es prohibir la creaciĂ³n de cualquier recurso si el espacio de nombres objetivo es `default`. De lo contrario, la solicitud es aceptada.
Comienza creando una carpeta llamada `opa-policy`.

Crea una carpeta llamada `data` en la carpeta `opa-policy`.
Esta carpeta tiene los objetos `AdmissionReview` grabados del servidor de la API de Kubernetes.
Se han reducido por simplicidad para el ejercicio, asĂ­ puedes centrarte en los aspectos que importan.

Crea un archivo `default-ns.json` con el siguiente contenido dentro del directorio `data`:

[subs="+attributes",json]
----
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
    "operation": "CREATE",
    "object": {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata": {
        "name": "nginx",
        "namespace": "default",
        "uid": "04dc7a5e-e1f1-4e34-8d65-2c9337a43e64"
      }
    }
  }
}
----

Esto simula la creaciĂ³n de una operaciĂ³n de pod dentro del espacio de nombres `default`.
Ahora, crea otro ejemplo de solicitud en `other-ns.json` dentro del directorio `data`:

[subs="+attributes",json]
----
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
    "operation": "CREATE",
    "object": {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata": {
        "name": "nginx",
        "namespace": "other",
        "uid": "04dc7a5e-e1f1-4e34-8d65-2c9337a43e64"
      }
    }
  }
}
----

Puedes ver que esto simula otra solicitud de creaciĂ³n de pod, esta vez bajo un espacio de nombres llamado `other`.

Vuelve a tu carpeta `opa-policy` y comienza a escribir tu directiva Rego.

En esta carpeta, crea un archivo llamado `request.rego` en la carpeta `opa-policy`.
El nombre puede ser cualquier cosa, pero lo usarĂ¡s para este ejercicio.
Este es un archivo Rego que contiene cĂ³digo de utilidad relacionado con la solicitud/respuesta en sĂ­.
En particular, te permite simplificar tu cĂ³digo de directiva y reutilizar esta parte comĂºn en diferentes directivas.

El contenido es:

[,rego]
----
package policy

import data.kubernetes.admission

main = {
    "apiVersion": "admission.k8s.io/v1",
    "kind": "AdmissionReview",
    "response": response,
}

response = {
    "uid": input.request.uid,
    "allowed": false,
    "status": {"message": reason},
} {
    reason = concat(", ", admission.deny)
    reason != ""
} else = {
    "uid": input.request.uid,
    "allowed": true,
} {
    true
}
----

No tienes necesidad, en este momento, de entrar en detalle en el cĂ³digo Rego.
Puedes aprender sobre ello en su https://www.openpolicyagent.org/docs/latest/policy-language/[sitio web].

En este caso, devuelve ya sea `allowed: true` o `allowed: false`.
Esto depende de si el otro paquete, `data.kubernetes.admission`, tiene alguna declaraciĂ³n `deny` que evalĂºe a `true`.

Si alguna `data.kubernetes.admission.deny` evalĂºa a `true`, la `response` aquĂ­ evalĂºa al primer bloque.
De lo contrario, evalĂºa al segundo bloque, lo que lleva a la aceptaciĂ³n.
Debido a que ningĂºn bloque `deny` evaluĂ³ a `true`, esto significa que la directiva estĂ¡ aceptando la solicitud.

Esto es solo el shell de la directiva, la utilidad.
Ahora, creas otro archivo, llamado, por ejemplo, `policy.rego` dentro de nuestra carpeta `opa-policy` con estos contenidos:

[,rego]
----
package kubernetes.admission

deny[msg] {
    input.request.object.metadata.namespace == "default"
    msg := "it is forbidden to use the default namespace"
}
----

Esta es la parte importante de tu directiva.
La declaraciĂ³n `deny` evalĂºa a `true` si todas las declaraciones dentro de ella evalĂºan a `true`.
En este caso, solo hay una declaraciĂ³n, comprobando si el espacio de nombres es `default`.

Por diseĂ±o de Open Policy Agent,
`input` tiene el objeto consultable con el objeto `AdmissionReview`,
asĂ­ que podemos inspeccionarlo de manera conveniente.

Si todo ha ido bien, tu Ă¡rbol deberĂ­a verse como el siguiente:

[subs="+attributes",console]
----
.
â”œâ”€â”€ data
â”‚   â”œâ”€â”€ default-ns.json
â”‚   â””â”€â”€ other-ns.json
â”œâ”€â”€ policy.rego
â””â”€â”€ request.rego

1 directory, 4 files
----
