include::partial$variables.adoc[]
= Glossﾃ｡rio
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-04
:page-revdate: {revdate}
:description: Explore recursos e configuraﾃｧﾃｵes principais relacionados a {admc-name} polﾃｭticas em ambientes Kubernetes para mais informaﾃｧﾃｵes.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["glossary"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "glossary"]
:sidebar_label: Glossﾃ｡rio
:sidebar_position: 90
:current-version: {page-origin-branch}

== Um

=== Polﾃｭtica de Admissﾃ｣o

Um recurso em nﾃｭvel de namespace. A polﾃｭtica processa apenas aquelas solicitaﾃｧﾃｵes que visam o namespace no qual a Polﾃｭtica de Admissﾃ｣o estﾃ｡ definida.

== C

=== ClusterAdmissionPolicy

Uma <<_admissionpolicy,Polﾃｭtica de Admissﾃ｣o>> que visa recursos em todo o cluster.

=== ClusterReport

Um <<_report,Relatﾃｳrio>> e um Relatﾃｳrio de Cluster armazenam os resultados das varreduras de polﾃｭticas. Qual deles ﾃｩ usado depende do escopo do recurso.

== K

=== kwctl

Uma ferramenta CLI para gerar e testar arquivos YAML do Kubernetes para implantaﾃｧﾃ｣o de polﾃｭticas.

== M

=== MutatingWebhookConfiguration

Um https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[recurso do Kubernetes] criado pelo controlador {admc-short-name} para informar ao Kubernetes onde enviar um `AdmissionReview`.
Em outras palavras, ﾃｩ assim que um controlador {admc-short-name} informa ao Kubernetes onde encontrar uma polﾃｭtica de mutaﾃｧﾃ｣o de recurso.

== P

=== Relatﾃｳrio

Um Relatﾃｳrio e um <<_clusterreport,Relatﾃｳrio de Cluster>> armazenam os resultados das varreduras de polﾃｭticas. Qual deles ﾃｩ usado depende do escopo do recurso.

[#_policy_server]
=== PolicyServer

Um Servidor de Polﾃｭticas valida as solicitaﾃｧﾃｵes recebidas executando {admc-short-name} polﾃｭticas sobre elas.

== V

=== ValidatingWebhookConfiguration

Um https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[recurso do Kubernetes] criado pelo controlador {admc-short-name} para informar ao Kubernetes onde enviar um `AdmissionReview`.
Em outras palavras, ﾃｩ assim que {admc-short-name} informa ao Kubernetes onde encontrar uma polﾃｭtica de validaﾃｧﾃ｣o de recurso.

== Q

=== waPC

Chamadas de Procedimento WebAssembly. https://wapc.io.

=== WASI

Interface de Sistema WebAssembly. https://wasi.dev.

=== Wasm

Um formato de instruﾃｧﾃ｣o binﾃ｡ria para uma mﾃ｡quina virtual baseada em pilha. Projetado para implantaﾃｧﾃ｣o na web. https://webassembly.org.

=== Wasmtime

Um runtime para WebAssembly. https://wasmtime.dev.
