include::partial$variables.adoc[]
= GlossûÀrio
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-04-30
:page-revdate: {revdate}
:description: Explore recursos e configuraûÏûçes principais relacionados a {project-name} polûÙticas em ambientes Kubernetes para mais informaûÏûçes.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["glossary"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "glossary"]
:sidebar_label: GlossûÀrio
:sidebar_position: 90
:current-version: {page-origin-branch}

== Um

=== PolûÙtica de AdmissûÈo

Um recurso em nûÙvel de namespace. A polûÙtica processa apenas aquelas solicitaûÏûçes que visam o namespace no qual a PolûÙtica de AdmissûÈo estûÀ definida.

== C

=== ClusterAdmissionPolicy

Uma <<_admissionpolicy,PolûÙtica de AdmissûÈo>> que visa recursos em todo o cluster.

=== ClusterReport

Um <<_report,Relatû°rio>> e um Relatû°rio de Cluster armazenam os resultados das varreduras de polûÙticas. Qual deles ûˋ usado depende do escopo do recurso.

== K

=== kwctl

Uma ferramenta CLI para gerar e testar arquivos YAML do Kubernetes para implantaûÏûÈo de polûÙticas.

== M

=== MutatingWebhookConfiguration

Um https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[recurso do Kubernetes] criado pelo controlador {short-project-name} para informar ao Kubernetes onde enviar um `AdmissionReview`.
Em outras palavras, ûˋ assim que um controlador {short-project-name} informa ao Kubernetes onde encontrar uma polûÙtica de mutaûÏûÈo de recurso.

== P

=== Relatû°rio

Um Relatû°rio e um <<_clusterreport,Relatû°rio de Cluster>> armazenam os resultados das varreduras de polûÙticas. Qual deles ûˋ usado depende do escopo do recurso.

[#_policy_server]
=== PolicyServer

Um Servidor de PolûÙticas valida as solicitaûÏûçes recebidas executando {short-project-name} polûÙticas sobre elas.

== V

=== ValidatingWebhookConfiguration

Um https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[recurso do Kubernetes] criado pelo controlador {short-project-name} para informar ao Kubernetes onde enviar um `AdmissionReview`.
Em outras palavras, ûˋ assim que {short-project-name} informa ao Kubernetes onde encontrar uma polûÙtica de validaûÏûÈo de recurso.

== Q

=== waPC

Chamadas de Procedimento WebAssembly. https://wapc.io.

=== WASI

Interface de Sistema WebAssembly. https://wasi.dev.

=== Wasm

Um formato de instruûÏûÈo binûÀria para uma mûÀquina virtual baseada em pilha. Projetado para implantaûÏûÈo na web. https://webassembly.org.

=== Wasmtime

Um runtime para WebAssembly. https://wasmtime.dev.
