include::partial$variables.adoc[]

= InstalaĂ§ĂŁo de air gap com Hauler
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Use o Hauler para instalar {project-name} em ambientes air-gapped.
:keywords: ["{project-name}", kubewarden, kubernetes, air gap installation, hauler]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual-do-operador, air gap, instalaĂ§ĂŁo, hauler

Este guia mostra como instalar {project-name} em ambientes air-gapped usando link:https://docs.hauler.dev/docs/intro[Hauler]. O Hauler Ă© uma ferramenta que ajuda os usuĂˇrios a executar cargas de trabalho em ambientes air-gapped. Ele move os recursos necessĂˇrios para os apps para esses ambientes air-gapped.

{short-project-name} fornece um arquivo de manifesto com todos os recursos necessĂˇrios para executar {short-project-name} em um ambiente privado. Esta documentaĂ§ĂŁo descreve como vocĂŞ pode usĂˇ-lo. Consulte a documentaĂ§ĂŁo do Hauler para saber mais sobre ele.

O fluxo de trabalho bĂˇsico usando o manifesto do Hauler Ă©:

. Obtenha-o a partir de uma pĂˇgina de lanĂ§amento do {short-project-name}
. Carregue todos os recursos necessĂˇrios para executar {short-project-name} em um armazenamento local
. Exporte-os para um arquivo
. Mova o arquivo para o ambiente privado
. Carregue os recursos no Hauler em execuĂ§ĂŁo dentro do ambiente privado
. Copie tudo para um registro, para ser usado no processo de instalaĂ§ĂŁo, em seu ambiente air-gapped.

== Baixe o manifesto do Hauler da pĂˇgina de lanĂ§amento do Helm chart.

Baixe `hauler_manifest.yml` da {short-project-name} link:https://github.com/kubewarden/helm-charts/releases/[pĂˇgina de lanĂ§amento].

Sincronize os recursos definidos no manifesto para o seu armazenamento do Hauler:

[source,shell]
----
hauler store sync --filename hauler_manifest.yaml
----

O Hauler baixa todos os recursos do manifesto para o armazenamento local. Este processo leva alguns minutos. Quando concluĂ­do, vocĂŞ pode ver os recursos sincronizados com o comando `hauler store info`.

== Gere o arquivo tarball com todos os recursos {short-project-name}.

Execute o comando Hauler para exportar todos os recursos previamente carregados no armazenamento para um arquivo:

[source,shell]
----
hauler store save --filename kubewarden-resources.tar.zst
----

[NOTE]
====

As imagens de contĂŞiner {short-project-name} suportam as arquiteturas x86_64 e famĂ­lia de arquiteturas ARM. Portanto, quando vocĂŞ salva o recurso no arquivo, pode ver mensagens de aviso como esta:

[source,shell]
----
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kyverno/policy-reporter:3.3.3]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kyverno/policy-reporter-ui:2.4.1]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/policy-server:v1.27.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/audit-scanner:v1.27.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/rancher/kuberlr-kubectl:v5.0.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/kubewarden-controller:v1.27.0]
----

Para evitar essa mensagem de aviso, vocĂŞ pode definir a flag `--platform` do CLI para definir qual arquitetura de plataforma deseja salvar no arquivo.

====

== Transfira o tarball para o seu ambiente isolado.

Agora que vocĂŞ tem todos os recursos {short-project-name} em `kubewarden-resources.tar.zst`, copie-os para o seu ambiente air-gapped e carregue-os no armazenamento do Hauler lĂˇ:

[source,shell]
----
hauler store load --filename kubewarden-resources.tar.zst
# Check if the resources are loaded
hauler store info
----

Agora todos os recursos necessĂˇrios para instalar {short-project-name} estĂŁo no armazenamento do Hauler em seu ambiente isolado.

== Popule o registro privado.

Para usar os recursos do seu armazenamento Hauler, Ă© necessĂˇrio tornĂˇ-los disponĂ­veis em um registro interno. VocĂŞ pode usar comandos do Hauler para copiĂˇ-los para o seu registro privado.

[source,shell]
----
hauler store copy registry://localhost:5000
----

VocĂŞ tambĂ©m pode executar o Hauler para iniciar um registro com todos os recursos do armazenamento. Este registro Ă© inseguro, e vocĂŞ precisa adaptar a configuraĂ§ĂŁo do cluster:

[source,shell]
----
# Find IP address of your host
# hostname -I

# Update registries.yaml for k3s based cluster to allow insecure access
# mirrors:
#   "<HOST_IP>:5000":
#     endpoint:
#       - "http://<HOST_IP>:5000"
# configs:
#   "<HOST_IP>:5000":
#     tls:
#       insecure_skip_verify: true

# Configure policy-server to allow pulling policies from insecure sources
# helm install .. kubewarden-defaults .. --set policyServer.insecureSources[0]=<HOST_IP:5000>

hauler store serve registry
----

Isso inicia um registro no endereĂ§o `localhost:5000`. A partir deste ponto, vocĂŞ pode usar outros comandos como Skopeo para copiar todas as imagens de contĂŞiner, mĂłdulos de polĂ­tica e grĂˇficos Helm usados pelo {short-project-name} para o seu registro privado.

== Instale o {short-project-name}

Agora que seu registro privado tem tudo o que Ă© necessĂˇrio, vocĂŞ pode instalar {short-project-name}. A diferenĂ§a em relaĂ§ĂŁo a uma instalaĂ§ĂŁo padrĂŁo do {short-project-name} Ă© que vocĂŞ precisa alterar o registro nas imagens de contĂŞiner e polĂ­ticas para ser o registro privado. AlĂ©m disso, vocĂŞ precisa instalar os grĂˇficos Helm dos artefatos OCI.

Instale a pilha {short-project-name}:

[source,shell]
----
helm install --wait -n kubewarden kubewarden-crds --create-namespace \
    oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-crds
helm install --wait -n kubewarden kubewarden-controller \
    --set "global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>" \
    oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-controller
----

[CAUTION]
====

Para usar o sub-grĂˇfico PolicyReporter disponĂ­vel no grĂˇfico `kubewarden-controller`, vocĂŞ precisa definir outros valores especĂ­ficos para o sub-grĂˇfico em um ambiente air-gapped. Veja um exemplo abaixo:

[source,shell]
----
helm install --wait -n kubewarden kubewarden-controller oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-controller \
    --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set auditScanner.policyReporter=true \
    --set policy-reporter.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.image.repository=kyverno/policy-reporter \
    --set policy-reporter.ui.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.ui.image.repository=kyverno/policy-reporter-ui
----

Ă‰ necessĂˇrio definir `auditScanner.policyReporter` e quatro outros valores para habilitar o sub-grĂˇfico e configurar o registro e repositĂłrio com a localizaĂ§ĂŁo do armazenamento da imagem do Policy Reporter. Para mais informaĂ§Ăµes sobre os valores do sub-grĂˇfico de relatĂłrio de polĂ­ticas, consulte o \link: \https://kyverno.github.io/policy-reporter-docs/getting-started/helm.html[documentaĂ§ĂŁo do Policy Reporter].

====

[source,shell]
----
helm install --wait -n kubewarden \
  kubewarden-defaults oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-defaults \
  --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>
----

Por fim, configure cada Servidor de PolĂ­ticas para buscar polĂ­ticas do seu registro privado. Veja a seĂ§ĂŁo xref:/howtos/policy-servers/02-private-registry.adoc[usando registro privado] da documentaĂ§ĂŁo.

Agora crie {short-project-name} polĂ­ticas em seu cluster. As polĂ­ticas devem estar disponĂ­veis em seu registro privado.

[source,yaml]
----
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://<REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policies/pod-privileged:v0.2.2
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
  mutating: false
EOF
----

[CAUTION]
====

Os recursos `PolicyServer` devem usar a imagem disponĂ­vel em seu registro privado.
Por exemplo:

[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: reserved-instance-for-tenant-a
spec:
  image: <REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policy-server:v1.3.0
  replicas:
----

====