:sidebar_label: Policy Server Kommandozeilenschnittstellenreferenz
:sidebar_position: 121
:title: Policy Server Kommandozeilenschnittstelle
:description: Erkunden Sie die Hilfe und Optionen der Kommandozeilenschnittstelle von \`policy-server`, um das Programm anzupassen und auszufГјhren.
:keywords: [cli, Referenz, policy-server]
:doc-persona: [kubewarden-operator]
:doc-type: [Referenz]
:doc-topic: [Betriebsanleitung]
include::partial$variables.adoc[]
:revdate: 2026-03-18
:page-revdate: {revdate}

= {title}
:page-languages: [en, de, es, fr, ja, pt, zh]

== Befehlszeilenhilfe fГјr `policy-server`

Dieses Dokument enthГӨlt den Hilfetext fГјr das `policy-server`
Befehlszeilenprogramm.

*BefehlsГјbersicht:*

* link:#policy-server[`policy-server`]
* link:#policy-server-docs[`policy-server docs`]

=== `policy-server`

*Verwendung:* `policy-server ++[+OPTIONS+]++ ++[+COMMAND+]++`

==== *Unterbefehle:*

* `docs` вҖ” Generiert die Markdown-Dokumentation fГјr policy-server-Befehle

==== *Optionen:*

* `--addr ++<+BIND_ADDRESS+>++` вҖ” Bindet an die ADRESSE
+
Standardwert: `0.0.0.0`
* `--always-accept-admission-reviews-on-namespace ++<+NAMESPACE+>++` вҖ”
Akzeptiert immer AdmissionReviews, die auf den angegebenen Namespace abzielen
* `--cert-file ++<+CERT_FILE+>++` вҖ” Pfad zu einer X.509-Zertifikatdatei fГјr HTTPS
* `--client-ca-file ++<+CLIENT_CA_FILE+>++` вҖ” Pfad zu einer CA-Zertifikatdatei, die das Client-Zertifikat ausgestellt hat. Erforderlich, um mTLS zu aktivieren
* `--daemon` вҖ” Wenn gesetzt, wird der policy-server im abgetrennten Modus als Daemon ausgefГјhrt
* `--daemon-pid-file ++<+DAEMON-PID-FILE+>++` вҖ” Pfad zur PID-Datei,
wird nur im Daemon-Modus verwendet
+
Standardwert: `policy-server.pid`
* `--daemon-stderr-file ++<+DAEMON-STDERR-FILE+>++` вҖ” Pfad zur Datei, die stderr enthГӨlt, wird nur im Daemon-Modus verwendet
* `--daemon-stdout-file ++<+DAEMON-STDOUT-FILE+>++` вҖ” Pfad zur Datei, die stdout enthГӨlt, wird nur im Daemon-Modus verwendet
* `--disable-timeout-protection` вҖ” Deaktiviert den ZeitГјberschreitungsschutz fГјr Richtlinien
* `--docker-config-json-path ++<+DOCKER_CONFIG+>++` вҖ” Pfad zu einem Docker config.json-ГӨhnlichen Pfad. Kann verwendet werden, um Authentifizierungsdetails fГјr die Registry anzugeben
* `--enable-metrics` вҖ” Metriken aktivieren
* `--enable-pprof` вҖ” pprof-Profiling aktivieren
* `--ignore-kubernetes-connection-failure` вҖ” Bei einem Fehler der Kubernetes-Verbindung nicht mit einem Fehler beenden. Dies wird dazu fГјhren, dass kontextabhГӨngige Richtlinien fehlschlagen, wenn keine Verbindung zu Kubernetes besteht.
* `--key-file ++<+KEY_FILE+>++` вҖ” Pfad zu einer X.509-PrivatschlГјsseldatei fГјr HTTPS
* `--log-fmt ++<+LOG_FMT+>++` вҖ” Protokollausgabeformat
+
Standardwert: `text`
+
MГ¶gliche Werte: `text`, `json`, `otlp`
* `--log-level ++<+LOG_LEVEL+>++` вҖ” Protokollebene
+
Standardwert: `info`
+
MГ¶gliche Werte: `trace`, `debug`, `info`, `warn`, `error`
* `--log-no-color` вҖ” Farbige Ausgabe fГјr Protokolle deaktivieren
* `--policies ++<+POLICIES_FILE+>++` вҖ” YAML-Datei, die die zu ladenden Richtlinien und deren Einstellungen enthГӨlt
+
Standardwert: `policies.yml`
* `--policies-download-dir ++<+POLICIES_DOWNLOAD_DIR+>++` вҖ” Download-Pfad fГјr die Richtlinien
+
Standardwert: `.`
* `--policy-timeout ++<+MAXIMUM_EXECUTION_TIME_SECONDS+>++` вҖ”
Unterbricht die Richtlinienauswertung nach der angegebenen Zeit
+
Standardwert: `2`
* `--port ++<+PORT+>++` вҖ” PORT Гјberwachen
+
Standardwert: `3000`
* `--readiness-probe-port ++<+READINESS_PROBE_PORT+>++` вҖ”
Expose readiness endpoint on READINESS+_PROBE_+PORT
+
Standardwert: `8081`
* `--sigstore-cache-dir ++<+SIGSTORE_CACHE_DIR+>++` вҖ” Verzeichnis, das zum Zwischenspeichern von Sigstore-Daten verwendet wird
+
Standardwert: `sigstore-data`
* `--sources-path ++<+SOURCES_PATH+>++` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Hosts in der Registry, benutzerdefinierte CAsвҖҰ)
* `--verification-path ++<+VERIFICATION_CONFIG_PATH+>++` вҖ” YAML-Datei, die Verifizierungsinformationen enthГӨlt (URIs, SchlГјssel, AnnotationenвҖҰ)
* `--workers ++<+WORKERS_NUMBER+>++` вҖ” Anzahl der zu erstellenden Worker-Threads

=== `policy-server docs`

Generiert die Markdown-Dokumentation fГјr die policy-server-Befehle

*Verwendung:* `policy-server docs --output ++<+FILE+>++`

==== *Optionen:*

* `-o`, `--output ++<+FILE+>++` вҖ” Pfad, unter dem die Dokumentationsdatei gespeichert wird

Dieses Dokument wurde automatisch von clap-markdown generiert.
