include::partial$variables.adoc[]
= Glossaire
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Explorez les ressources clﾃｩs et les configurations liﾃｩes aux stratﾃｩgies {project-name} dans les environnements Kubernetes pour plus d'informations.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["glossary"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "glossary"]
:sidebar_label: Glossaire
:sidebar_position: 90
:current-version: {page-origin-branch}

== R

=== AdmissionPolicy

Une ressource ﾃ l'ﾃｩchelle de l'espace de noms. La stratﾃｩgie ne traite que les demandes ciblant l'espace de noms dans lequel l'AdmissionPolicy est dﾃｩfinie.

== C

=== ClusterAdmissionPolicy

Une <<_admissionpolicy,AdmissionPolicy>> qui cible des ressources ﾃ l'ﾃｩchelle du cluster.

=== ClusterReport

Un <<_report,Report>> et un ClusterReport stockent les rﾃｩsultats des analyses de stratﾃｩgie. Le choix de l'un ou de l'autre dﾃｩpend de la portﾃｩe de la ressource.

== K

=== kwctl

Un outil CLI pour gﾃｩnﾃｩrer et tester des fichiers YAML Kubernetes pour le dﾃｩploiement de stratﾃｩgies.

== L

=== MutatingWebhookConfiguration

Un https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[ressource Kubernetes] crﾃｩﾃｩ par le contrﾃｴleur {short-project-name} pour informer Kubernetes oﾃｹ envoyer un `AdmissionReview`.
En d'autres termes, c'est ainsi qu'un contrﾃｴleur {short-project-name} informe Kubernetes oﾃｹ trouver une stratﾃｩgie de mutation de ressource.

== P

=== Rapport

Un Report et un <<_clusterreport,ClusterReport>> stockent les rﾃｩsultats des analyses de stratﾃｩgie. Le choix de l'un ou de l'autre dﾃｩpend de la portﾃｩe de la ressource.

[#_policy_server]
=== PolicyServer

Un PolicyServer valide les demandes entrantes en exﾃｩcutant des stratﾃｩgies {short-project-name} contre les demandes.

== V

=== ValidatingWebhookConfiguration

Un https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[ressource Kubernetes] crﾃｩﾃｩ par le contrﾃｴleur {short-project-name} pour informer Kubernetes oﾃｹ envoyer un `AdmissionReview`.
En d'autres termes, c'est ainsi que {short-project-name} informe Kubernetes oﾃｹ trouver une stratﾃｩgie de validation de ressource.

== M

=== waPC

Appels de procﾃｩdure WebAssembly. https://wapc.io.

=== WASI

Interface systﾃｨme WebAssembly. https://wasi.dev.

=== Wasm

Un format d'instruction binaire pour une machine virtuelle basﾃｩe sur une pile. Conﾃｧu pour le dﾃｩploiement web. https://webassembly.org.

=== Wasmtime

Un composant d'exﾃｩcution pour WebAssembly. https://wasmtime.dev.
