include::partial$variables.adoc[]
= Swift
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprende a utilizar el compilador de Swift con soporte para WebAssembly a través de SwiftWasm para acceder a herramientas para construir directivas {project-name}.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "swift"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "swift"]
:sidebar_label: Swift
:sidebar_position: 50
:current-version: {page-origin-branch}

Como se indica en el https://swift.org/[sitio web oficial]:

____
Swift es un lenguaje de programación de propósito general que es accesible para los recién llegados y potente para los expertos.
Es rápido, moderno, seguro y un placer escribir.
____

El compilador de Swift aún no tiene soporte para WebAssembly, sin embargo, el proyecto https://swiftwasm.org/[SwiftWasm] proporciona un compilador parcheado con esta capacidad.

El equipo de SwiftWasm está trabajando para fusionar estos cambios en el proyecto Swift.
Mientras tanto, puedes utilizar la cadena de herramientas proporcionada por el proyecto SwiftWasm para construir directivas {project-name}.

[NOTE]
====

No necesitas un sistema Apple para escribir o ejecutar código Swift. Todo se puede hacer también en una máquina Linux o en Windows (utilizando Docker para Windows).
====


== Estado actual

Los autores de directivas pueden utilizar los siguientes recursos:

* https://github.com/kubewarden/policy-sdk-swift[{short-project-name} SDK de Swift]: esto proporciona un conjunto de ``struct``s y funciones que simplifican el proceso de escritura de directivas.
* https://github.com/kubewarden/swift-policy-template[{short-project-name} proyecto de plantilla de Swift]: utiliza esta plantilla para crear una directiva basada en Swift.
La plantilla viene con una directiva funcional y un conjunto de GitHub Actions para automatizar su ciclo de vida.

No hay limitaciones severas con Swift, solo algunos problemas menores:

* Es crítico realizar algunas optimizaciones post-construcción antes de utilizar la directiva _"en producción"_:
 .. Elimina el módulo Wasm a través de `wasm-strip` para reducir su tamaño
 .. Optimiza el módulo Wasm a través de `wasm-opt`

La acción de GitHub proporcionada por el repositorio de la plantilla ya se encarga de eso.

== Más ejemplos

https://github.com/kubewarden/pod-runtime-class-policy/tree/swift-implementation[Esta rama del repositorio de GitHub] tiene una {short-project-name} directiva escrita en Swift.
