include::partial$variables.adoc[]
= Registro
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure a inicializaĂ§ĂŁo do logger para logging estruturado em sua polĂ­tica usando a integraĂ§ĂŁo do Go SDK do projeto oneLog.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "logging"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "escrevendo polĂ­ticas", "golang", "go", "logging"]
:current-version: {page-origin-branch}

O Go SDK se integra ao projeto
https://github.com/francoispqt/onelog[`onelog`], quase pronto para uso.
// TODO: Last release 2019. Still good?

O projeto escolheu esta biblioteca como:

* Funciona com binĂĄrios WebAssembly.
Outras soluĂ§Ă”es de logging populares nĂŁo conseguem compilar para o WebAssembly.
* Ele fornece https://github.com/francoispqt/onelog#benchmarks[bom desempenho].
* Suporta logging estruturado.

== Inicializar logger

VocĂȘ precisa inicializar uma estrutura de logger.
Ao realizar esta inicializaĂ§ĂŁo em uma variĂĄvel global, vocĂȘ pode registrar a partir dos dois principais pontos de entrada da polĂ­tica: `validate` e `validate_settings`.

No pacote principal, `main.go` hĂĄ inicializaĂ§ĂŁo para o logger:

[,go]
----
var (
    logWriter = kubewarden.KubewardenLogWriter{}
    logger    = onelog.New(
        &logWriter,
        onelog.ALL, // shortcut for onelog.DEBUG|onelog.INFO|onelog.WARN|onelog.ERROR|onelog.FATAL
    )
)
----

== Consumindo o logger

Agora, vocĂȘ pode usar o objeto `logger` para registrar de onde for necessĂĄrio em sua polĂ­tica:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.Info("validating request")
    // ...
}
----

VocĂȘ pode adicionar logging estruturado:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.WarnWithFields("logging something important", func(e onelog.Entry) {
        e.String("one_field", "a value")
        e.String("another_field", "another value")
    })
    // ...
}
----

VocĂȘ pode consultar
https://pkg.go.dev/github.com/francoispqt/onelog?utm_source=godoc[`onelog` documentaĂ§ĂŁo]
para mais informaĂ§Ă”es.

O logging da polĂ­tica vai para o avaliador de polĂ­ticas
(por exemplo, `kwctl` ou `policy-server`),
e eles registram em nome da polĂ­tica.
Eles usam mecanismos que sĂŁo interoperĂĄveis com outros componentes que permitem rastreamento distribuĂ­do, como
https://www.jaegertracing.io/[Jaeger].
