include::partial$variables.adoc[]
= Registro
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure a inicialização do logger para logging estruturado em sua política usando a integração do Go SDK do projeto oneLog.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "logging"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "escrevendo políticas", "golang", "go", "logging"]
:current-version: {page-origin-branch}

O Go SDK se integra ao projeto
https://github.com/francoispqt/onelog[`onelog`], quase pronto para uso.
// TODO: Last release 2019. Still good?

O projeto escolheu esta biblioteca como:

* Funciona com binários WebAssembly.
Outras soluções de logging populares não conseguem compilar para o WebAssembly.
* Ele fornece https://github.com/francoispqt/onelog#benchmarks[bom desempenho].
* Suporta logging estruturado.

== Inicializar logger

Você precisa inicializar uma estrutura de logger.
Ao realizar esta inicialização em uma variável global, você pode registrar a partir dos dois principais pontos de entrada da política: `validate` e `validate_settings`.

No pacote principal, `main.go` há inicialização para o logger:

[,go]
----
var (
    logWriter = kubewarden.KubewardenLogWriter{}
    logger    = onelog.New(
        &logWriter,
        onelog.ALL, // shortcut for onelog.DEBUG|onelog.INFO|onelog.WARN|onelog.ERROR|onelog.FATAL
    )
)
----

== Consumindo o logger

Agora, você pode usar o objeto `logger` para registrar de onde for necessário em sua política:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.Info("validating request")
    // ...
}
----

Você pode adicionar logging estruturado:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.WarnWithFields("logging something important", func(e onelog.Entry) {
        e.String("one_field", "a value")
        e.String("another_field", "another value")
    })
    // ...
}
----

Você pode consultar
https://pkg.go.dev/github.com/francoispqt/onelog?utm_source=godoc[`onelog` documentação]
para mais informações.

O logging da política vai para o avaliador de políticas
(por exemplo, `kwctl` ou `policy-server`),
e eles registram em nome da política.
Eles usam mecanismos que são interoperáveis com outros componentes que permitem rastreamento distribuído, como
https://www.jaegertracing.io/[Jaeger].
