include::partial$variables.adoc[]
= Einfﾃｼhrung in CEL
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-04
:page-revdate: {revdate}
:description: Erfahren Sie mehr ﾃｼber CEL (Computation Expression Language), eine schnelle, tragbare und sichere Ausdruckssprache, die fﾃｼr Kubernetes-Validierungsregeln und Erweiterungen der Kubernetes-API entwickelt wurde.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "richtlinien schreiben", "cel", "einfﾃｼhrung"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "richtlinien schreiben", "einfﾃｼhrung"]
:current-version: {page-origin-branch}

Die https://cel.dev[Common Expression Language (CEL)] ist eine allgemeine Ausdruckssprache, die darauf ausgelegt ist, schnell, tragbar und sicher in der Ausfﾃｼhrung zu sein. CEL als Sprache ist speichersicher, nebenwirkungsfrei, terminiert (Programme kﾃｶnnen nicht unendlich schleifen) und stark sowie dynamisch typisiert. Sie kﾃｶnnen mehr ﾃｼber CEL erfahren unter https://cel.dev[cel.dev] und es im https://playcel.undistro.io[CEL-Spielplatz] ﾃｼben.

== CEL in Kubernetes

CEL wurde als Sprache fﾃｼr Kubernetes-Validierungsregeln ausgewﾃ､hlt, da CEL-Ausdrﾃｼcke leicht in CRD-Schemas eingebettet und "vorauskompiliert" (bei der Erstellung und Aktualisierung von CRDs) typgeprﾃｼft werden kﾃｶnnen. Aus diesen Grﾃｼnden und aufgrund seiner allgemeinen Eigenschaften ist es ein perfekter Kandidat zur Erweiterung der Kubernetes-API.

Als stabil mit Kubernetes 1.30 gekennzeichnet, kann man CEL bei https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy[ValidatingAdmissionPolicies] und anderen Validierungsregeln verwenden. Fﾃｼr weitere Informationen siehe die Kubernetes-Dokumentation https://kubernetes.io/docs/reference/using-api/cel[hier].

=== Kubernetes-Funktionsbibliotheken

Kubernetes CEL-Validierungsregeln haben Zugriff auf mehrere Funktionsbibliotheken:

* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#list-of-standard-definitions[CEL-Standardfunktionen]
* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#macros[CEL-Standardmakros]
* https://pkg.go.dev/github.com/google/cel-go/ext#Strings[CEL-erweiterte String-Funktionsbibliothek]
* https://kubernetes.io/docs/reference/using-api/cel/#kubernetes-cel-libraries[Kubernetes CEL-Erweiterungsbibliotheken], mit zusﾃ､tzlichen Funktionen fﾃｼr Listen, Regex, URLs, Autorisierer, Mengen, optionale Typen, numerische Vergleiche usw.

== CEL in {project-name}: `cel-policy`

{short-project-name} bietet https://github.com/kubewarden/cel-policy[cel-policy].
Dies ist eine Richtlinie, die den Upstream https://pkg.go.dev/github.com/google/cel-go[cel-go] Interpreter erstellt und bﾃｼndelt sowie die oben aufgefﾃｼhrten verschiedenen Bibliotheken, die fﾃｼr CEL in Kubernetes von `apiextensions-apiserver` verfﾃｼgbar sind.

Darﾃｼber hinaus bﾃｼndelt `cel-policy` eine *{short-project-name} CEL-Erweiterungsbibliothek*, die {short-project-name}s https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[Hostfﾃ､higkeiten als native CEL] exponiert:

* Sigstore-ﾃ彙erprﾃｼfung
* OCI-Interaktion
* Kryptografische Funktionen
* Netzwerkbetrieb
* Zugriff auf Kubernetes-Ressourcen

Das bedeutet, dass `cel-policy` eine Obermenge von Kubernetes CEL ist und rﾃｼckwﾃ､rtskompatibel. Man kann CEL, das fﾃｼr Vanilla Kubernetes geschrieben wurde, wiederverwenden und/oder die von {short-project-name} hinzugefﾃｼgten Funktionen nutzen.

Der `cel-policy` wird kompiliert ausgeliefert und verhﾃ､lt sich wie ein CEL-Interpreter. Die Benutzer der Richtlinie ﾃｼbergeben die gewﾃｼnschten CEL-Ausdrﾃｼcke im `spec.settings` der (Cluster)AdmissionPolicy, und dank der CEL-Funktionen wird der Ausdruck kompiliert und auf Korrektheit typgeprﾃｼft, wenn die (Cluster)AdmissionPolicy erstellt oder aktualisiert wird. Das bedeutet, dass keine benutzerdefinierten Builds des `cel-policy` erforderlich sind.

=== Vorteile von {short-project-name}'s `cel-policy` im Vergleich zu ValidatingAdmissionPolicies

Der {short-project-name} `cel-policy`:

* Sein CEL-Code ist rﾃｼckwﾃ､rtskompatibel mit ValidatingAdmissionPolicies.
* Im Gegensatz zu ValidatingAdmissionPolicies benﾃｶtigt es keine Bindung wie ValidatingAdmissionPolicyBinding, da dies in {short-project-name}'s Definitionen der (Cluster)Admissionpolicies enthalten ist.
* Kann in Clustern bereitgestellt werden, die keine Unterstﾃｼtzung fﾃｼr ValidatingAdmissionPolicies bieten.
* Ist kontextbewusst und nutzt {short-project-name}'s feingranulare Berechtigungen fﾃｼr xref:../../../reference/spec/05-context-aware-policies.adoc[Kontextbewusstsein].
* Wird als (Cluster)AdmissionPolicy bereitgestellt.
* Profitiert von {short-project-name}'s Nachverfolgung und Telemetrie zu Richtlinien.
* Es wird vom Audit Scanner berﾃｼcksichtigt.
* Kann dank kwctl auﾃ歹rhalb des Clusters entwickelt und getestet werden.
