include::partial$variables.adoc[]
= {admc-name}の使用例
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-04
:page-revdate: {revdate}
:sidebar_label: 使用例
:sidebar_position: 74
:description: Kubernetesのさまざまな環境やペルソナにおける{admc-name}のさまざまなユースケースについて学び、複数のシナリオを含みます。
:keywords: {admc-name}、ドキュメント、ユースケース、ケーススタディ
:doc-persona: kubewarden-all
:doc-type: 説明
:doc-topic: 説明

これらは{admc-name}のxref:/personas.adoc[ペルソナ]に関するいくつかの例となるユースケースです。

== ケースA：Kubernetesオペレーターとして、クラスターが安全でコンプライアンスに準拠していることを確認したいです。

私は`kubewarden`ネームスペース内で、デフォルトの設定とともに`kubewarden-defaults`Helmチャートを使用して{admc-name}をデプロイします。これにより、Kubernetesオペレーターの管理下で、デフォルトのPolicyServerと推奨されるClusterAdmissionPoliciesが`kubewarden`ネームスペースにデプロイされます。

オペレーターとして、負荷分散と耐障害性のために、管理されたネームスペース（例えば`kubewarden`）の下にさらに多くのPolicyServersを追加できます。

オペレーターは、さらに多くのClusterAdmissionPoliciesおよびClusterAdmissionPolicyGroupsをデプロイできます。これらは、すべてのKubernetesリソースを、あらゆる種類の操作（GET、CREATE、UPDATE、PATCH、DELETE、PROXY）についてチェックします。これにより、クラスターへの操作が安全でコンプライアンスに準拠していることが保証されます。

具体的には、次のようなメカニズムがあります。

* セキュリティ
* コンプライアンス（業界標準または会社の規則への準拠）
* リソースの最適化（ミューテーティングポリシーを通じて）
* Kubernetes環境のガバナンス（ラベルや命名規則を通じて）
* ベストプラクティス
* イメージの検証

セキュリティの期待は時間とともに変化します。以前はクラスター内で正しかったデプロイメントが、もはやそうでない場合があります。しかし、{admc-short-name}はすでにクラスター内でそれらの操作を受け入れています。これらの状況において、オペレーターはAudit Scanner機能をデプロイできます。これは、定期的に実行され、クラスター内の既存のリソースを評価するCronJobです。これにより、クラスターが安全であり、時間が経過しても準拠していることが確認されます。

オペレーターは、`monitor`モードの代わりに`protect`モードでポリシーを構成でき、クラスターの状態から学びながら操作をブロックしません。

オペレーターは、ログやOpenTelemetry情報を消費することで、ポリシーや{admc-short-name}スタックから情報を受け取ることができます。

== ケースB：Kubernetesオペレーターとして、Kubernetesユーザーが自分のネームスペースでセルフサービスできるようにフレームワークを提供したいと考えています。

オペレーターとして、私は自分が選択したポリシーのセットのために、ケースAのように{admc-short-name}をデプロイします。これにより、他のユーザーが回避できないクラスター内の安全なベースラインが提供されます。

ケースAに加えて、私はネームスペースごとに異なるペルソナを持っています：おそらくチーム、チーム管理者、テストデプロイメントなどです。各ネームスペースの管理者が自分のネームスペースでポリシーサーバーをデプロイできるようにし、ネームスペース単位のAdmissionPoliciesやAdmissionPolicyGroupsも利用できるようにしています。
このアーキテクチャは、彼らが自分のポリシーサーバーとポリシーを制御できることを意味します。ポリシーは彼らのネームスペースにのみ適用され、リソースの使用を彼らのネームスペースに制約します。

また、オペレーターが騒がしいテナントを分離し、高スループットと低遅延が必要なテナントやタスクのために高性能なポリシーサーバーを予約することを許可します。

== ケースC：ポリシー作成者として、私は新しいポリシーを書くために知っているツールや言語を使用したいと考えています。

{admc-short-name}は、ポリシーのターゲット言語としてWebAssemblyにコンパイルできる任意の言語をサポートすることでこれを実現します。これにより、ポリシー作成者はワークフロー（`git`、CI、エディター、専門家による評価など）やツール：言語、言語ライブラリ、テストハーネスやフレームワークなどを再利用できます。

ドメイン固有言語（Rego、CEL、KyvernoのYAML+マクロなど）や汎用言語（Go、Rust、C#、Javascript、Wasmにコンパイルできる任意の言語）を再利用することを許可します。{admc-short-name}は、いくつかの言語に対してファーストクラスのサポートとしてxref:/tutorials/writing-policies/index.adoc[SDKs]を提供します。

{admc-short-name}ポリシーはシンプルまたは複雑なxref:/explanations/context-aware-policies.adoc[コンテキスト対応]ポリシーである可能性があります。
コンテキスト対応ポリシーは、別のワークロードとインターフェースするためにも使用されます（例えば、長時間実行されるサービスから情報を取得するための画像スキャナー）。

== ケースD：システムインテグレーターとして、私はセキュリティとコンプライアンスソリューションの一部として{admc-short-name}を再利用したいと考えています。

システムインテグレーターとして、私は{admc-short-name}を再利用したいと考えており、{admc-short-name}に他のソリューションを含めることで再利用する可能性もあります。

システムインテグレーターとして、私は{admc-short-name}の一部を再利用することができます。例えば、`policy-server`は、Kubernetesクラスター内外のリソースをxref:/howtos/raw-policies.adoc["生ポリシー"]機能を通じて監視するためのものです。

システムインテグレーターは、`kubewarden-controller`をデプロイするか、自分でCRDを管理することを選択できます。彼らは必要に応じて監査スキャナーをデプロイまたはスケールすることを選択できます。

システムインテグレーターは新しいコンポーネントを作成することができます。例えば、イメージスキャナーを作成し、Kubernetesコントローラーにモノリシックな実装を持たずに、コンテキスト対応ポリシーを介してそれとインターフェースを持つことができます。

== 非目標

{admc-short-name}は以下を意図していません：

- Kubernetesのビルトインセキュリティ機能を置き換えるのではなく、それを補完すること：
  - {admc-short-name}はPSPからの移行を提供します。
  - {admc-short-name}の`cel-policy`を使用して、ValidatingAdmissionPoliciesおよびCELポリシーを再利用できます。
  - {admc-short-name}のポリシーは変更可能ですが、Pod Security Admissionは変更できません。
  - {admc-short-name}のポリシーは、{admc-short-name}スタック機能（監査スキャナー、テレメトリ、CRD管理）から恩恵を受けます。
- 侵入検知やランタイムコンテナ隔離のようなランタイムセキュリティを提供すること。
- クラスターのホストシステム保護を提供すること。
- 無限のポリシー実行柔軟性を提供すること。DoS攻撃を防ぐために、ポリシーの処理時間は制限されています。