include::partial$variables.adoc[]
= カスタム認証局
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: {project-name}インストールで使用するためのカスタム認証局を設定して、安全な通信と認証を確保します。
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["distributing-policies", "custom-certificate-authorities"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "カスタム認証局"]
:sidebar_label: カスタム認証局
:sidebar_position: 50
:current-version: {page-origin-branch}

`kwctl` と `policy-server` の両方を使用すると、Open Container Initiative (OCI) レジストリおよび HTTP サーバーからポリシーを取得できます。
ポリシーは OCI レジストリにのみプッシュできます。
デフォルトでは、これにはホスト TLS 検証を伴う HTTPS が使用されます。

システムの認証局 (CA) ストアは、OCI レジストリからの信頼された証明書のチェーンを検証するために使用されます。
標準の {project-name} インストールでは、`policy-server` は Linuxコンテナに付属の CA ストアを使用します。
クライアント側では、`kwctl` がオペレーティングシステムの CA ストアを使用します。

https://github.com/kubewarden/kubewarden-controller[Controller] を使用している場合、xref:/howtos/policy-servers/01-custom-cas.adoc[`spec` フィールド] を介して PolicyServer を設定できます。

[NOTE]
====

`kwctl` と `policy-server` のデフォルトの動作は、システム CA ストアに一致する信頼された証明書を使用して HTTPS を強制します。
`insecure_sources` 設定を使用することで、信頼されていない証明書を使用したり、TLS なしでレジストリと対話することができます。
明らかに、これは本番環境には適していません。
====


== `sources.yaml`ファイル

`kwctl` と `policy-server` のプッシュ・プル動作を `sources.yaml` ファイルを使用して調整できます。

参照の詳細については、xref:../reference/sources_yaml.adoc[`sources.yaml`] 参照を確認してください。
