include::partial$variables.adoc[]
= {project-name}大規模環境における
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: {project-name}を{project-name}で構成し、要求の厳しい大規模環境において高可用性とパフォーマンスを確保します。
:keywords: [kubewarden, "{project-name}", kubernetes, policyservers, production]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: HOWTO(操作方法)
:doc-topic: operator-manual, policy-servers, production
:sidebar_label: 大規模環境でのデプロイメント
:sidebar_position: 21

このセクションでは、要求の厳しい大規模環境における{project-name}の実際のデプロイメントについて詳述します。高可用性とパフォーマンスのために{short-project-name}を構成する方法と、重負荷時に何を期待するかを示しています。

[IMPORTANT]
====
本番環境で{short-project-name}を運用するためのヒントをもっと見たい場合は、xref:/howtos/production-deployments.adoc[本番デプロイメント]のドキュメントをチェックしてください。
====

== 環境の概要

インフラストラクチャは、約20のKubernetesクラスターで構成されています。これらのクラスターの中で最も大きいものは、サイズとリソース量が大きいことが特徴です：

* ノード: 約400
* ネームスペース: 約4,000
* 管理対象リソース:
** ポッド:10,000
** ロールバインディング:13,000
** Ingress:12,000
** デプロイメント:8,000
** サービス:13,000

== {short-project-name}の設定

この環境の要求に応えるために、{short-project-name}はワークロードの分離と高可用性に重点を置いて構成されています。

* ポリシーの実施：22 `ClusterAdmissionPolicies`がクラスター全体で実施されており、ネームスペース特有の`AdmissionPolicies`はありません。
* ポリシーサーバーアーキテクチャ：ワークロードを分離するために、2つの別々の`PolicyServer`デプロイメントが使用されています：
** 1つの`PolicyServer`は、コンテキスト対応ポリシー専用に割り当てられています。
** 2つ目の`PolicyServer`は、すべての他の非コンテキスト対応ポリシーを処理します。
* スケーラビリティとリソース：
** Replicas:各`PolicyServer`デプロイメントは、高いリクエスト量を処理するために15のレプリカを実行します。
** リソースの割り当て：各レプリカには300MBのメモリと4つのCPUコアが割り当てられています。

== パフォーマンスメトリック

この構成は、高いアドミッションリクエスト率を管理しながら、予測可能なパフォーマンスを維持します。

* アドミッションリクエストのスループット：クラスターは、1秒あたり最大300のアドミッションリクエストを処理します（ウェブフックの検証と監査スキャンの両方を含む）。
* ポリシーのレイテンシ：
** 典型的なレイテンシ：コンテキスト対応ポリシーは、一般的に実行に約500msかかります。
** タイムアウト：この高スループット環境では、ウェブフックのタイムアウトは2.5秒に設定されており、`PolicyServer`のタイムアウトは10秒に設定されています。ほとんどのリクエストは迅速ですが、インフラストラクチャはAPIサーバーの安定性を損なうことなく、時折の遅い操作を処理できるように構築されています。

== 監査スキャナーのパフォーマンス

監査スキャナーは、膨大なリソースにわたる継続的なコンプライアンスを確保するために利用されます。

* 頻度:クラスター全体の監査は、4時間ごとに実施されます。
* 設定:監査ジョブは、ランタイムを短縮するために最大の並列性に調整されています：

[source,shell]
----
--parallel-namespaces: "10"
--parallel-resources: "20"
--parallel-policies: "20"
--page-size: "1000"
----

* 監査の所要時間：数万のリソースを持つ最大のクラスターでも、完全な監査ジョブは一定時間内に完了します。
