include::partial$variables.adoc[]
= ValidatingAdmissionPolicyマイグレーション
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: ValidatingAdmissionPolicyを{project-name}に移行するために、kwctlコマンドのマイグレーション手順を使用して、スムーズなポリシー移行を行います。
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["vap-migration"]
:doc-type: ["howto"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "kubernetes", "cel", "vap", "validatingadmissionpolicy"]
:current-version: {page-origin-branch}

Kubernetes v1.26以降、https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/[ValidatingAdmissionPolicy]は、KubernetesでカスタムAdmissionポリシーを記述する方法を提供します。ポリシーは、https://cel.dev/[Common Expression Language (CEL)]を使用して記述され、いくつかのhttps://kubernetes.io/docs/reference/using-api/cel/[Kubernetes特有の拡張]が追加されています。
ValidatingAdmissionPolicyはKubernetes v1.30で安定版となりました。

{project-name}は、変更なしでKubernetes VAPポリシーを実行できるCELポリシーを提供します。
CELポリシーに関する詳細は、{short-project-name}のドキュメント内のxref:../tutorials/writing-policies/CEL/01-intro-cel.adoc[このセクション]でご覧いただけます。
xref:tutorials/writing-policies/CEL/01-intro-cel.adoc#_benefits_of_kubewardens_cel_policy_in_comparison_with_validatingadmissionpolicies[この段落]は、{short-project-name}を使用してVAPポリシーを実行する利点を説明します。

このガイドでは、`kwctl`ツールを使用してVAPポリシーを{short-project-name}に移行する方法を説明します。

== 移行手順

[NOTE]
====
このガイドに従うには、`kwctl`のバージョン1.14.0以上を使用する必要があります。
====


次のYAML定義を含むファイルが与えられた場合、`ValidatingAdmissionPolicy`:

.`ValidatingAdmissionPolicy`定義
[%collapsible]
======
[subs="+attributes",yaml]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "force-liveness-probe"
spec:
  failurePolicy: Fail
  variables:
    - name: containers_without_liveness_probe
      expression: |
        object.spec.template.spec.containers.filter(c, !has(c.livenessProbe)).map(c, c.name)
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  validations:
    - expression: |
        size(variables.containers_without_liveness_probe) == 0
      messageExpression: |
        'These containers are missing a liveness probe: ' + variables.containers_without_liveness_probe.join(' ')
      reason: Invalid
----
======

および`ValidatingAdmissionPolicyBinding`リソースを含むファイルがある場合：

.`ValidatingAdmissionPolicyBinding`定義
[%collapsible]
======
[subs="+attributes",shell]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "kw-scaffold-demo"
spec:
  policyName: "force-liveness-probe"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchLabels:
        docs.kubewarden.io/vap-migration: enabled
----

======

次の手順に従って、ポリシーを{short-project-name}に移行できます：

.ポリシー移行のための`kwctl`コマンド
[%collapsible]
======

[subs="+attributes",shell]
----
$ kwctl scaffold vap \
    -p vap.yml \
    -b vap-binding.yml
----

======

コマンドは、次のような出力を生成します：

.マイグレーションからの出力
[%collapsible]
======

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: kw-scaffold-demo
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:latest
  settings:
    failurePolicy: Fail
    variables:
      - expression: |
          object.spec.template.spec.containers.filter(c, !has(c.livenessProbe)).map(c, c.name)
        name: containers_without_liveness_probe
    validations:
      - expression: |
          size(variables.containers_without_liveness_probe) == 0
        messageExpression: |
          'These containers are missing a liveness probe: ' + variables.containers_without_liveness_probe.join(' ')
        reason: Invalid
  rules:
    - apiGroups:
        - apps
      apiVersions:
        - v1
      resources:
        - deployments
      operations:
        - CREATE
        - UPDATE
  mutating: false
  namespaceSelector:
    matchLabels:
      docs.kubewarden.io/vap-migration: enabled
----
======

[NOTE]
====

このコマンドは、CELポリシーの`latest`バージョンの使用についてユーザーに警告します。

[subs="+attributes",console]
----
024-06-24T16:00:16.516062Z  WARN kwctl::scaffold:
  Using the 'latest' version of the CEL policy could lead to unexpected behavior.
  It is recommended to use a specific version to avoid breaking changes.
----

破壊的な変更を避けるために、特定のバージョンを使用することをお勧めします。

このように`--cel-policy`フラグを使用してこれを行うことができます。

[subs="+attributes",console]
----
$ kwctl scaffold vap \
    --cel-policy ghcr.io/kubewarden/policies/cel-policy:v1.0.1 \
    -p vap.yml \
    -b vap-binding.yml
----

====
