include::partial$variables.adoc[]
= Rédaction de {project-name} politiques
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Développez des politiques de contrôleur d'admission en exposant des fonctionnalités bien définies via une API spécifique en utilisant n'importe quel langage de programmation pris en charge.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["rédaction-politiques"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "rédaction de politiques"]
:sidebar_label: Rédaction de politiques
:current-version: {page-origin-branch}

Cette section présente des {project-name} politiques en utilisant des analogies de l'informatique traditionnelle.

Une {short-project-name} politique est comme un programme qui effectue une tâche.
Elle reçoit des données d'entrée, effectue des calculs avec ces données et renvoie un résultat.

Les données d'entrée sont des demandes d'admission Kubernetes.
Le résultat du calcul est une réponse de validation, qui indique à Kubernetes s'il faut accepter, rejeter ou modifier les données d'entrée, la demande d'admission.

Le composant https://github.com/kubewarden/policy-server[policy-server] de {short-project-name} effectue ces opérations.

Le serveur de politiques n'inclut aucune capacité de traitement de données.
Vous ajoutez des capacités de traitement à l'exécution avec des modules complémentaires.
Ces modules complémentaires sont les {short-project-name} politiques.

Ainsi, une {short-project-name} politique est comme un https://en.wikipedia.org/wiki/Plug-in_%28computing%29[plug-in traditionnel] du programme "policy server".

En bref :

* Les {short-project-name} politiques sont des plug-ins qui exposent un ensemble de fonctionnalités bien définies (valider un objet de demande Kubernetes, valider les paramètres de politique fournis par l'utilisateur, et d'autres fonctions) en utilisant une API bien définie.
* Le serveur de politiques est le programme "principal" qui charge les plug-ins (alias politiques) et utilise leurs fonctionnalités exposées pour accepter, rejeter ou modifier les demandes Kubernetes.

La rédaction de {short-project-name} politiques consiste à écrire la logique métier de validation puis à l'exposer via une API bien définie.

== Exigences en matière de langage de programmation

Vous fournissez des {short-project-name} politiques sous forme de binaires https://webassembly.org/[WebAssembly].

Les auteurs de politiques peuvent rédiger des politiques en utilisant n'importe quel langage de programmation qui prend en charge WebAssembly comme cible de compilation.
La liste des langages pris en charge évolue constamment, https://github.com/appcypher/awesome-wasm-langs[cette page] fournit un bon aperçu du paysage WebAssembly.

Actuellement, WebAssembly n'a pas de moyen officiel de partager des types de données complexes entre l'hôte et un invité WebAssembly.
Pour surmonter cette limitation, les {short-project-name} politiques utilisent le projet https://github.com/wapc[waPC], qui fournit un canal de communication bidirectionnel.

Ainsi, le langage de programmation de votre choix doit disposer d'un SDK invité waPC disponible.
Si ce n'est pas le cas, n'hésitez pas à nous contacter.
L'équipe du projet peut vous aider à surmonter cette limitation.
