include::partial$variables.adoc[]
= Swift
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Apprenez à utiliser le compilateur Swift avec le support de WebAssembly via SwiftWasm pour accéder aux outils de création de stratégies {project-name}.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "rédaction de stratégies", "swift"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "rédaction de stratégies", "swift"]
:sidebar_label: Swift
:sidebar_position: 50
:current-version: {page-origin-branch}

Comme indiqué sur le https://swift.org/[site officiel] :

____
Swift est un langage de programmation polyvalent qui est accessible aux débutants et puissant pour les experts.
Il est rapide, moderne, sûr et agréable à écrire.
____

Le compilateur Swift n'a pas encore de support pour WebAssembly, cependant le projet https://swiftwasm.org/[SwiftWasm] fournit un compilateur auquel un correctif a été appliqué afin d'activer cette capacité.

L'équipe de SwiftWasm travaille à fusionner ces changements dans le projet Swift.
En attendant, vous pouvez utiliser la chaîne d'outils fournie par le projet SwiftWasm pour créer des stratégies {project-name}.

[NOTE]
====

Vous n'avez pas besoin d'un système Apple pour écrire ou exécuter du code Swift. Tout peut également être fait sur une machine Linux ou sur Windows (en utilisant Docker pour Windows).
====


== État actuel

Les auteurs de stratégies peuvent utiliser les ressources suivantes :

* https://github.com/kubewarden/policy-sdk-swift[{short-project-name} Swift SDK] : il fournit un ensemble de ``struct``s et de fonctions qui simplifient la rédaction de stratégies.
* https://github.com/kubewarden/swift-policy-template[{short-project-name} projet template Swift] : utilisez ce modèle pour générer une stratégie basée sur Swift.
Le modèle est livré avec une stratégie fonctionnelle et un ensemble d'actions GitHub pour automatiser son cycle de vie.

Il n'y a pas de limitations sévères avec Swift, seulement quelques problèmes mineurs :

* Il est essentiel d'effectuer certaines optimisations post-construction avant d'utiliser la stratégie _"en production"_ :
 .. Réduisez la taille du module Wasm via `wasm-strip`
 .. Optimisez le module Wasm via `wasm-opt`

L'action GitHub fournie par le dépôt modèle s'en occupe déjà.

== Plus d'exemples

https://github.com/kubewarden/pod-runtime-class-policy/tree/swift-implementation[Cette branche de dépôt GitHub] a une {short-project-name} stratégie écrite en Swift.
