include::partial$variables.adoc[]

= Backup e restauraĂ§ĂŁo com o Operador de Backup do Rancher
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-04
:page-revdate: {revdate}
:description: Configure e gerencie backups e restauraĂ§Ăµes usando o operador rancher-backup em qualquer cluster Kubernetes.
:keywords: "{project-name}", Kubernetes, Kubewarden, Operador de Backup do Rancher, backup, restore
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: Manual do Operador, rancher-backup-operator
:current-version: {page-origin-branch}

O operador `rancher-backup` pode ser usado para fazer backup e restaurar o Rancher em qualquer cluster Kubernetes.

Desde a versĂŁo `v9.0.0`, `rancher-backup` tem suporte para {project-name}. Isso inclui:

- O Namespace padrĂŁo do Rancher `cattle-kubewarden-system` (ou `cattle-kubewarden-*`), e o Namespace padrĂŁo {short-project-name} `kubewarden`.
- Os recursos necessĂˇrios de {short-project-name} sĂŁo instalados por meio dos charts Helm.
- Os CRDs de {short-project-name}, que sĂŁo reconciliados apĂłs a restauraĂ§ĂŁo pelo controlador {short-project-name}.
- O subchart `policy-reporter` do chart `kubewarden-controller`, para seus valores padrĂŁo. Isso nĂŁo inclui a integraĂ§ĂŁo do Grafana nem outros plugins.

== Segredos do UsuĂˇrio

O processo de backup nĂŁo inclui segredos criados pelo usuĂˇrio, como aqueles usados para xref:/howtos/policy-servers/02-private-registry.adoc#_creating_the_secret[configurar servidores de polĂ­tica para registros privados], a menos que estejam corretamente rotulados. Para isso, rotule os segredos de uma das seguintes maneiras. Ou:

[source,shell]
----
kubectl label secret secret-ghcr-docker app.kubernetes.io/part-of=kubewarden
----

Ou:

[source,shell]
----
kubectl label secret secret-ghcr-docker resources.cattle.io/backup=true
----

== Instalando o Operador de Backup do Rancher

Siga o \link: \https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.html[documentaĂ§ĂŁo do Rancher Manager]. Para uma instalaĂ§ĂŁo do Minikube usando os PersistentVolumes do tipo `hostPath` nomeados `standard` que o Minikube suporta por padrĂŁo.

Ă‰ necessĂˇrio instruir o Operador de Backup a tambĂ©m fazer backup de CRs definidos pelo usuĂˇrio {short-project-name} definindo o Valor `optionalResources.kubewarden.enabled` como `true`.

A instalaĂ§ĂŁo serĂˇ a seguinte:

[source,console]
----
helm repo add rancher-charts https://charts.rancher.io
helm repo update
helm install --wait --create-namespace -n cattle-resources-system \
    rancher-backup-crd rancher-charts/rancher-backup-crd
helm install --wait -n cattle-resources-system \
    rancher-backup rancher-charts/rancher-backup \
    --set persistence.enabled=true --set persistence.storageClass=standard \
    --set optionalResources.kubewarden.enabled=true
----

== Backup

Use o `rancher-resource-set-full` para fazer backup dos segredos {short-project-name}.
Isso inclui os segredos TLS que sĂŁo criados na instalaĂ§ĂŁo do Helm.

Se vocĂŞ preferir usar `rancher-resource-basic`, lembre-se de fazer backup ou criar manualmente os segredos TLS necessĂˇrios.

Aqui estĂˇ um exemplo de como realizar um backup nĂŁo criptografado para o local padrĂŁo com o `rancher-resource-set-full`:

[source,shell]
----
kubectl apply -f - <<EOF
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: default-location-backup
spec:
  resourceSetName: rancher-resource-set-full
EOF
backup.resources.cattle.io/default-location-backup created
----

Os logs do `rancher-backup` ou o backup mostram a criaĂ§ĂŁo do arquivo de backup:

[source,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
...
INFO[2025/06/26 10:07:48] Processing backup default-location-backup
INFO[2025/06/26 10:07:48] For backup CR default-location-backup, filename: default-location-backup-32d64f39-d3c7-4331-9101-8ca493bd9d2e-2025-06-26T10-07-48Z
...
INFO[2025/06/26 10:07:49] Done with backup
----

VocĂŞ tambĂ©m pode ver seu status descrevendo o recurso:

[source,shell]
----
kubectl get backups
NAME                      LOCATION   TYPE       LATEST-BACKUP                                                                              RESOURCESET                 AGE    STATUS
default-location-backup   PV         One-time   default-location-backup-43f3ccb7-5624-4eed-9c3b-1c15d287080e-2025-06-26T15-53-27Z.tar.gz   rancher-resource-set-full   111s   Completed
----

Consulte a documentaĂ§ĂŁo do Rancher para mais link:https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.html#_backup[exemplos de backup].

== Restaurar

Para restaurar o backup nĂŁo criptografado do local padrĂŁo, pegue o nome do arquivo da coluna LATEST-BACKUP ao exibir o recurso de backup para criar um recurso de restauraĂ§ĂŁo:

[source,shell]
----
kubectl apply -f - <<EOF
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: restore-default
spec:
  backupFilename: default-location-backup-32d64f39-d3c7-4331-9101-8ca493bd9d2e-2025-06-26T10-07-48Z.tar.gz
EOF
restore.resources.cattle.io/restore-default created

kubectl get restores
NAME              BACKUP-SOURCE   BACKUP-FILE                                                                                AGE   STATUS
restore-default   PV              default-location-backup-43f3ccb7-5624-4eed-9c3b-1c15d287080e-2025-06-26T15-53-27Z.tar.gz   6s    Completed
----

Consulte a documentaĂ§ĂŁo do Rancher para mais link:https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.html#_restore[exemplos de restauraĂ§ĂŁo].


