include::partial$variables.adoc[]

= Proxy-Konfiguration
:page-languages: [en, de, es, fr, ja, pt, zh]
:description: Proxies mit {admc-name} verwenden.
:keywords: ["{admc-name}", "kubewarden", "kubernetes", "proxy", "proxies"]
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-type: ["howto"]
:doc-topic: ["operator-manual", "proxy"]

FĂĽr sowohl `kwctl` als auch `policy-server` kĂ¶nnen Sie HTTP- und HTTPS-Proxies konfigurieren sowie Domains von dieser Proxy-Konfiguration ausnehmen.

Sie kĂ¶nnen dies auf zwei Arten tun: * Indem Sie die Umgebungsvariablen `HTTP_PROXY`, `HTTPS_PROXY` und `NO_PROXY` (sowie deren Kleinbuchstaben-Entsprechungen) entweder fĂĽr `kwctl` oder fĂĽr `policy-server` setzen.
  Um ein PolicyServer CR zu konfigurieren, setzen Sie sein `spec.env`-Array. * Durch Bereitstellung einer `sources.yaml`-Datei ĂĽber das `--sources-path`-Argument.
  Eine `sources.yaml`-Datei hat Vorrang vor den Umgebungsvariablen.
  Der Zugriff auf diese Konfiguration ĂĽber das `spec`-Feld ist in PolicyServer CRs noch nicht verfĂĽgbar.

Das Setzen einer Proxy-Konfiguration beeinflusst:

* Richtlinien-Pull, -Push und -Pull-and-Run von und zur OCI-Registry.
* HostfĂ¤higkeiten aus kontextbewussten Aufrufen, wie:
** Container-Registry, wie das Abrufen eines OCI-Manifests oder Manifest-Digests.
   Anstatt direkt auf die OCI-Registry zuzugreifen, wird der Datenverkehr ĂĽber die konfigurierten Proxies geleitet.
** Sigstore-FĂ¤higkeiten, wie die ĂśberprĂĽfung einer schlĂĽssellosen Signatur.
   Anstatt auf die von Sigstore definierten Dienste zuzugreifen, wird der Datenverkehr ĂĽber die konfigurierten Proxies geleitet.

== Beispiel

Sie kĂ¶nnen die folgenden Umgebungsvariablen entweder fĂĽr `kwctl` oder fĂĽr `policy-server` (ĂĽber den PolicyServer `spec.env`) setzen:

[source,bash]
----
HTTP_PROXY="http://proxy.corp:3128"
https_proxy="http://proxy.corp:3129"
NO_PROXY="localhost,.corp"
----

Mit dieser Konfiguration: * UnverschlĂĽsselter Datenverkehr ĂĽber HTTP, wie der zu und von einer unsicheren OCI-Registry, wird ĂĽber `\http://proxy.corp:3128` geleitet.
  Dies betrifft das Abrufen von Richtlinien sowie solche Richtlinien, die kontextbewusste FĂ¤higkeiten aufrufen und OCI-Image-Manifest-Digests fĂĽr Container in diesem Repository aufweisen. * VerschlĂĽsselter Datenverkehr ĂĽber HTTPS wird ĂĽber `\https://proxy.corp:3129` geleitet.
  Zum Beispiel umfasst dies das Abrufen und Pushen von Richtlinien zu jeder sicheren OCI-Registry und die erwĂ¤hnten kontextbewussten FĂ¤higkeiten von Richtlinien. * Datenverkehr zu und von localhost oder einer Domain unter `.corp` ist von den vorherigen Konfigurationen ausgenommen.


== Die `sources.yaml`-Datei

FĂĽr weitere Details ĂĽberprĂĽfen Sie die xref:/reference/sources_yaml.adoc[`sources.yaml`]-Referenz.