include::partial$variables.adoc[]
= {short-project-name}のためにOPAポリシーを構築して実行します。
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Regoポリシーパッケージを構築し、それをWASMターゲットにコンパイルし、kwctlと統合することで、プロジェクトのためのカスタムOPAポリシーを構築します。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "build-and-run"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "build and run", "open policy agent", "opa", "rego"]
:current-version: {page-origin-branch}

前のセクションでは、Regoポリシーを作成しました。
構造は次のようになります：

[subs="+attributes",console]
----
.
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
└── request.rego

1 directory, 4 files
----

== ビルド

構築するには：

[subs="+attributes",console]
----
$ opa build -t wasm -e policy/main policy.rego request.rego
----

これにより、次の内容でregoポリシーが構築されます：

* `target`: `wasm`.
`wasm`ターゲット用のポリシーを構築したいです。
* `entrypoint`: `policy/main`.
エントリーポイントは、`policy`パッケージ内の`main`ルールです。
* `policy.rego`:
`policy.rego`ファイルを構築して含めます。
* `request.rego`:
`request.rego`ファイルを構築して含めます。

ビルドが完了すると、`opa build`が`bundle.tar.gz`ファイルを生成します。
それを抽出できます：

[subs="+attributes",console]
----
$ tar -xf bundle.tar.gz /policy.wasm
----

現在、ツリーは次のようになります：

[subs="+attributes",console]
----
.
├── bundle.tar.gz
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
├── policy.wasm
└── request.rego

1 directory, 6 file
----

あなたの`policy.wasm`ファイルがあります：

[subs="+attributes",console]
----
$ file policy.wasm
policy.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
----

今、それを実行します。

== 実行

ポリシーを実行するには`kwctl`を使用します：

[subs="+attributes",console]
----
$ kwctl run -e opa --request-path data/other-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": true
}
----

このリクエストはポリシーによって受け入れられます。これは`other`ネームスペースを指すリクエストだからです。

* `execution-mode`: `opa`.
RegoポリシーはOpen Policy AgentまたはGatekeeperをターゲットにできます。
`kwctl`にどのようなポリシーを実行しているかを伝えなければなりません。
* `request-path`:
`kwctl`が評価のためにポリシーを送る先として記録されたリクエストの場所。

`default`ネームスペース内にポッドを作成するリクエストを評価してみてください：

[subs="+attributes",console]
----
$ kwctl run -e opa --request-path data/default-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "it is forbidden to use the default namespace"
  }
}
----

ポリシーはリクエストを拒否し、その理由をAPIサーバーを通じてユーザーまたはAPI消費者に返します。
