include::partial$variables.adoc[]
= Distribuindo uma política do Gatekeeper com {project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Distribua políticas do Gatekeeper entre clusters Kubernetes anotando arquivos de política com metadados e implantando-os via ClusterAdmissionPolicy.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "gatekeeper", "rego"]
:current-version: {page-origin-branch}

As políticas precisam ser anotadas para que possam ser enviadas e, eventualmente, executadas pelo {project-name} `policy-server` em um cluster Kubernetes.

Anotar e distribuir uma política do Gatekeeper é semelhante a distribuir uma do Open Policy Agent.

== Anotando a política

Você vai escrever um arquivo `metadata.yaml` no seu diretório de políticas com o conteúdo:

[subs="+attributes",yaml]
----
rules:
- apiGroups: [""]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["CREATE"]
mutating: false
contextAware: false
executionMode: gatekeeper
annotations:
  io.kubewarden.policy.title: no-default-namespace
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: This policy will reject any resource created inside the default namespace
  io.kubewarden.policy.author: The {short-project-name} Authors
  io.kubewarden.policy.url: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.source: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
      This policy is just an example.

      You can write interesting descriptions about the policy here.
----

Você pode ver que tudo é igual aos metadados da versão do Open Policy Agent, exceto pela parte `executionMode: gatekeeper`.

Vá em frente e anote a política:

[subs="+attributes",console]
----
$ kwctl annotate policy.wasm --metadata-path metadata.yaml --output-path annotated-policy.wasm
----

== Enviando a política

Envie sua política para um registro OCI:

[subs="+attributes",console]
----
$ kwctl push annotated-policy.wasm registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
Policy successfully pushed
----

== Implantando no Kubernetes

Você precisa puxar sua política para o seu armazenamento local `kwctl` primeiro:

[subs="+attributes",console]
----
$ kwctl pull registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
pulling policy...
----

Agora você pode criar um recurso scaffold `ClusterAdmissionPolicy`:

[subs="+attributes",console]
----
$ kwctl scaffold manifest registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1 --type ClusterAdmissionPolicy
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Agora use este recurso `ClusterAdmissionPolicy` para implantar sua política em um cluster Kubernetes.
