include::partial$variables.adoc[]
= Capacidades de red
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprende sobre las capacidades de red y cómo utilizar las funciones del host para búsquedas DNS, así como los protocolos de comunicación.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "network-capabilities"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "especificación de directivas", "capacidades de red"]
:sidebar_label: Capacidades de red
:current-version: {page-origin-branch}

{project-name} Las políticas no pueden realizar solicitudes de red desde dentro del contexto de ejecución de WebAssembly.

Las operaciones de red se pueden realizar aprovechando una serie de capacidades expuestas por el host.

== Búsqueda de host DNS

Esta función realiza una búsqueda DNS comenzando desde el FQDN dado por la directiva.

=== Almacenamiento en el caché.

Los resultados de la búsqueda se almacenan en caché durante 1 minuto.

=== Protocolo de comunicación

Esta es la descripción del protocolo waPC utilizado para exponer esta capacidad:

==== Función waPC - `v1/dns_lookup_host` entrada

[,hcl]
----
# hostname - JSON encoded string
string
----

==== Función waPC - `v1/dns_lookup_host` salida

[,hcl]
----

{
  # list of IPs
  "ips": [string]
}
----

Todas las direcciones IP asociadas con el FQDN dado se devolverán como cadenas en la respuesta.
Tanto las entradas IPv4 como IPv6 se devuelven como parte de la misma respuesta.

Por ejemplo, al solicitar el resumen del manifiesto de la `busybox:latest` imagen, las cargas útiles serían:

* Carga útil de entrada: `"google.com"`
* Carga útil de salida: `{ "ips": ["127.0.0.1"]}`
