include::partial$variables.adoc[]
= Konfigurieren von Richtlinien
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Richtlinien konfigurieren, indem spezifische Namespaces ausgewĂ¤hlt oder benutzerdefinierte Ablehnungsnachrichten festgelegt werden, und Ergebnisse mit AdmissionPolicyGroup negiert werden.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "policies"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "policies", "ClusterAdmissionPolicies", "AdmissionPolicies", "configuration", "namespaces"]
:sidebar_label: Konfigurieren von Richtlinien
:sidebar_position: 90
:current-version: {page-origin-branch}

== Ăśberspringen von Namespaces fĂĽr eine spezifische Richtlinie

StandardmĂ¤Ăźig gelten Richtlinien fĂĽr alle Namespaces, fĂĽr die der `PolicyServer` konfiguriert ist.
Wenn Sie mĂ¶chten, dass eine Richtlinie nur spezifische Namespaces anvisiert, kĂ¶nnen Sie mehrere `AdmissionPolicies` in jedem Namespace bereitstellen.

Eine weitere MĂ¶glichkeit besteht darin, `ClusterAdmissionPolicies` zu konfigurieren, indem deren `spec.namespaceSelector` festgelegt wird (siehe xref:reference/CRDs.adoc#clusteradmissionpolicy[CRD-Dokumentation]). Die `spec.namespaceSelector` entscheidet, ob die Richtlinie auf ein Objekt angewendet wird, basierend darauf, ob der Namespace fĂĽr dieses Objekt mit dem Selektor ĂĽbereinstimmt.

Hier ist eine Richtlinie, die nur die `kube-system` und `my-namespace` Namespaces anvisiert:

[subs="+attributes",yaml]
----
---
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-privileged-namespaces
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v1.0.3
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["namespaces"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: In
        values: [kube-system, my-namespace]
  settings:
    modes:
      enforce: "privileged"
----

Hier ist eine Richtlinie, die alle Namespaces auĂźer den `kube-system` und `my-namespace` anvisiert:

[subs="+attributes",yaml]
----
---
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-default-mode
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v1.0.3
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["namespaces"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: NotIn
        values: [kube-system, my-namespace]
  settings:
    modes:
      enforce: "restricted"
----

== Benutzerdefinierte Ablehnungsnachricht

Wenn eine Richtlinie eine Ressource ablehnt, ist die dem Benutzer angezeigte Nachricht die, die vom Autor der Richtlinie verfasst wurde. Manchmal mĂ¶chten Clusterbetreiber mĂ¶glicherweise eine benutzerdefinierte Ablehnungsnachricht festlegen. Zum Beispiel kann dies verwendet werden, um auf ein internes Wiki zu verweisen oder um einen spezifischeren Fehlercode bereitzustellen.

Das `message` Feld in den `ClusterAdmissionPolicy` und `AdmissionPolicy` Typen kann verwendet werden, um dies zu erreichen.

[NOTE]
====
`ClusterAdmissionPolicyGroup` und `AdmissionPolicyGroup` haben bereits ein `message` Feld, das sich auf die gleiche Weise verhĂ¤lt.
====

Das `message` Feld ermĂ¶glicht es Clusterbetreibern, eine benutzerdefinierte Ablehnungsnachricht zu definieren, die die von der Richtlinie zurĂĽckgegebene ĂĽberschreibt. Bei Verwendung dieser Konfiguration kann die ursprĂĽngliche Ablehnungsnachricht im `causes`-Feld der Antwort gefunden werden.

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: pod-privileged-with-message
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:1.0.2
  policyServer: default
  mode: protect
  message: "Nops! You cannot do that"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Sie kĂ¶nnen die vollstĂ¤ndigen Details einer abgelehnten Zulassungsanfrage erhalten, indem Sie das Verbosity-Level von kubectl erhĂ¶hen:

[subs="verbatim,attributes"]
----
$ kubectl -v4 run pod-privileged2 --image=registry.k8s.io/pause --privileged
I0612 16:32:43.647601   48424 cert_rotation.go:137] Starting client certificate rotation controller
I0612 16:32:43.662550   48424 helpers.go:246] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "admission webhook \"clusterwide-pod-privileged-with-message.kubewarden.admission\" denied the request: Nops! You cannot do that",
  "details": {
    "causes": [
      {
        "message": "Privileged container is not allowed"
      }
    ]
  },
  "code": 400
}]
----

== Ein Ergebnis einer Richtlinie zu negieren, indem man es in eine PolicyGroup kapselt.

Manchmal implementiert eine Richtlinie nicht die umgekehrte Logik dessen, was Sie benĂ¶tigen.

Zum Beispiel mĂ¶chten Sie die link:https://artifacthub.io/packages/kubewarden/priority-class-policy/priority-class-policy[`priority-class` Richtlinie] verwenden, um eine Reihe von PrioritĂ¤tsklassen abzulehnen. Aber zum Zeitpunkt des Schreibens unterstĂĽtzt die `priority-class`-Richtlinie nur Erlauben-Listen, nicht Ablehnen-Listen.

Ein hĂ¤ufiges Muster ist es, Ihre Richtlinie in eine `AdmissionPolicyGroup` oder `ClusterAdmissionPolicyGroup` einzuwickeln und das Ergebnis der Richtlinie in ihrer `spec.expression` zu negieren.

Zum Beispiel nehmen wir an, wir mĂ¶chten, dass die Benutzer alle PrioritĂ¤tsklassen verwenden, die innerhalb des Clusters definiert sind, mit Ausnahme einer der folgenden: `low-priority`, `med-priority` und `high-priority`.

Derzeit erlauben die Richtlinieneinstellungen nur, die Liste der erlaubten PrioritĂ¤tsklassen auszudrĂĽcken. Die folgende Gruppenrichtlinie ĂĽberwindet diese EinschrĂ¤nkung.

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: AdmissionPolicyGroup
metadata:
  name: priority-class-denylist
  namespace: your-namespace # or use a CLusterAdmissionPolicyGroup and set spec.namespaceSelector
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["replicationcontrollers"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["batch"]
      apiVersions: ["v1"]
      resources: ["jobs", "cronjobs"]
      operations: ["CREATE", "UPDATE"]
  policies:
    is_a_denied_priority_class:
      module: ghcr.io/kubewarden/policies/priority-class-policy:v1.0.4
      settings:
        allowed_priority_classes:
          - low-priority
          - med-priority
          - high-priority
  expression: "!is_a_denied_priority_class()" # negated result
  message: "the Pod is using a priorityClass that is not allowed"
----