include::partial$variables.adoc[]
= Wie man Richtliniengruppen verwendet
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Implementieren Sie Richtliniengruppen mit spezifischen Regeln, die nicht konforme Pods basierend auf Bildsignaturen und anderen Kriterien ablehnen.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["Erklärungen", "Richtliniengruppe"]
:doc-type: ["howto"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "Richtliniengruppen", "clusteradmissionpolicygroup", "admissionpolicygroup"]
:sidebar_label: Richtliniengruppen
:sidebar_position: 36
:current-version: {page-origin-branch}

[TIP]
====
Bevor Sie mit Richtliniengruppen arbeiten, konsultieren Sie die
xref:explanations/policy-groups.adoc[Erklärung].
====


Verwenden Sie das Beispiel aus der xref:../explanations/policy-groups.adoc[Erklärung der Richtliniengruppen],
um diese Befehle zu implementieren.

[,shell]
----
kubectl apply -f group-policy-demo.yaml
----

.Eine `ClusterAdmissionPolicyGroup`, die Pods ablehnt, die Bilder mit dem `latest` Tag verwenden, es sei denn, die Bilder sind von zwei vertrauenswürdigen Parteien signiert: Alice und Bob.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  policies:
    signed_by_alice:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
                yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
                -----END PUBLIC KEY-----
    signed_by_bob:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X
                urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==
                -----END PUBLIC KEY-----
    reject_latest:
      module: registry://ghcr.io/kubewarden/policies/trusted-repos:v0.2.0
      settings:
        tags:
          reject:
            - latest
  expression: "reject_latest() || (signed_by_alice() && signed_by_bob())"
  message: "the image is using the latest tag or is not signed by Alice and Bob"
----
======

Sobald die Richtlinie aktiv ist, wird die Erstellung eines nicht konformen Pods abgelehnt.
Um weitere Informationen über die Bewertung der Richtlinien, die Teil der
Gruppe sind, zu erhalten, erhöhen Sie das Detailniveau von `kubectl`:

[,console]
----
kubectl -v4 apply -f signed-pod.yml
I0919 18:29:40.251332    4330 helpers.go:246] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"signed-pod.yml\": admission webhook \"clusterwide-demo.kubewarden.admission\" denied the request: the image is using the latest tag or is not signed by Alice and Bob",
  "details": {
    "causes": [
      {
        "message": "Resource signed is not accepted: verification of image testing.registry.svc.lan/busybox:latest failed: Host error: Callback evaluation failure: Image verification failed: missing signatures\nThe following constraints were not satisfied:\nkind: pubKey\nowner: null\nkey: |\n  -----BEGIN PUBLIC KEY-----\n  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X\n  urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==\n  -----END PUBLIC KEY-----\nannotations: null\n",
        "field": "spec.policies.signed_by_bob"
      },
      {
        "message": "not allowed, reported errors: tags not allowed: latest",
        "field": "spec.policies.reject_latest"
      }
    ]
  },
  "code": 400
}]
Error from server: error when creating "signed-pod.yml": admission webhook "clusterwide-demo.kubewarden.admission" denied the request: the image is using the latest tag or is not signed by Alice and Bob
----

[NOTE]
====
Die Bewertungsausgabe, die von den Richtlinien, die Teil der Gruppe sind, erzeugt wird, ist nur sichtbar, wenn das Detailniveau von `kubectl` erhöht wird.

Ein Detailniveau von `4` reicht aus, um die Bewertungsausgabe der Richtlinien zu sehen.
====

