include::partial$variables.adoc[]
= Erstellen einer neuen Validierungsrichtlinie
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erforschen Sie die Erstellung einer neuen Validierungsrichtlinie, die Pods mit auf der Sperrliste stehenden Labels ablehnt, während sie Labels mit vom Benutzer bereitgestellten regulären Ausdrücken validiert, um die Sicherheit zu gewährleisten.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "richtlinien-schreiben", "go", "eine neue Validierungsrichtlinie erstellen"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "Richtlinien in Go schreiben", "neue Validierungsrichtlinie"]
:current-version: {page-origin-branch}

Dieses Tutorial behandelt die Erstellung einer Richtlinie, die die Labels von Pod-Objekten validiert.

Die Richtlinie soll alle Pods ablehnen, die eines oder mehrere Labels auf der Sperrliste verwenden.
Die Richtlinie validiert auch bestimmte Labels mithilfe eines vom Benutzer bereitgestellten regulären Ausdrucks.

Zusammenfassend sollten die Richtlinieinstellungen wie folgt aussehen:

[subs="+attributes",yaml]
----
# List of labels that cannot be used
denied_labels:
- foo
- bar

# Labels that are validated with user-defined regular expressions
constrained_labels:
  priority: "[123]"
  cost-center: "^cc-\d+"
----

Die Richtlinie lehnt die Erstellung dieses Pods ab:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    foo: hello world
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

Sie lehnt auch die Erstellung dieses Pods ab:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    cost-center: cc-marketing
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

Sie können die Einstellungen der Richtlinie verwenden, um die Verwendung einer Labelspezifikation zu erzwingen, unabhängig vom Inhalt:

[subs="+attributes",yaml]
----
constrained_labels:
  mandatory-label: ".*" # <- this label must be present, we don't care about its value
----

== Erstellen des Grundgerüsts für ein neues Richtlinienprojekt

Sie können ein neues Richtlinienprojekt mit dem https://github.com/kubewarden/go-policy-template[Vorlagen-Repository] erstellen.
Wählen Sie die grüne Schaltfläche "Diese Vorlage verwenden" oben auf der Seite und folgen Sie dem Assistenten von GitHub.

Klonen Sie das Repository lokal und setzen Sie die `module`-Direktive in der `go.mod`-Datei so, dass sie wie folgt aussieht:

[,go]
----
module <path to your repository>
----

[NOTE]
====
Eine echte Richtlinie würde einen Repository-Pfad verwenden, wie `github.com/kubewarden/go-policy-template`.
====


== Tester

Vorausgesetzt, die erforderlichen Werkzeuge sind vorhanden, verwendet ein `make test`-Befehl Docker, um ein TinyGo-Compiler-Image herunterzuladen, um die Richtlinienvorlage zu erstellen und zu testen.

Der Standard-`make`-Befehl erstellt das `policy.wasm`-Ziel. Dann führt `make test` die definierten Go-Tests aus.
Der Befehl `make e2e-tests` führt Tests mit https://github.com/bats-core/bats-core[bats] innerhalb eines {short-project-name}-Clusters aus.
Nach dem Klonen der `go-policy-template` überprüfen diese Befehle, ob Sie über die erforderlichen Werkzeuge für das Tutorial verfügen.

.Ausgabe der `make`-Befehle
[%collapsible]
======

[subs="+attributes",console]
----
make test
docker run \
        --rm \
        -e GOFLAGS="-buildvcs=false" \
        -v /home/jhk/projects/suse/tmp/go-kw-demo:/src \
        -w /src tinygo/tinygo:0.30.0 \
        tinygo build -o policy.wasm -target=wasi -no-debug .
Unable to find image 'tinygo/tinygo:0.30.0' locally
0.30.0: Pulling from tinygo/tinygo
9aaefb8797c4: Pull complete
24ab7ca26e01: Pull complete
ca4ea8be6361: Pull complete
50380d0859d2: Pull complete
4f4fb700ef54: Pull complete
ea0ddd497f04: Pull complete
01ba28116afb: Pull complete
Digest: sha256:5cbf5e50aec3a00fcff8bb4ae070a07eea8198187a97b21dff6d873d2274ce7a
Status: Downloaded newer image for tinygo/tinygo:0.30.0
go test -v
=== RUN   TestParsingSettingsWithNoValueProvided
--- PASS: TestParsingSettingsWithNoValueProvided (0.00s)
=== RUN   TestIsNameDenied
--- PASS: TestIsNameDenied (0.00s)
=== RUN   TestEmptySettingsLeadsToApproval
NATIVE: |{"level":"debug","message":"validating pod object","name":"test-pod","namespace":"default"}
|
--- PASS: TestEmptySettingsLeadsToApproval (0.00s)
=== RUN   TestApproval
NATIVE: |{"level":"debug","message":"validating pod object","name":"test-pod","namespace":"default"}
|
--- PASS: TestApproval (0.00s)
=== RUN   TestApproveFixture
NATIVE: |{"level":"debug","message":"validating pod object","name":"test-pod","namespace":"default"}
|
--- PASS: TestApproveFixture (0.00s)
=== RUN   TestRejectionBecauseNameIsDenied
NATIVE: |{"level":"debug","message":"validating pod object","name":"test-pod","namespace":"default"}
|
NATIVE: |{"level":"info","message":"rejecting pod object","name":"test-pod","denied_names":"foo,test-pod"}
|
--- PASS: TestRejectionBecauseNameIsDenied (0.00s)
PASS
ok      github.com/kubewarden/go-policy-template        0.004s
----

und

[subs="+attributes",console]
----
make e2e-tests
bats e2e.bats
e2e.bats
 ✓ reject because name is on deny list
 ✓ accept because name is not on the deny list
 ✓ accept because the deny list is empty

3 tests, 0 failures
----

======
