include::partial$variables.adoc[]
= Rédaction de stratégies brutes
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Apprenez à rédiger des stratégies brutes qui évaluent des documents JSON arbitraires et appliquent des règles de contrôle d'accès dans votre système.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "raw-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "stratégies brutes", "open policy agent", "opa", "rego"]
:sidebar_label: Stratégies brutes
:current-version: {page-origin-branch}

Les stratégies brutes sont des stratégies qui peuvent évaluer des documents JSON arbitraires.
Pour plus d'informations sur les stratégies brutes, veuillez vous référer à la page xref:howtos/raw-policies.adoc[stratégies brutes].

== Par exemple :

Les exemples suivants devraient vous sembler familiers si vous avez complété la page xref:tutorials/writing-policies/rego/open-policy-agent/02-create-policy.adoc[validation] de ce didacticiel.

[NOTE]
====
N'oubliez pas de marquer la stratégie comme `raw`, en utilisant le champ `policyType` dans la configuration `metadata.yml`.
Veuillez vous référer à la spécification xref:tutorials/writing-policies//metadata.adoc[metadata] pour plus d'informations.
====


=== Validation

Vous allez rédiger une stratégie qui accepte une demande dans le format suivant :

[subs="+attributes",json]
----
{
  "request": {
    "user": "alice",
    "action": "read",
    "resource": "products"
  }
}
----

Elle valide que seul l'utilisateur `admin` peut supprimer des ressources.

Commencez par créer une stratégie en utilisant le modèle de stratégie https://github.com/kubewarden/opa-policy-template[OPA] .

Tout d'abord, vous devez modifier le fichier `policy.rego` pour qu'il ressemble à ceci :

[,rego]
----
package validation

deny[msg] {
    input.request.action == "delete"
    input.request.user != "admin"
    msg := sprintf("user %v is not allowed to delete resources", [input.request.user])
}
----

Le module `utility/policy.rego` nécessite une modification pour supprimer le code spécifique à Kubernetes :

[,rego]
----
package policy

import data.validation

main = {
    "response": response,
}

# OPA policy responses need the uid field to be set.
# If the request doesn't contain a uid, set it to an empty string.
default uid = ""

uid = input.request.uid

response = {
    "uid": uid,
    "allowed": false,
    "status": {"message": reason},
} {
    reason = concat(", ", validation.deny)
    reason != ""
} else = {
    "uid": uid,
    "allowed": true,
} {
    true
}
----
