include::partial$variables.adoc[]
= Creación de una nueva directiva
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Crea una directiva que evalúe todos los recursos con espacio de nombres y prohíba su creación en el espacio de nombres predeterminado para el aprendizaje práctico.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "create-policy"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "creating a policy", "open policy agent", "opa", "rego"]
:sidebar_label: Creación de una nueva directiva
:current-version: {page-origin-branch}

Puedes crear una directiva de ejemplo que ayude a entender los conceptos importantes.

[NOTE]
====
Hay una https://github.com/kubewarden/opa-policy-template[kubewarden/opa-policy-template] que puedes usar para portar una directiva existente.
====


== Requisitos

Escribirás, compilarás y ejecutarás una directiva en esta sección.
Necesitas estas herramientas para completar este tutorial:

* https://github.com/open-policy-agent/opa/releases[`opa`]: usarás la CLI de `opa` para construir tu directiva como un objetivo `wasm`.
* https://github.com/kubewarden/kwctl/releases[`kwctl`]: usarás `kwctl` para ejecutar tu directiva construida.

== La directiva

Vas a crear una directiva que evalúe cualquier tipo de recurso con espacio de nombres.
Su objetivo es prohibir la creación de cualquier recurso si el espacio de nombres objetivo es `default`. De lo contrario, la solicitud es aceptada.
Comienza creando una carpeta llamada `opa-policy`.

Crea una carpeta llamada `data` en la carpeta `opa-policy`.
Esta carpeta tiene los objetos `AdmissionReview` grabados del servidor de la API de Kubernetes.
Se han reducido por simplicidad para el ejercicio, así puedes centrarte en los aspectos que importan.

Crea un archivo `default-ns.json` con el siguiente contenido dentro del directorio `data`:

[subs="+attributes",json]
----
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
    "operation": "CREATE",
    "object": {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata": {
        "name": "nginx",
        "namespace": "default",
        "uid": "04dc7a5e-e1f1-4e34-8d65-2c9337a43e64"
      }
    }
  }
}
----

Esto simula la creación de una operación de pod dentro del espacio de nombres `default`.
Ahora, crea otro ejemplo de solicitud en `other-ns.json` dentro del directorio `data`:

[subs="+attributes",json]
----
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
    "operation": "CREATE",
    "object": {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata": {
        "name": "nginx",
        "namespace": "other",
        "uid": "04dc7a5e-e1f1-4e34-8d65-2c9337a43e64"
      }
    }
  }
}
----

Puedes ver que esto simula otra solicitud de creación de pod, esta vez bajo un espacio de nombres llamado `other`.

Vuelve a tu carpeta `opa-policy` y comienza a escribir tu directiva Rego.

En esta carpeta, crea un archivo llamado `request.rego` en la carpeta `opa-policy`.
El nombre puede ser cualquier cosa, pero lo usarás para este ejercicio.
Este es un archivo Rego que contiene código de utilidad relacionado con la solicitud/respuesta en sí.
En particular, te permite simplificar tu código de directiva y reutilizar esta parte común en diferentes directivas.

El contenido es:

[,rego]
----
package policy

import data.kubernetes.admission

main = {
    "apiVersion": "admission.k8s.io/v1",
    "kind": "AdmissionReview",
    "response": response,
}

response = {
    "uid": input.request.uid,
    "allowed": false,
    "status": {"message": reason},
} {
    reason = concat(", ", admission.deny)
    reason != ""
} else = {
    "uid": input.request.uid,
    "allowed": true,
} {
    true
}
----

No tienes necesidad, en este momento, de entrar en detalle en el código Rego.
Puedes aprender sobre ello en su https://www.openpolicyagent.org/docs/latest/policy-language/[sitio web].

En este caso, devuelve ya sea `allowed: true` o `allowed: false`.
Esto depende de si el otro paquete, `data.kubernetes.admission`, tiene alguna declaración `deny` que evalúe a `true`.

Si alguna `data.kubernetes.admission.deny` evalúa a `true`, la `response` aquí evalúa al primer bloque.
De lo contrario, evalúa al segundo bloque, lo que lleva a la aceptación.
Debido a que ningún bloque `deny` evaluó a `true`, esto significa que la directiva está aceptando la solicitud.

Esto es solo el shell de la directiva, la utilidad.
Ahora, creas otro archivo, llamado, por ejemplo, `policy.rego` dentro de nuestra carpeta `opa-policy` con estos contenidos:

[,rego]
----
package kubernetes.admission

deny[msg] {
    input.request.object.metadata.namespace == "default"
    msg := "it is forbidden to use the default namespace"
}
----

Esta es la parte importante de tu directiva.
La declaración `deny` evalúa a `true` si todas las declaraciones dentro de ella evalúan a `true`.
En este caso, solo hay una declaración, comprobando si el espacio de nombres es `default`.

Por diseño de Open Policy Agent,
`input` tiene el objeto consultable con el objeto `AdmissionReview`,
así que podemos inspeccionarlo de manera conveniente.

Si todo ha ido bien, tu árbol debería verse como el siguiente:

[subs="+attributes",console]
----
.
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
└── request.rego

1 directory, 4 files
----
