include::partial$variables.adoc[]
= Comment utiliser les groupes de stratégies
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Implémentez des groupes de stratégies avec des règles spécifiques qui rejettent les Pods non conformes en fonction des signatures d'image et d'autres critères.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["explications", "groupe de stratégies"]
:doc-type: ["howto"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "groupes de stratégies", "groupe de stratégies d'admission de cluster", "groupe de stratégies d'admission"]
:sidebar_label: Groupes de stratégies
:sidebar_position: 36
:current-version: {page-origin-branch}

[TIP]
====
Avant de travailler avec les groupes de stratégies, consultez l'xref:explanations/policy-groups.adoc[explication].
====


En utilisant l'exemple de la xref:../explanations/policy-groups.adoc[explication des groupes de stratégies],
utilisez ces commandes pour l'implémenter.

[,shell]
----
kubectl apply -f group-policy-demo.yaml
----

.Un `ClusterAdmissionPolicyGroup` qui rejette les Pods utilisant des images avec le tag `latest`, à moins que les images ne soient signées par deux parties de confiance : Alice et Bob.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  policies:
    signed_by_alice:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
                yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
                -----END PUBLIC KEY-----
    signed_by_bob:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X
                urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==
                -----END PUBLIC KEY-----
    reject_latest:
      module: registry://ghcr.io/kubewarden/policies/trusted-repos:v0.2.0
      settings:
        tags:
          reject:
            - latest
  expression: "reject_latest() || (signed_by_alice() && signed_by_bob())"
  message: "the image is using the latest tag or is not signed by Alice and Bob"
----
======

Une fois la stratégie active, la création d'un Pod non conforme sera rejetée.
Pour obtenir plus d'informations sur l'évaluation des stratégies qui font partie du
groupe, augmentez le niveau de verbosité de `kubectl` :

[,console]
----
kubectl -v4 apply -f signed-pod.yml
I0919 18:29:40.251332    4330 helpers.go:246] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"signed-pod.yml\": admission webhook \"clusterwide-demo.kubewarden.admission\" denied the request: the image is using the latest tag or is not signed by Alice and Bob",
  "details": {
    "causes": [
      {
        "message": "Resource signed is not accepted: verification of image testing.registry.svc.lan/busybox:latest failed: Host error: Callback evaluation failure: Image verification failed: missing signatures\nThe following constraints were not satisfied:\nkind: pubKey\nowner: null\nkey: |\n  -----BEGIN PUBLIC KEY-----\n  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X\n  urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==\n  -----END PUBLIC KEY-----\nannotations: null\n",
        "field": "spec.policies.signed_by_bob"
      },
      {
        "message": "not allowed, reported errors: tags not allowed: latest",
        "field": "spec.policies.reject_latest"
      }
    ]
  },
  "code": 400
}]
Error from server: error when creating "signed-pod.yml": admission webhook "clusterwide-demo.kubewarden.admission" denied the request: the image is using the latest tag or is not signed by Alice and Bob
----

[NOTE]
====
La sortie d'évaluation produite par les stratégies qui font partie du groupe n'est visible
qu'en augmentant le niveau de verbosité de `kubectl`.

Un niveau de verbosité de `4` suffit pour voir la sortie d'évaluation des stratégies.
====

