include::partial$variables.adoc[]
= IntroducciĂ³n a CEL
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-06-18
:page-revdate: {revdate}
:description: Aprende sobre CEL (Lenguaje de ExpresiĂ³n de CĂ¡lculo) como un lenguaje de expresiĂ³n rĂ¡pido, portĂ¡til y seguro diseĂ±ado para reglas de validaciĂ³n de Kubernetes y extensiones a la API de Kubernetes.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "introduction"]
:current-version: {page-origin-branch}

El https://cel.dev[Lenguaje de ExpresiĂ³n ComĂºn (CEL)] es un lenguaje de expresiĂ³n de propĂ³sito general diseĂ±ado para ser rĂ¡pido, portĂ¡til y seguro de ejecutar. CEL como lenguaje es seguro en memoria, libre de efectos secundarios, con terminaciĂ³n garantizada (los programas no pueden ejecutarse indefinidamente) y fuertemente y dinĂ¡micamente tipado. Puedes aprender mĂ¡s sobre CEL en https://cel.dev[cel.dev] y practicarlo en el https://playcel.undistro.io[playground de CEL].

== CEL en Kubernetes

CEL fue elegido como el lenguaje para las reglas de validaciĂ³n de Kubernetes ya que las expresiones CEL pueden ser fĂ¡cilmente integradas en los esquemas de CRD, y compiladas y verificadas por tipo "por adelantado" (cuando se crean y actualizan los CRD). Por estas razones y sus caracterĂ­sticas generales, es un candidato perfecto para extender la API de Kubernetes.

Marcado como estable con Kubernetes 1.30, se puede usar CEL en https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy[ValidatingAdmissionPolicies] y otras reglas de validaciĂ³n. Para mĂ¡s informaciĂ³n, consulta la documentaciĂ³n de Kubernetes https://kubernetes.io/docs/reference/using-api/cel[aquĂ­].

=== Bibliotecas de funciones de Kubernetes

Las reglas de validaciĂ³n de Kubernetes CEL tienen acceso a varias bibliotecas de funciones:

* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#list-of-standard-definitions[Funciones estĂ¡ndar de CEL]
* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#macros[Macros estĂ¡ndar de CEL]
* https://pkg.go.dev/github.com/google/cel-go/ext#Strings[Biblioteca de funciones de cadena extendida de CEL]
* https://kubernetes.io/docs/reference/using-api/cel/#kubernetes-cel-libraries[Bibliotecas de extensiĂ³n de Kubernetes CEL], con funciones suplementarias para listas, regex, URLs, autorizadores, cantidades, tipos opcionales, comparaciones numĂ©ricas, etc.

== CEL en {admc-name}: `cel-policy`

{admc-short-name} proporciona https://github.com/kubewarden/cel-policy[cel-policy].
Esta es una polĂ­tica que construye y empaqueta el intĂ©rprete https://pkg.go.dev/github.com/google/cel-go[cel-go] de sentido ascendente, y tambiĂ©n las diferentes bibliotecas listadas arriba y disponibles para CEL en Kubernetes desde `apiextensions-apiserver`.

AdemĂ¡s, `cel-policy` incluye una biblioteca de extensiĂ³n de CEL *{admc-short-name} que expone las capacidades del host de {admc-short-name} como CEL nativas*:

* VerificaciĂ³n de Sigstore
* InteracciĂ³n OCI
* Funciones criptogrĂ¡ficas
* Operaciones de red
* Acceso a recursos de Kubernetes

Esto significa que `cel-policy` es un superconjunto de Kubernetes CEL, y es compatible hacia atrĂ¡s. Se puede reutilizar CEL escrito para Kubernetes estĂ¡ndar, y/o hacer uso de las caracterĂ­sticas aĂ±adidas por {admc-short-name}.

El `cel-policy` se envĂ­a compilado y se comporta como un intĂ©rprete de CEL. Los usuarios de la polĂ­tica pasan las expresiones CEL deseadas en el `spec.settings` de la (Cluster)AdmissionPolicy, y gracias a las caracterĂ­sticas de CEL, la expresiĂ³n se compila y se verifica su tipo para correcciĂ³n al crear o actualizar la (Cluster)AdmissionPolicy. Esto significa que no hay necesidad de compilaciones personalizadas del `cel-policy`.

=== Beneficios del `cel-policy` de {admc-short-name} en comparaciĂ³n con ValidatingAdmissionPolicies

El {admc-short-name} `cel-policy`:

* Su cĂ³digoÂ CEL es compatible hacia atrĂ¡s con ValidatingAdmissionPolicies.
* A diferencia de ValidatingAdmissionPolicies, no necesita un enlaceÂ como ValidatingAdmissionPolicyBinding, ya que esto estĂ¡ incluido en las definiciones de (Cluster)Admissionpolicies de {admc-short-name}.
* Se puede desplegar en clĂºsteres que carecen de soporte para ValidatingAdmissionPolicies.
* Es consciente del contexto y hace uso de los permisos granulares de {admc-short-name} para xref:../../../reference/spec/05-context-aware-policies.adoc[conciencia del contexto].
* Se despliega como (Cluster)AdmissionPolicy.
* Se beneficia del rastreo y la telemetrĂ­a de {admc-short-name} sobre polĂ­ticas.
* Se tendrĂ¡ en cuenta por el EscĂ¡ner de AuditorĂ­a.
* Se puede desarrollar y probar fuera del clĂºster gracias a kwctl.
