include::partial$variables.adoc[]
= Distribuindo uma polûÙtica OPA com {project-name}
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Anote sua polûÙtica Rego com metadados relevantes e, em seguida, envie-a para um registro OCI para se preparar para a implantaûÏûÈo.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "distribuindo", "open policy agent", "opa", "rego"]
:sidebar_label: Distribuir
:current-version: {page-origin-branch}

Vocûˆ escreveu, construiu e executou sua polûÙtica Rego.
Agora ûˋ hora de distribuir a polûÙtica.

As polûÙticas precisam ser anotadas para que possam ser executadas no `policy-server`.
O `policy-server` ûˋ a parte que executa as polûÙticas, quando estûÀ em execuûÏûÈo em um cluster Kubernetes.

== Anotando a polûÙtica

Anotar uma polûÙtica ûˋ um processo que enriquece os metadados da polûÙtica com informaûÏûçes relevantes.
InformaûÏûçes como autoria, licenûÏa, localizaûÏûÈo do cû°digo-fonte, regras, que descrevem que tipo de recursos esta polûÙtica entende e avalia.

Para anotar sua polûÙtica, vocûˆ precisa escrever um arquivo `metadata.yaml`:

[subs="+attributes",yaml]
----
rules:
- apiGroups: [""]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["CREATE"]
mutating: false
contextAware: false
executionMode: opa
annotations:
  io.kubewarden.policy.title: no-default-namespace
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: This policy will reject any resource created inside the default namespace
  io.kubewarden.policy.author: The {project-name} Authors
  io.kubewarden.policy.url: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.source: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
      This policy is just an example.

      You can write interesting descriptions about the policy here.
----

Vocûˆ pode ver vûÀrios detalhes:

* Regras:
Quais recursos a polûÙtica tem como alvo.
* MutaûÏûÈo:
Se esta polûÙtica realiza mutaûÏûÈo.
Neste caso, ela estûÀ apenas validando.
* SensûÙvel ao contexto:
Se esta polûÙtica requer contexto do cluster para avaliar a solicitaûÏûÈo.
* Modo de execuûÏûÈo:
Como esta ûˋ uma polûÙtica Rego, ûˋ obrigatû°rio especificar qual modo de execuûÏûÈo ela espera, `opa` ou `gatekeeper`.
Esta polûÙtica estûÀ escrita no estilo `opa`, retornando um objeto `AdmissionReview` completo.
* AnotaûÏûçes: Metadados armazenados na prû°pria polûÙtica.

VûÀ em frente e anote sua polûÙtica:

[subs="+attributes",console]
----
$ kwctl annotate policy.wasm --metadata-path metadata.yaml --output-path annotated-policy.wasm
----

Agora vocûˆ pode inspecionar a polûÙtica executando `kwctl inspect annotated-policy.wasm`.

== Enviando a polûÙtica

Agora que a polûÙtica estûÀ anotada, vocûˆ pode enviûÀ-la para um registro OCI.

[subs="+attributes",console]
----
$ kwctl push annotated-policy.wasm registry.my-company.com/kubewarden/no-default-namespace:v0.0.1
Policy successfully pushed
----

Sua polûÙtica Rego, direcionada ao framework OPA, tem tudo o que precisa para ser implantada em produûÏûÈo, criando um `ClusterAdmissionPolicy`.
Vocûˆ tambûˋm pode preparar isso.
Primeiro, vocûˆ precisa puxar a polûÙtica para o armazenamento local `kwctl`:

[subs="+attributes",console]
----
$ kwctl pull registry://registry.my-company.com/kubewarden/no-default-namespace:v0.0.1
pulling policy...
----

Crie um `ClusterAdmissionPolicy` a partir disso.
Esta operaûÏûÈo leva em conta os metadados que possui sobre a polûÙtica:

[subs="+attributes",console]
----
$ kwctl manifest registry://registry.my-company.com/kubewarden/no-default-namespace:v0.0.1 --type ClusterAdmissionPolicy
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "registry://registry.my-company.com/kubewarden/no-default-namespace:v0.0.1"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Agora vocûˆ pode usar este `ClusterAdmissionPolicy` como base para direcionar os recursos que deseja, ou implantar no Kubernetes como estûÀ.
