include::partial$variables.adoc[]
= Glosario
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-06-18
:page-revdate: {revdate}
:description: Explora recursos clave y configuraciones relacionadas con las políticas de {admc-name} en entornos de Kubernetes para más información.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["glossary"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "glossary"]
:sidebar_label: Glosario
:sidebar_position: 90
:current-version: {page-origin-branch}

== A

[#_admissionpolicy]
=== AdmissionPolicy

Un recurso a nivel de espacio de nombres. La política procesa únicamente aquellas solicitudes que están dirigidas al espacio de nombres en el que se define la PolíticaDeAdmisión.

== C

[#_clusteradmissionpolicy]
=== ClusterAdmissionPolicy

Una <<_admissionpolicy,PolíticaDeAdmisión>> que apunta a recursos a nivel de clúster.

[#_clusterreport]
=== ClusterReport

Un <<_report,Informe>> y un InformeDeClúster almacenan los resultados de los escaneos de políticas. Cuál se utiliza depende del alcance del recurso.

== K

[#_kwctl]
=== kwctl

Una herramienta CLI para generar y probar archivos YAML de Kubernetes para la ampliación de políticas.

== L

[#_mutatingwebhookconfiguration]
=== MutatingWebhookConfiguration

Un https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[recurso de Kubernetes] creado por el controlador {admc-short-name} para informar a Kubernetes dónde enviar un `AdmissionReview`.
En otras palabras, así es como un {admc-short-name} controlador informa a Kubernetes dónde encontrar una política de mutación de recursos.

== P

[#_report]
=== Informe

Un Informe y un <<_clusterreport,InformeDeClúster>> almacenan los resultados de los escaneos de políticas. Cuál se utiliza depende del alcance del recurso.

[#_policyserver]
=== PolicyServer

Un ServidorDePolíticas valida las solicitudes entrantes ejecutando {admc-short-name} políticas contra las solicitudes.

== V

[#_validatingwebhookconfiguration]
=== ValidatingWebhookConfiguration

Un https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[recurso de Kubernetes] creado por el controlador {admc-short-name} para informar a Kubernetes dónde enviar un `AdmissionReview`.
En otras palabras, así es como {admc-short-name} informa a Kubernetes dónde encontrar una política de validación de recursos.

== Mx

[#_wapc]
=== waPC

Llamadas a Procedimientos de WebAssembly. https://wapc.io.

[#_wasi]
=== WASI

Interfaz de Sistema de WebAssembly. https://wasi.dev.

[#_wasm]
=== Wasm

Un formato de instrucción binaria para una máquina virtual basada en pila. Diseñado para el despliegue web. https://webassembly.org.

[#_wasmtime]
=== Wasmtime

Un tiempo de ejecución para WebAssembly. https://wasmtime.dev.
