include::partial$variables.adoc[]

= Scanner de Auditoria
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Verifique o estado de conformidade de seus clusters usando o recurso Scanner de Auditoria dentro de {project-name}, para garantir sua configuraĂ§ĂŁo adequada.
:doc-persona: ["kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["howto", "audit-scanner-installation"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "audit scanner"]
:sidebar_label: Scanner de Auditoria
:sidebar_position: 70
:current-version: {page-origin-branch}

A partir da versĂŁo `v1.7.0`, {project-name} possui um novo recurso chamado "Scanner de Auditoria". Um novo componente, chamado "Scanner de Auditoria", verifica constantemente os recursos declarados no cluster, sinalizando aqueles que nĂŁo estĂŁo em conformidade com as polĂ­ticas {project-name} implantadas e salvando esses resultados em recursos customizados de relatĂłrio especĂ­ficos.

As polĂ­ticas evoluem ao longo do tempo: vocĂȘ implanta novas polĂ­ticas e atualiza as polĂ­ticas existentes. Tanto a versĂŁo quanto as configuraĂ§Ă”es mudam. Isso pode levar a situaĂ§Ă”es em que recursos jĂĄ no cluster nĂŁo estĂŁo mais em conformidade.

O recurso scanner de auditoria fornece aos administradores do Kubernetes uma ferramenta para verificar consistentemente o estado de conformidade de seus clusters.

O Scanner de Auditoria pode salvar seus resultados tanto em definiĂ§Ă”es de recursos personalizados (CRDs) OpenReports de link:https://openreports.io[openreports.io] (a configuraĂ§ĂŁo padrĂŁo desde a v1.33) ou PolicyReports do link:https://github.com/kubernetes-sigs/wg-policy-prototypes[grupo de trabalho de polĂ­ticas do Kubernetes] (marcado como descontinuado desde a v1.30, nĂŁo instalado nem criado por padrĂŁo desde a v1.30, programado para remoĂ§ĂŁo em uma versĂŁo futura).

== InstalaĂ§ĂŁo

O componente Scanner de Auditoria estĂĄ disponĂ­vel desde {short-project-name} `v1.7.0`.
Portanto, certifique-se de que estĂĄ instalando o grĂĄfico do Helm com a versĂŁo do app `v1.7.0` ou superior.

. Instale o grĂĄfico do Helm `kubewarden-crds`. O grĂĄfico instala os CRDs necessĂĄrios `PolicyReport` por padrĂŁo.
+
[subs="+attributes",console]
----
helm install kubewarden-crds kubewarden/kubewarden-crds
----
+

[NOTE]
====
Com o Kubewarden 1.33, o recurso Scanner de Auditoria salva os relatĂłrios em CRDs OpenReports de [openreports.io](https://openreports.io) por padrĂŁo.

Os CRDs link:https://htmlpreview.github.io/?https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/045372e558b896695b2daae92e8c7a04d4d40282/policy-report/docs/index.html[PolicyReport] do grupo de trabalho de polĂ­ticas do K8s nĂŁo sĂŁo instalados por padrĂŁo, estĂŁo marcados como descontinuados e serĂŁo removidos em uma versĂŁo futura.

UsuĂĄrios que desejam continuar usando os PolicyReports descontinuados, ou seja, o comportamento anterior Ă  1.33, precisam: - Alterar o valor do grĂĄfico do Helm `kubewarden-crds` de `.Values.install.installPolicyReportCRDs` para `true`. - Alterar o valor do grĂĄfico do Helm `kubewarden-controller` de `.Values.auditScanner.reportCRDsKind` de `openreports` para `policyreport`.
====
+
[CAUTION]
====
Para armazenar os resultados dos relatĂłrios de polĂ­ticas, vocĂȘ precisa ter as definiĂ§Ă”es de recursos personalizados (CRDs) do PolicyReport disponĂ­veis. Se os CRDs do PolicyReport necessĂĄrios jĂĄ estiverem no cluster, vocĂȘ nĂŁo pode instalĂĄ-los usando o grĂĄfico kubewarden-crds. Nesse caso, vocĂȘ pode desabilitar a instalaĂ§ĂŁo dos CRDs do OpenReport definindo `installOpenReportCRDs` como `false` no grĂĄfico (ou `installPolicyReportCRDs` como `false` se estiver usando os PolicyReports descontinuados).
Isso significa que a pilha Kubewarden nĂŁo gerenciarĂĄ esses CRDs, e a responsabilidade Ă© dos administradores.

Veja mais informaĂ§Ă”es sobre os CRDs no repositĂłrio do link:https://github.com/kubernetes-sigs/wg-policy-prototypes[grupo de trabalho de polĂ­ticas].

====


. Instale o grĂĄfico do Helm `kubewarden-controller`.
+
[subs="+attributes",console]
----
helm install kubewarden-controller kubewarden/kubewarden-controller
----
+

[NOTE]
====
O Scanner de Auditoria estĂĄ habilitado por padrĂŁo. Para desabilitĂĄ-lo, defina o `auditScanner.enable=false`.
====
+
[NOTE]
====
Se vocĂȘ quiser que o Scanner de Auditoria salve seus relatĂłrios nos CRDs do PolicyReports (marcados como descontinuados) em vez dos CRDs padrĂŁo do OpenReports, defina `auditScanner.reportCRDsKind="policyreport"`.
====

Para mais informaĂ§Ă”es sobre a instalaĂ§ĂŁo de {short-project-name}, consulte o xref:quick-start.adoc[Guia de InĂ­cio RĂĄpido].

Por padrĂŁo, a implementaĂ§ĂŁo do Scanner de Auditoria Ă© como um https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs[Cronjob] acionado a cada 60 minutos. VocĂȘ pode ajustar isso e outras configuraĂ§Ă”es do Scanner de Auditoria alterando o grĂĄfico do kubewarden-controller https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/values.yaml[values.yaml].

Veja xref:explanations/audit-scanner/audit-scanner.adoc[aqui] mais informaĂ§Ă”es sobre o Scanner de Auditoria.

=== Interface do UsuĂĄrio do Policy Reporter (opcional)

O grĂĄfico `kubewarden-controller` vem com um subgrĂĄfico do https://kyverno.github.io/policy-reporter[Policy Reporter]. EstĂĄ desabilitado por padrĂŁo e pode ser habilitado definindo `auditScanner.policyReporter=true`. Os valores do subgrĂĄfico do Policy Reporter estĂŁo sob a chave `policyReporter` dos valores `kubewarden-controller`.

Isso instala apenas parte do grĂĄfico upstream do Policy Reporter, a UI, que fornece uma visualizaĂ§ĂŁo dos PolicyReports e ClusterPolicyReports em um cluster. Veja xref:explanations/audit-scanner/audit-scanner.adoc[Scanner de Auditoria] para mais informaĂ§Ă”es sobre a UI do Policy Reporter.

Por padrĂŁo, a UI do Policy Reporter Ă© exposta apenas como um serviĂ§o ClusterIP com o nome `kubewarden-controller-ui` no namespace de instalaĂ§ĂŁo de

O grĂĄfico `kubewarden-controller` foi instalado.

==== Ingress

Os usuĂĄrios podem fornecer sua prĂłpria configuraĂ§ĂŁo de Ingress ou habilitar um Ingress atravĂ©s da configuraĂ§ĂŁo do subgrĂĄfico https://github.com/kyverno/policy-reporter/blob/policy-reporter-2.19.4/charts/policy-reporter/charts/ui/values.yaml#L172-L189[aqui].

Veja este exemplo de configuraĂ§ĂŁo de Ingress via o subgrĂĄfico:

[subs="+attributes",yaml]
----
auditScanner:
  policyReporter: true
policy-reporter: # subchart values settings
  ui:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - host: "*.local" # change this to your appropriate domain
          paths:
            - path: /
              pathType: ImplementationSpecific
----

==== Encaminhamento de porta

Para uma visĂŁo rĂĄpida ou depuraĂ§ĂŁo, pode-se configurar um encaminhamento de porta para o serviĂ§o com:

[subs="+attributes",console]
----
kubectl port-forward service/kubewarden-controller-ui 8082:8080 -n kubewarden
----

O que torna a interface do Policy Reporter disponĂ­vel em `\http://localhost:8082`.

== Acionar execuĂ§ĂŁo manual

A implementaĂ§ĂŁo do Scanner de Auditoria Ă© como um Cronjob que roda a cada 60 minutos por padrĂŁo. Ă possĂ­vel acionar uma execuĂ§ĂŁo manual rodando o seguinte comando:

[subs="+attributes",bash]
----
kubectl create job \
    --namespace kubewarden \
    --from cronjob/audit-scanner \
    audit-scanner-manual-$(date +%Y-%m-%d-%H-%M-%S)
----

VocĂȘ pode verificar o status do trabalho com:

[subs="+attributes",console]
----
kubectl get -n kubewarden jobs
----
