include::partial$variables.adoc[]
= {project-name} em um Ambiente de Grande Escala
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure {project-name}s com {project-name} para garantir alta disponibilidade e desempenho em ambientes de grande escala exigentes.
:keywords: [kubewarden, "{project-name}", kubernetes, policyservers, produĂ§ĂŁo]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: operator-manual, policyservers, produĂ§ĂŁo
:sidebar_label: ImplantaĂ§ĂŁo em escala
:sidebar_position: 21

Esta seĂ§ĂŁo detalha uma implantaĂ§ĂŁo do mundo real de {project-name} em um ambiente de grande escala exigente. Ela ilustra como configurar {short-project-name} para alta disponibilidade e desempenho e o que esperar sob carga pesada.

[IMPORTANT]
====
Se vocĂŞ quiser ver mais dicas sobre como executar {short-project-name} em produĂ§ĂŁo, confira a documentaĂ§ĂŁo de xref:/howtos/production-deployments.adoc[ImplantaĂ§Ăµes em produĂ§ĂŁo].
====

== VisĂŁo Geral do Ambiente

A infraestrutura consiste em aproximadamente 20 clusters Kubernetes. Os maiores desses clusters sĂŁo caracterizados por tamanho significativo e volume de recursos:

* NĂłs: ~400
* Namespaces: ~4.000
* Recursos gerenciados:
** Pods: 10,000
** RoleBindings: 13.000
** Ingresses: 12.000
** ImplantaĂ§Ăµes: 8.000
** ServiĂ§os: 13.000

== {short-project-name} ConfiguraĂ§ĂŁo

Para atender Ă s demandas deste ambiente, {short-project-name} Ă© configurado com foco no isolamento de carga de trabalho e alta disponibilidade.

* AplicaĂ§ĂŁo da PolĂ­tica: 22 `ClusterAdmissionPolicies` sĂŁo aplicadas em todos os clusters, sem `AdmissionPolicies` especĂ­fico de namespace.
* Arquitetura do PolicyServer: Duas implantaĂ§Ăµes `PolicyServer` separadas sĂŁo usadas para isolar cargas de trabalho:
** Uma `PolicyServer` Ă© dedicada exclusivamente a polĂ­ticas contextuais.
** Uma segunda `PolicyServer` lida com todas as outras polĂ­ticas nĂŁo contextuais.
* Escalabilidade e Recursos:
** RĂ©plicas: Cada implantaĂ§ĂŁo `PolicyServer` executa 15 rĂ©plicas para lidar com o alto volume de solicitaĂ§Ăµes.
** AlocaĂ§ĂŁo de Recursos: Cada rĂ©plica Ă© alocada com 300 MB de memĂłria e 4 nĂşcleos de CPU.

== MĂ©tricas de Desempenho

Esta configuraĂ§ĂŁo gerencia com sucesso uma alta taxa de solicitaĂ§Ăµes de admissĂŁo enquanto mantĂ©m um desempenho previsĂ­vel.

* Taxa de Processamento das SolicitaĂ§Ăµes de AdmissĂŁo: Os clusters lidam com atĂ© 300 solicitaĂ§Ăµes de admissĂŁo por segundo (incluindo validaĂ§Ăµes de webhook e varreduras de auditoria).
* LatĂŞncia da PolĂ­tica:
** LatĂŞncia TĂ­pica: PolĂ­ticas contextuais geralmente levam cerca de 500ms para serem executadas.
** Tempos de espera: Neste ambiente de alta capacidade, os tempos de espera do webhook estĂŁo configurados para 2,5 segundos, enquanto o tempo de espera `PolicyServer` estĂˇ definido para 10 segundos. Embora a maioria das solicitaĂ§Ăµes seja rĂˇpida, a infraestrutura Ă© construĂ­da para lidar com operaĂ§Ăµes ocasionalmente lentas sem comprometer a estabilidade do servidor da API.

== Desempenho do Scanner de Auditoria

O scanner de auditoria Ă© utilizado para garantir conformidade contĂ­nua em um grande nĂşmero de recursos.

* FrequĂŞncia: Uma auditoria em todo o cluster Ă© realizada a cada 4 horas.
* ConfiguraĂ§ĂŁo: O trabalho de auditoria Ă© ajustado para mĂˇximo paralelismo a fim de reduzir o tempo de execuĂ§ĂŁo:

[source,shell]
----
--parallel-namespaces: "10"
--parallel-resources: "20"
--parallel-policies: "20"
--page-size: "1000"
----

* DuraĂ§ĂŁo da Auditoria: Mesmo no maior cluster com dezenas de milhares de recursos, um trabalho de auditoria completo Ă© concluĂ­do em
