include::partial$variables.adoc[]
= Como usar grupos de políticas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Implemente grupos de políticas com regras específicas que rejeitam Pods não conformes com base em assinaturas de imagem e outros critérios.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["explanations", "policy-group"]
:doc-type: ["howto"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "grupos de políticas", "grupo de política de admissão de cluster", "grupo de política de admissão"]
:sidebar_label: Grupos de políticas
:sidebar_position: 36
:current-version: {page-origin-branch}

[TIP]
====
Antes de trabalhar com Grupos de Políticas, consulte a
xref:explanations/policy-groups.adoc[explicação].
====


Usando o exemplo da xref:../explanations/policy-groups.adoc[explicação dos Grupos de Políticas],
use estes comandos para implementá-lo.

[,shell]
----
kubectl apply -f group-policy-demo.yaml
----

.Um `ClusterAdmissionPolicyGroup` que rejeita Pods que usam imagens com a tag `latest`, a menos que as imagens sejam assinadas por duas partes confiáveis: Alice e Bob.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  policies:
    signed_by_alice:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
                yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
                -----END PUBLIC KEY-----
    signed_by_bob:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X
                urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==
                -----END PUBLIC KEY-----
    reject_latest:
      module: registry://ghcr.io/kubewarden/policies/trusted-repos:v0.2.0
      settings:
        tags:
          reject:
            - latest
  expression: "reject_latest() || (signed_by_alice() && signed_by_bob())"
  message: "the image is using the latest tag or is not signed by Alice and Bob"
----
======

Uma vez que a política esteja ativa, a criação de um Pod não conforme será rejeitada.
Para obter mais informações sobre a avaliação das políticas que fazem parte do
grupo, aumente o nível de verbosidade de `kubectl`:

[,console]
----
kubectl -v4 apply -f signed-pod.yml
I0919 18:29:40.251332    4330 helpers.go:246] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"signed-pod.yml\": admission webhook \"clusterwide-demo.kubewarden.admission\" denied the request: the image is using the latest tag or is not signed by Alice and Bob",
  "details": {
    "causes": [
      {
        "message": "Resource signed is not accepted: verification of image testing.registry.svc.lan/busybox:latest failed: Host error: Callback evaluation failure: Image verification failed: missing signatures\nThe following constraints were not satisfied:\nkind: pubKey\nowner: null\nkey: |\n  -----BEGIN PUBLIC KEY-----\n  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X\n  urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==\n  -----END PUBLIC KEY-----\nannotations: null\n",
        "field": "spec.policies.signed_by_bob"
      },
      {
        "message": "not allowed, reported errors: tags not allowed: latest",
        "field": "spec.policies.reject_latest"
      }
    ]
  },
  "code": 400
}]
Error from server: error when creating "signed-pod.yml": admission webhook "clusterwide-demo.kubewarden.admission" denied the request: the image is using the latest tag or is not signed by Alice and Bob
----

[NOTE]
====
A saída da avaliação produzida pelas políticas que fazem parte do grupo é visível
apenas aumentando o nível de verbosidade de `kubectl`.

Um nível de verbosidade de `4` é suficiente para ver a saída da avaliação das políticas.
====

