include::partial$variables.adoc[]
= Configurando a pilha {project-name} para produĂ§ĂŁo
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure tolerĂąncias e regras de afinidade para agendamento e confiabilidade ideais dentro da pilha {project-name} em um cluster Kubernetes.
:keywords: ["{project-name}", kubewarden, kubernetes, policyservers, produĂ§ĂŁo, poddisruptionbudget, afinidade, limites, tolerĂąncias, priorityclass]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual-do-operador, servidores-de-polĂ­tica, produĂ§ĂŁo, poddisruptionbudget, afinidade, limites, tolerĂąncias, priorityclass

{project-name} oferece recursos para confiabilidade e agendamento correto de seus componentes em um cluster Kubernetes. Algumas das dicas nesta pĂĄgina vĂȘm de membros da comunidade {short-project-name} usando {short-project-name} em grande escala.

[IMPORTANT]
====
Se vocĂȘ quiser ver um exemplo real de execuĂ§ĂŁo de {short-project-name} em grande escala, confira a pĂĄgina de documentaĂ§ĂŁo xref:/howtos/deploy-at-scale.adoc[{short-project-name} em um Ambiente de Grande Escala].

====

== Configurando TolerĂąncias e Afinidade/Anti-Afinidade

Ao usar os campos `tolerations` e `affinity`, os operadores podem ajustar o agendamento e a confiabilidade da pilha {short-project-name} para atender Ă s suas necessidades e restriĂ§Ă”es especĂ­ficas de implantaĂ§ĂŁo. Para mais detalhes sobre os campos exatos e suas configuraĂ§Ă”es, consulte a https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[documentaĂ§ĂŁo do Kubernetes sobre Taints e TolerĂąncias] e https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[Afinidade e Anti-Afinidade].

A partir da versĂŁo 1.15 da pilha {short-project-name}, os grĂĄficos Helm {short-project-name} vĂȘm com dois novos valores:

* `.global.tolerations`
* `.global.affinity`

Esses valores do grĂĄfico Helm permitem que os usuĂĄrios definam tolerĂąncias do Kubernetes e configuraĂ§Ă”es de afinidade/anti-afinidade para a pilha {short-project-name}, incluindo a implantaĂ§ĂŁo do controlador, o cronjob do scanner de auditoria e o recurso personalizado padrĂŁo `PolicyServer`.

=== TolerĂąncias

O valor `tolerations` Ă© um array onde os usuĂĄrios podem especificar tolerĂąncias do Kubernetes para os componentes {short-project-name}. TolerĂąncias permitem que pods sejam agendados em nĂłs com taints correspondentes. Isso Ă© Ăștil para gerenciar onde os pods podem ser agendados, especialmente em cenĂĄrios que envolvem manutenĂ§ĂŁo de nĂłs, cargas de trabalho dedicadas ou requisitos de hardware especĂ­ficos:

[source,yaml]
----
global:
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoSchedule"
    - key: "key2"
      operator: "Equal"
      value: "value2"
      effect: "NoExecute"
----

Neste exemplo, as tolerĂąncias definidas sĂŁo aplicadas Ă  implantaĂ§ĂŁo do controlador, ao cronjob do scanner de auditoria e ao recurso personalizado padrĂŁo `PolicyServer`.

=== Afinidade/Anti-Afinidade

O valor `affinity` permite que os usuĂĄrios definam regras de afinidade e anti-afinidade do Kubernetes para os componentes {short-project-name}. Regras de afinidade restringem pods a nĂłs especĂ­ficos, enquanto regras de anti-afinidade impedem que pods sejam agendados em certos nĂłs ou em estreita proximidade com outros pods. Essas configuraĂ§Ă”es sĂŁo Ășteis para garantir alta disponibilidade, tolerĂąncia a falhas e uso otimizado de recursos em um cluster.

[source,yaml]
----
global:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: security
                operator: In
                values:
                  - S1
          topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: security
                  operator: In
                  values:
                    - S2
            topologyKey: topology.kubernetes.io/zone
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: label-1
                operator: In
                values:
                  - key-1
        - weight: 50
          preference:
            matchExpressions:
              - key: label-2
                operator: In
                values:
                  - key-2
----

Neste exemplo, as regras de afinidade serĂŁo aplicadas Ă  implantaĂ§ĂŁo do controlador, ao cronjob do scanner de auditoria e ao recurso personalizado padrĂŁo `PolicyServer`.

A configuraĂ§ĂŁo de afinidade anterior disponĂ­vel no Helm chart `kubewarden-default`, que era usada para definir a configuraĂ§ĂŁo de afinidade apenas para o `PolicyServer`, foi removida em favor do valor global `affinity`. Essa mudanĂ§a simplifica o processo de configuraĂ§ĂŁo ao fornecer uma Ășnica abordagem para definir regras de afinidade e anti-afinidade para todos os componentes {short-project-name}.

[WARNING]
====
A antiga configuraĂ§ĂŁo `affinity` no Helm chart `kubewarden-default` foi removida. Os usuĂĄrios agora devem usar o campo `.global.affinity` para configurar as definiĂ§Ă”es de afinidade e anti-afinidade para toda a pilha {short-project-name}.
====

== Configurando Classes de Prioridade

Ao usar classes de prioridade, os operadores podem impor uma prioridade de agendamento para os pods de carga de trabalho da pilha {short-project-name}. Isso garante que a carga de trabalho {short-project-name} esteja disponĂ­vel em relaĂ§ĂŁo a outras cargas de trabalho, prevenindo a evacuaĂ§ĂŁo e garantindo a confiabilidade do serviĂ§o. Para mais informaĂ§Ă”es, consulte a https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/[documentaĂ§ĂŁo do Kubernetes sobre Classes de Prioridade].

A partir da versĂŁo 1.25 da pilha {short-project-name}, os Helm charts {short-project-name} vĂȘm com um novo valor:

* `.global.priorityClassName`

A classe de prioridade definida pelo nome neste valor Ă© aplicada aos pods de implantaĂ§ĂŁo do controlador e aos pods do recurso customizado `PolicyServer` padrĂŁo.

O valor `.global.priorityClassName` espera um nome de uma classe de prioridade existente. Como exemplo, poderĂ­amos usar:

[source,yaml]
----
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubewarden-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
----

O Kubernetes jĂĄ vem com duas classes de prioridade que sĂŁo boas candidatas: `system-cluster-critical` e `system-node-critical`. Essas sĂŁo classes comuns e sĂŁo usadas para https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/[garantir que componentes crĂ­ticos sejam sempre agendados primeiro].

[WARNING]
====
Se vocĂȘ excluir uma classe de prioridade, os Pods existentes que usam o nome da classe de prioridade excluĂ­da permanecem inalterados, mas os Pods subsequentes que usam o nome da classe de prioridade excluĂ­da nĂŁo serĂŁo criados pelo Kubernetes.
====

== `PolicyServer` ConfiguraĂ§ĂŁo de produĂ§ĂŁo

`PolicyServers` sĂŁo crĂ­ticos para o cluster. A confiabilidade deles Ă© importante, pois processam SolicitaĂ§Ă”es de AdmissĂŁo destinadas Ă  API do Kubernetes via os Webhooks de ValidaĂ§ĂŁo e MutaĂ§ĂŁo.

Assim como outros Controladores de AdmissĂŁo DinĂąmica, esse processo ocorre antes que as solicitaĂ§Ă”es cheguem ao servidor de API do Kubernetes. A latĂȘncia ou atrasos de serviĂ§o pelo Controlador de AdmissĂŁo DinĂąmica podem introduzir inconsistĂȘncia no cluster, negaĂ§ĂŁo de serviĂ§o ou deadlock.

{short-project-name} oferece vĂĄrias maneiras de aumentar a confiabilidade de `PolicyServers`. As implantaĂ§Ă”es em produĂ§ĂŁo podem variar bastante, cabendo ao operador configurar a implantaĂ§ĂŁo de acordo com suas necessidades.

=== OrĂ§amentos de InterrupĂ§ĂŁo de Pod

O controlador {short-project-name} pode criar um https://kubernetes.io/docs/tasks/run-application/configure-pdb/[OrĂ§amento de InterrupĂ§ĂŁo de Pod] (PDB) para os Pods `PolicyServer`. Isso controla a faixa de rĂ©plicas de Pods `PolicyServer` associadas ao `PolicyServer`, garantindo alta disponibilidade e evacuaĂ§ĂŁo controlada em caso de manutenĂ§ĂŁo de nĂł, operaĂ§Ă”es de escalonamento ou atualizaĂ§Ă”es de cluster.

Isso Ă© alcanĂ§ado definindo `spec.minAvailable`, ou `spec.maxUnavailable` do recurso `PolicyServer`:

* `minAvailable`: especifica o nĂșmero mĂ­nimo de Pods `PolicyServer` que devem estar disponĂ­veis em todos os momentos. Pode ser um nĂșmero inteiro ou uma porcentagem.

  Useful for maintaining the operational integrity of the `PolicyServer`,
  ensuring that policies are continuously enforced without interruption.

* `maxUnavailable`: especifica o nĂșmero mĂĄximo de Pods `PolicyServer` que podem estar indisponĂ­veis a qualquer momento. Pode ser um nĂșmero inteiro ou uma porcentagem.

  Useful for performing rolling updates or partial maintenance without
  fully halting the policy enforcement mechanism.

[NOTE]
====
VocĂȘ pode especificar apenas um de `maxUnavailable` e `minAvailable`.
====

==== Configurando minAvailable ou maxUnavailable

.Exemplo: Defina minAvailable
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  minAvailable: 2 # ensure at least two policy-server Pods are available at all times
----

.Exemplo: Defina maxUnavailable
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  maxUnavailable: "30%" # ensure no more than 30% of policy-server Pods are unavailable at all times
----

=== Afinidade / Anti-afinidade

O controlador {short-project-name} pode definir a afinidade dos Pods `PolicyServer`. Isso permite restringir Pods a nĂłs especĂ­ficos, ou Pods em relaĂ§ĂŁo a outros Pods. Para mais informaĂ§Ă”es sobre Afinidade, consulte a https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[documentaĂ§ĂŁo do Kubernetes].

A configuraĂ§ĂŁo de afinidade do Kubernetes permite restringir Pods a nĂłs (via `spec.affinity.nodeAffinity`) ou restringir Pods em relaĂ§ĂŁo a outros Pods (via `spec.affinity.podAffinity`). A afinidade pode ser configurada como uma restriĂ§ĂŁo suave (com `preferredDuringSchedulingIgnoredDuringExecution`) ou uma restriĂ§ĂŁo rĂ­gida (com `requiredDuringSchedulingIgnoredDuringExecution`).

A afinidade / anti-afinidade corresponde a rĂłtulos especĂ­ficos, seja rĂłtulos de nĂłs (por exemplo: `topology.kubernetes.io/zone` definido como `antarctica-east1`) ou rĂłtulos de Pods. Pods criados a partir de definiĂ§Ă”es `PolicyServer` tĂȘm um rĂłtulo `kubewarden/policy-server` definido como o nome do `PolicyServer`. (por exemplo: `kubewarden/policy-server: default`).

[NOTE]
====
A afinidade/anti-afinidade entre Pods requer quantidades substanciais de processamento e nĂŁo Ă© recomendada em clusters maiores que vĂĄrias centenas de nĂłs.
====

Para configurar a afinidade para um `PolicyServer`, defina seu campo `spec.affinity`. Este campo aceita um objeto YAML que corresponde ao conteĂșdo do `spec.affinity` de um Pod.

==== Configurando Afinidade / Anti-afinidade

.Exemplo: Espalhe os Pods `PolicyServer` por zonas e nomes de host
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: kubewarden/policy-server
                operator: In
                values:
                  - your-policy-server
          topologyKey: topology.kubernetes.io/zone
        - labelSelector:
            matchExpressions:
              - key: kubewarden/policy-server
                operator: In
                values:
                  - your-policy-server
          topologyKey: kubernetes.io/hostname
----

.Exemplo: Agende apenas Pods `PolicyServer` em nĂłs do plano de controle
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: kubewarden/policy-server
                operator: In
                values:
                  - your-policy-server
          topologyKey: node-role.kubernetes.io/control-plane
----

=== Limites e SolicitaĂ§Ă”es

O controlador {short-project-name} pode definir os limites de recursos e solicitaĂ§Ă”es dos Pods `PolicyServer`. Isso especifica quanto de cada recurso cada um dos contĂȘineres associados aos Pods `PolicyServer` necessita. Para `PolicyServers`, apenas os recursos `cpu` e `memory` sĂŁo relevantes. Consulte a https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes[documentaĂ§ĂŁo do Kubernetes] sobre unidades de recursos para mais informaĂ§Ă”es.

Isso Ă© alcanĂ§ado definindo os seguintes campos de recursos `PolicyServer`:

* `spec.limits`: Limites sobre recursos, impostos pelo tempo de execuĂ§ĂŁo do contĂȘiner. Diferentes tempos de execuĂ§ĂŁo podem ter maneiras diferentes de implementar as restriĂ§Ă”es.
* `spec.requests`: Quantidade de recursos a reservar para cada contĂȘiner. Ă possĂ­vel e permitido que um contĂȘiner use mais recursos do que seu `request`.

  If omitted, it defaults to `spec.limits` if that is set (unless
  `spec.requests` of containers is set to some defaults via an admission
  mechanism).

[NOTE]
====
Subestimar recursos de `PolicyServers` pode causar problemas de confiabilidade no cluster.
====

==== Configurando Limites e SolicitaĂ§Ă”es

.Exemplo: Defina limites rĂ­gidos para cada `PolicyServer` contĂȘiner
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  limits:
    cpu: 500m
    memory: 1Gi
----

=== Classes de Prioridade

O controlador {short-project-name} pode definir a classe de prioridade usada para os pods de `PolicyServers`. Isso significa que as cargas de trabalho `PolicyServer` sĂŁo agendadas com prioridade, prevenindo a evacuaĂ§ĂŁo e garantindo a confiabilidade do serviĂ§o. Consulte a https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/[documentaĂ§ĂŁo do Kubernetes para mais informaĂ§Ă”es].

[WARNING]
====
Se vocĂȘ excluir uma classe de prioridade, os Pods existentes que usam o nome da classe de prioridade excluĂ­da permanecem inalterados, mas os Pods subsequentes que usam o nome da classe de prioridade excluĂ­da nĂŁo serĂŁo criados pelo Kubernetes.
====

==== Configurando Classes de Prioridade

.Exemplo: Usando a classe de prioridade padrĂŁo `system-cluster-critical`:
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  priorityClassName: system-cluster-critical
----

=== Isolar cargas de trabalho de PolĂ­ticas

Para garantir estabilidade e alto desempenho em escala, os usuĂĄrios podem executar implantaĂ§Ă”es separadas *`PolicyServer`* para isolar diferentes cargas de trabalho.

* *Dedique um `PolicyServer` para PolĂ­ticas SensĂ­veis ao Contexto:* Essas polĂ­ticas sĂŁo mais intensivas em recursos porque consultam o servidor da API do Kubernetes ou outros serviĂ§os externos como Sigstore, registros OCI, entre outros. IsolĂĄ-las previne que uma polĂ­tica lenta crie um gargalo para outras polĂ­ticas mais rĂĄpidas.
* *Use outro `PolicyServer` para Todas as Outras PolĂ­ticas:* Execute polĂ­ticas regulares e autĂŽnomas em um servidor separado para garantir baixa latĂȘncia para os pedidos de admissĂŁo mais comuns.

VocĂȘ tambĂ©m pode considerar dividir ainda mais a carga de trabalho. Por exemplo, se vocĂȘ tiver algumas polĂ­ticas que sĂŁo lentas e requerem um tempo limite de execuĂ§ĂŁo maior, considere movĂȘ-las para um dedicado `PolicyServer`. Dessa forma, vocĂȘ garante que as polĂ­ticas nĂŁo bloqueiem os worker na avaliaĂ§ĂŁo de outros pedidos.

=== AlocaĂ§ĂŁo de Recursos e Escalonamento

Para lidar com alto trĂĄfego e garantir disponibilidade, forneĂ§a recursos suficientes e escale suas rĂ©plicas.

* *Aloque Recursos Suficientes:* Em ambientes de alto trĂĄfego, aloque recursos generosos para cada rĂ©plica. NĂŁo deixe o `PolicyServers` sem recursos, pois CPU ou memĂłria insuficientes sĂŁo uma das principais causas de timeouts de requisiĂ§ĂŁo. Lembre-se de que o `PolicyServers` receberĂĄ requisiĂ§Ă”es do plano de controle e do {short-project-name} scanner de auditoria.
* *Escale para Alta Disponibilidade:* Para implantaĂ§Ă”es que lidam com centenas de requisiĂ§Ă”es por segundo, execute um nĂșmero elevado de rĂ©plicas. Isso distribui a carga de forma eficaz e garante que a falha de alguns pods nĂŁo impacte a operaĂ§ĂŁo do cluster.

Comece com uma base de 3-5 rĂ©plicas e monitore o uso de CPU e memĂłria. Escalone a contagem de rĂ©plicas conforme necessĂĄrio.

=== Auditoria Eficaz em Escala

Para realizar auditorias de forma eficiente em grandes clusters, ajuste o scanner de auditoria para desempenho e paralelismo.

* *Agende Auditorias Periodicamente:* Executar uma varredura com frequĂȘncia pode ser um bom equilĂ­brio entre capturar desvios de configuraĂ§ĂŁo e minimizar a carga no servidor de API.
* *Ajuste o Paralelismo de Forma Agressiva:* A chave para auditorias rĂĄpidas Ă© a paralelizaĂ§ĂŁo. Com configuraĂ§Ă”es de alto paralelismo, vocĂȘ pode reduzir os tempos de auditoria em clusters massivos para pouco mais de uma hora.

[WARNING]
====
Ă importante lembrar que o scanner de auditoria envia requisiĂ§Ă”es para `PolicyServers`. Portanto, seu paralelismo pode impactar o desempenho de `PolicyServer`. Se vocĂȘ deseja ter um paralelismo agressivo para reduzir os tempos de varredura em grandes clusters, pode ser necessĂĄrio aumentar os recursos do servidor de polĂ­ticas disponĂ­veis para evitar impactar o desempenho do controlador de admissĂŁo.
====

Defina `disableStore: true` para reduzir a carga se vocĂȘ consumir resultados de auditoria dos logs e nĂŁo precisar de recursos personalizados de polĂ­tica `Reports` nem `ClusterReports` no cluster.
