include::partial$variables.adoc[]

= Backup e restauração com o Operador de Backup do Rancher
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure e gerencie backups e restaurações usando o operador rancher-backup em qualquer cluster Kubernetes.
:keywords: "{project-name}", Kubernetes, Kubewarden, Operador de Backup do Rancher, backup, restore
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: Manual do Operador, rancher-backup-operator
:current-version: {page-origin-branch}

O operador `rancher-backup` pode ser usado para fazer backup e restaurar o Rancher em qualquer cluster Kubernetes.

Desde a versão `v9.0.0`, `rancher-backup` tem suporte para {project-name}. Isso inclui:

- O Namespace padrão do Rancher `cattle-kubewarden-system` (ou `cattle-kubewarden-*`), e o Namespace padrão {short-project-name} `kubewarden`.
- Os recursos necessários de {short-project-name} são instalados por meio dos charts Helm.
- Os CRDs de {short-project-name}, que são reconciliados após a restauração pelo controlador {short-project-name}.
- O subchart `policy-reporter` do chart `kubewarden-controller`, para seus valores padrão. Isso não inclui a integração do Grafana nem outros plugins.

== Segredos do Usuário

O processo de backup não inclui segredos criados pelo usuário, como aqueles usados para xref:/howtos/policy-servers/02-private-registry.adoc#_creating_the_secret[configurar servidores de política para registros privados], a menos que estejam corretamente rotulados. Para isso, rotule os segredos de uma das seguintes maneiras. Ou:

[source,shell]
----
kubectl label secret secret-ghcr-docker app.kubernetes.io/part-of=kubewarden
----

Ou:

[source,shell]
----
kubectl label secret secret-ghcr-docker resources.cattle.io/backup=true
----

== Instalando o Operador de Backup do Rancher

Siga o \link: \https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.html[documentação do Rancher Manager]. Para uma instalação do Minikube usando os PersistentVolumes do tipo `hostPath` nomeados `standard` que o Minikube suporta por padrão.

É necessário instruir o Operador de Backup a também fazer backup de CRs definidos pelo usuário {short-project-name} definindo o Valor `optionalResources.kubewarden.enabled` como `true`.

A instalação será a seguinte:

[source,console]
----
helm repo add rancher-charts https://charts.rancher.io
helm repo update
helm install --wait --create-namespace -n cattle-resources-system \
    rancher-backup-crd rancher-charts/rancher-backup-crd
helm install --wait -n cattle-resources-system \
    rancher-backup rancher-charts/rancher-backup \
    --set persistence.enabled=true --set persistence.storageClass=standard \
    --set optionalResources.kubewarden.enabled=true
----

== Backup

Use o `rancher-resource-set-full` para fazer backup dos segredos {short-project-name}.
Isso inclui os segredos TLS que são criados na instalação do Helm.

Se você preferir usar `rancher-resource-basic`, lembre-se de fazer backup ou criar manualmente os segredos TLS necessários.

Aqui está um exemplo de como realizar um backup não criptografado para o local padrão com o `rancher-resource-set-full`:

[source,shell]
----
kubectl apply -f - <<EOF
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: default-location-backup
spec:
  resourceSetName: rancher-resource-set-full
EOF
backup.resources.cattle.io/default-location-backup created
----

Os logs do `rancher-backup` ou o backup mostram a criação do arquivo de backup:

[source,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
...
INFO[2025/06/26 10:07:48] Processing backup default-location-backup
INFO[2025/06/26 10:07:48] For backup CR default-location-backup, filename: default-location-backup-32d64f39-d3c7-4331-9101-8ca493bd9d2e-2025-06-26T10-07-48Z
...
INFO[2025/06/26 10:07:49] Done with backup
----

Você também pode ver seu status descrevendo o recurso:

[source,shell]
----
kubectl get backups
NAME                      LOCATION   TYPE       LATEST-BACKUP                                                                              RESOURCESET                 AGE    STATUS
default-location-backup   PV         One-time   default-location-backup-43f3ccb7-5624-4eed-9c3b-1c15d287080e-2025-06-26T15-53-27Z.tar.gz   rancher-resource-set-full   111s   Completed
----

Consulte a documentação do Rancher para mais link:https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.html#_backup[exemplos de backup].

== Restaurar

Para restaurar o backup não criptografado do local padrão, pegue o nome do arquivo da coluna LATEST-BACKUP ao exibir o recurso de backup para criar um recurso de restauração:

[source,shell]
----
kubectl apply -f - <<EOF
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: restore-default
spec:
  backupFilename: default-location-backup-32d64f39-d3c7-4331-9101-8ca493bd9d2e-2025-06-26T10-07-48Z.tar.gz
EOF
restore.resources.cattle.io/restore-default created

kubectl get restores
NAME              BACKUP-SOURCE   BACKUP-FILE                                                                                AGE   STATUS
restore-default   PV              default-location-backup-43f3ccb7-5624-4eed-9c3b-1c15d287080e-2025-06-26T15-53-27Z.tar.gz   6s    Completed
----

Consulte a documentação do Rancher para mais link:https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.html#_restore[exemplos de restauração].


