include::partial$variables.adoc[]
= Migração de ValidatingAdmissionPolicy
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Migre uma ValidatingAdmissionPolicy para {project-name} através dos passos de migração do comando kwctl para uma transição suave da política.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["vap-migration"]
:doc-type: ["howto"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "kubernetes", "cel", "vap", "validatingadmissionpolicy"]
:current-version: {page-origin-branch}

A partir do Kubernetes v1.26, o https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/[ValidatingAdmissionPolicy] fornece uma maneira de escrever políticas de admissão personalizadas no Kubernetes. As políticas são escritas com o https://cel.dev/[Common Expression Language (CEL)], estendidas com algumas https://kubernetes.io/docs/reference/using-api/cel/[extensões específicas do Kubernetes].
A ValidatingAdmissionPolicy alcançou estabilidade no Kubernetes v1.30.

{project-name} fornece uma política CEL que é capaz de executar políticas VAP do Kubernetes sem nenhuma modificação.
Você pode ler mais sobre a política CEL na xref:../tutorials/writing-policies/CEL/01-intro-cel.adoc[esta seção] da documentação de {short-project-name}.
xref:tutorials/writing-policies/CEL/01-intro-cel.adoc#_benefits_of_kubewardens_cel_policy_in_comparison_with_validatingadmissionpolicies[Este parágrafo] explica os benefícios de executar políticas VAP usando {short-project-name}.

Este guia explica como usar a ferramenta `kwctl` para migrar uma política VAP para {short-project-name}.

== Etapas de migração

[NOTE]
====
Você deve usar a versão 1.14.0 ou posterior do `kwctl` para seguir este guia.
====


Dado um arquivo contendo esta definição YAML de um `ValidatingAdmissionPolicy`:

.`ValidatingAdmissionPolicy` definição de
[%collapsible]
======
[subs="+attributes",yaml]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "force-liveness-probe"
spec:
  failurePolicy: Fail
  variables:
    - name: containers_without_liveness_probe
      expression: |
        object.spec.template.spec.containers.filter(c, !has(c.livenessProbe)).map(c, c.name)
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  validations:
    - expression: |
        size(variables.containers_without_liveness_probe) == 0
      messageExpression: |
        'These containers are missing a liveness probe: ' + variables.containers_without_liveness_probe.join(' ')
      reason: Invalid
----
======

E um arquivo contendo o `ValidatingAdmissionPolicyBinding` recurso:

.`ValidatingAdmissionPolicyBinding` definição de
[%collapsible]
======
[subs="+attributes",shell]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "kw-scaffold-demo"
spec:
  policyName: "force-liveness-probe"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchLabels:
        docs.kubewarden.io/vap-migration: enabled
----

======

Você pode migrar a política para {short-project-name} seguindo estes passos:

.`kwctl` comando para migração de política
[%collapsible]
======

[subs="+attributes",shell]
----
$ kwctl scaffold vap \
    -p vap.yml \
    -b vap-binding.yml
----

======

O comando produz uma saída semelhante a esta:

.Saída da migração
[%collapsible]
======

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: kw-scaffold-demo
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:latest
  settings:
    failurePolicy: Fail
    variables:
      - expression: |
          object.spec.template.spec.containers.filter(c, !has(c.livenessProbe)).map(c, c.name)
        name: containers_without_liveness_probe
    validations:
      - expression: |
          size(variables.containers_without_liveness_probe) == 0
        messageExpression: |
          'These containers are missing a liveness probe: ' + variables.containers_without_liveness_probe.join(' ')
        reason: Invalid
  rules:
    - apiGroups:
        - apps
      apiVersions:
        - v1
      resources:
        - deployments
      operations:
        - CREATE
        - UPDATE
  mutating: false
  namespaceSelector:
    matchLabels:
      docs.kubewarden.io/vap-migration: enabled
----
======

[NOTE]
====

O comando avisa o usuário sobre o uso da `latest` versão da política CEL:

[subs="+attributes",console]
----
024-06-24T16:00:16.516062Z  WARN kwctl::scaffold:
  Using the 'latest' version of the CEL policy could lead to unexpected behavior.
  It is recommended to use a specific version to avoid breaking changes.
----

É recomendável usar uma versão específica para evitar mudanças que quebrem a compatibilidade.

Você pode fazer isso usando a `--cel-policy` flag, assim:

[subs="+attributes",console]
----
$ kwctl scaffold vap \
    --cel-policy ghcr.io/kubewarden/policies/cel-policy:v1.0.1 \
    -p vap.yml \
    -b vap-binding.yml
----

====
