include::partial$variables.adoc[]

= Escáner de Auditoría
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Verifica el estado de cumplimiento de tus clústeres utilizando la función Audit Scanner dentro de {project-name}, para asegurar su correcta configuración.
:doc-persona: ["kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["howto", "audit-scanner-installation"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "audit scanner"]
:sidebar_label: Escáner de Auditoría
:sidebar_position: 70
:current-version: {page-origin-branch}

A partir de la versión `v1.7.0`, {project-name} tiene una nueva función llamada "Audit Scanner". Un nuevo componente, llamado "audit-scanner", comprueba constantemente los recursos declarados en el clúster, señalando aquellos que no cumplen con las políticas {project-name} desplegadas y guardando estos resultados en Recursos Personalizados específicos para informes.

Las políticas evolucionan con el tiempo: despliegas nuevas políticas y actualizas las políticas existentes. Tanto la versión como la configuración cambian. Esto puede llevar a situaciones en las que los recursos presentes en el clúster ya no cumplen.

La función de auditoría proporciona a los administradores de Kubernetes una herramienta para verificar de manera consistente el estado de cumplimiento de sus clústeres.

El Audit Scanner puede guardar sus resultados ya sea en Definiciones de Recursos Personalizados (CRDs) OpenReports de link:https://openreports.io[openreports.io] (la configuración predeterminada desde v1.33) o PolicyReports del link:https://github.com/kubernetes-sigs/wg-policy-prototypes[Kubernetes policy working group] (marcado como obsoleto desde v1.30, no instalado ni creado por defecto desde v1.30, programado para ser eliminado en una futura versión).

== Instalación

El componente de auditoría está disponible desde {short-project-name} `v1.7.0`.
Por lo tanto, asegúrate de que estás instalando el chart de Helm con la versión de aplicación `v1.7.0` o superior.

. Instala el `kubewarden-crds` chart de Helm. El chart instala por defecto los CRDs necesarios de `PolicyReport`.
+
[subs="+attributes",console]
----
helm install kubewarden-crds kubewarden/kubewarden-crds
----
+

[NOTE]
====
Con Kubewarden 1.33, la función Audit Scanner guarda los informes en los CRDs de OpenReports de [openreports.io](https://openreports.io) por defecto.

Los CRDs de link:https://htmlpreview.github.io/?https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/045372e558b896695b2daae92e8c7a04d4d40282/policy-report/docs/index.html[PolicyReport] del grupo de trabajo de políticas de K8s no están instalados por defecto, están marcados como obsoletos y serán eliminados en una futura versión.

Los usuarios que deseen seguir utilizando los PolicyReports obsoletos, es decir, el comportamiento anterior a 1.33, necesitan: - Cambiar el valor del chart de Helm `kubewarden-crds` de `.Values.install.installPolicyReportCRDs` a `true`. - Cambiar el valor del chart de Helm `kubewarden-controller` de `.Values.auditScanner.reportCRDsKind` de `openreports` a `policyreport`.
====
+
[CAUTION]
====
Para almacenar los resultados de los informes de políticas, necesitas tener disponibles las definiciones de recursos personalizadas (CRDs) de PolicyReport. Si los CRDs de PolicyReport necesarios ya están en el clúster, no puedes instalarlos utilizando el chart kubewarden-crds. En ese caso, puedes desactivar la instalación de los CRDs de OpenReport configurando `installOpenReportCRDs` a `false` en el chart (o `installPolicyReportCRDs` a `false` si utilizas los PolicyReports obsoletos).
Esto significa que la pila de Kubewarden no gestionará esos CRDs, y la responsabilidad es de los administradores.

Consulta más información sobre los CRDs en el link:https://github.com/kubernetes-sigs/wg-policy-prototypes[repositorio del grupo de trabajo de políticas].

====


. Instala el `kubewarden-controller` chart de Helm.
+
[subs="+attributes",console]
----
helm install kubewarden-controller kubewarden/kubewarden-controller
----
+

[NOTE]
====
El escáner de auditoría está habilitado de forma predeterminada. Para desactivarlo, establece el `auditScanner.enable=false`.
====
+
[NOTE]
====
Si deseas que el Escáner de Auditoría guarde sus informes en los CRDs de PolicyReports (marcados como obsoletos) en lugar de los CRDs de OpenReports de forma predeterminada, configura `auditScanner.reportCRDsKind="policyreport"`.
====

Para más información sobre la instalación de {short-project-name}, consulta la xref:quick-start.adoc[Guía de inicio rápido].

De forma predeterminada, la implementación del Escáner de Auditoría es como un https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs[Cron (daemon)] que se activa cada 60 minutos. Puedes ajustar esta y otras configuraciones del escáner de auditoría cambiando el chart kubewarden-controller https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/values.yaml[values.yaml].

Consulta xref:explanations/audit-scanner/audit-scanner.adoc[aquí] más información acerca del Escáner de Auditoría.

=== Policy Reporter UI (opcional)

El chart `kubewarden-controller` viene con un subchart del https://kyverno.github.io/policy-reporter[Policy Reporter]. Está desactivado de forma predeterminada, y se activa configurando `auditScanner.policyReporter=true`. Los valores del subchart de Policy Reporter están bajo la clave `policyReporter` de los valores `kubewarden-controller`.

Esto instala solo una parte del chart upstream de Policy Reporter, la interfaz de usuario, que proporciona una visualización de los PolicyReports y ClusterPolicyReports en un clúster. Consulta xref:explanations/audit-scanner/audit-scanner.adoc[Escáner de Auditoría] para más información sobre la Policy Reporter UI.

Por defecto, la Policy Reporter UI solo se expone como un servicio ClusterIP con el nombre `kubewarden-controller-ui` en el espacio de nombres de instalación de

Se instaló el `kubewarden-controller` chart.

==== Ingress

Los usuarios pueden proporcionar su propia configuración de Ingress, o habilitar un Ingress a través de la configuración del subchart https://github.com/kyverno/policy-reporter/blob/policy-reporter-2.19.4/charts/policy-reporter/charts/ui/values.yaml#L172-L189[aquí].

Consulta este ejemplo de una configuración de Ingress a través del subchart:

[subs="+attributes",yaml]
----
auditScanner:
  policyReporter: true
policy-reporter: # subchart values settings
  ui:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - host: "*.local" # change this to your appropriate domain
          paths:
            - path: /
              pathType: ImplementationSpecific
----

==== Port-forwarding

Para una vista rápida o depuración, se puede configurar una redirección de puertos al servicio con:

[subs="+attributes",console]
----
kubectl port-forward service/kubewarden-controller-ui 8082:8080 -n kubewarden
----

Lo que hace que la Policy Reporter UI esté disponible en `\http://localhost:8082`.

== Ejecutar manualmente

La implementación del escáner de auditoría es como un Cron (daemon) que se ejecuta cada 60 minutos de forma predeterminada. Es posible activar una ejecución manual ejecutando el siguiente comando:

[subs="+attributes",bash]
----
kubectl create job \
    --namespace kubewarden \
    --from cronjob/audit-scanner \
    audit-scanner-manual-$(date +%Y-%m-%d-%H-%M-%S)
----

Puedes comprobar el estado del trabajo con:

[subs="+attributes",console]
----
kubectl get -n kubewarden jobs
----
