include::partial$variables.adoc[]
= {project-name} en un entorno a gran escala
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configura {project-name}s con {project-name} para garantizar alta disponibilidad y rendimiento en entornos a gran escala exigentes.
:keywords: [kubewarden, "{project-name}", kubernetes, policyservers, producciĂ³n]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual del operador, servidores de directivas, producciĂ³n
:sidebar_label: Despliegue a gran escala
:sidebar_position: 21

Esta secciĂ³n detalla un despliegue del mundo real de {project-name} en un entorno a gran escala exigente. Ilustra cĂ³mo configurar {short-project-name} para alta disponibilidad y rendimiento y quĂ© esperar bajo una carga pesada.

[IMPORTANT]
====
Si quieres ver mĂ¡s consejos sobre cĂ³mo ejecutar {short-project-name} en producciĂ³n, consulta la documentaciĂ³n de xref:/howtos/production-deployments.adoc[Despliegues en producciĂ³n].
====

== DescripciĂ³n general del entorno

La infraestructura consiste en aproximadamente 20 clĂºsteres de Kubernetes. Los mĂ¡s grandes de estos clĂºsteres se caracterizan por un tamaĂ±o significativo y un volumen de recursos:

* Nodos: ~400
* Espacios de nombres: ~4,000
* Recursos gestionados:
** Pods: 10.000
** RoleBindings: 13,000
** Ingresses: 12,000
** Despliegues: 8,000
** Servicios: 13,000

== {short-project-name} ConfiguraciĂ³n

Para satisfacer las demandas de este entorno, {short-project-name} estĂ¡ configurado con un enfoque en el aislamiento de cargas de trabajo y alta disponibilidad.

* AplicaciĂ³n de directivas: 22 `ClusterAdmissionPolicies` se aplican en los clĂºsteres, sin `AdmissionPolicies` especĂ­ficos de espacio de nombres.
* Arquitectura del servidor de directivas: Se utilizan dos despliegues separados de `PolicyServer` para aislar cargas de trabajo:
** Una `PolicyServer` estĂ¡ dedicada exclusivamente a directivas sensibles al contexto.
** Una segunda `PolicyServer` maneja todas las demĂ¡s directivas no sensibles al contexto.
* Escalabilidad y recursos:
** RĂ©plicas: Cada despliegue de `PolicyServer` ejecuta 15 rĂ©plicas para manejar el alto volumen de solicitudes.
** AsignaciĂ³n de recursos: A cada rĂ©plica se le asignan 300 MB de memoria y 4 nĂºcleos de CPU.

== MĂ©tricas de rendimiento

Esta configuraciĂ³n gestiona con Ă©xito una alta tasa de solicitudes de admisiĂ³n mientras mantiene un rendimiento predecible.

* Rendimiento de solicitudes de admisiĂ³n: Los clĂºsteres manejan hasta 300 solicitudes de admisiĂ³n por segundo (incluyendo tanto validaciones de webhook como escaneos de auditorĂ­a).
* Latencia de polĂ­ticas:
** Latencia tĂ­pica: Las directivas sensibles al contexto generalmente tardan alrededor de 500 ms en ejecutarse.
** Tiempos lĂ­mite: En este entorno de alto rendimiento, los tiempos de espera de los webhooks estĂ¡n configurados en 2,5 segundos, mientras que el tiempo de espera `PolicyServer` estĂ¡ establecido en 10 segundos. Aunque la mayorĂ­a de las solicitudes son rĂ¡pidas, la infraestructura estĂ¡ diseĂ±ada para manejar operaciones ocasionales lentas sin comprometer la estabilidad del servidor API.

== Rendimiento del escĂ¡ner de auditorĂ­a

El escĂ¡ner de auditorĂ­a se utiliza para garantizar el cumplimiento continuo en el gran nĂºmero de recursos.

* Frecuencia: Se realiza una auditorĂ­a a nivel de clĂºster cada 4 horas.
* ConfiguraciĂ³n: El trabajo de auditorĂ­a estĂ¡ ajustado para un mĂ¡ximo paralelismo para reducir el tiempo de ejecuciĂ³n:

[source,shell]
----
--parallel-namespaces: "10"
--parallel-resources: "20"
--parallel-policies: "20"
--page-size: "1000"
----

* DuraciĂ³n de la auditorĂ­a: Incluso en el clĂºster mĂ¡s grande con decenas de miles de recursos, un trabajo de auditorĂ­a completo se completa en
