include::partial$variables.adoc[]

= Configuración de proxy:
:description: Usando proxies con {project-name}.
:keywords: ["{project-name}", "kubewarden", "kubernetes", "proxy", "proxies"]
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-type: ["howto"]
:doc-topic: ["operator-manual", "proxy"]

Para ambos, `kwctl` y `policy-server`, puedes configurar proxies HTTP y HTTPS, así como eximir dominios de esta configuración de proxy.

Puedes hacerlo de dos maneras: * Estableciendo las variables de entorno `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` (y sus equivalentes en minúsculas) para `kwctl` o `policy-server`.
  Para configurar un CR de PolicyServer, establece su array `spec.env`. * Proporcionando un archivo `sources.yaml` a través del argumento `--sources-path`.
  Un archivo `sources.yaml` tiene prioridad sobre las variables de entorno.
  Consumir esta configuración a través del campo `spec` aún no está expuesto en los CR de PolicyServer.

Establecer una configuración de proxy influye en:

* La extracción, el envío y la ejecución en modo pull-and-run de políticas desde y hacia el registro OCI.
* Capacidades del host desde llamadas contextuales, tales como:
** Registro de contenedores, como obtener un manifiesto OCI o un resumen del manifiesto.
   En lugar de acceder directamente al registro OCI, el tráfico será dirigido a través de los proxies configurados.
** Capacidades de Sigstore, como verificar una firma sin clave.
   En lugar de acceder a los servicios definidos por Sigstore, el tráfico será dirigido a través de los proxies configurados.

== Ejemplo

Puedes establecer las siguientes variables de entorno, para `kwctl` o `policy-server` (a través del PolicyServer `spec.env`):

[source,bash]
----
HTTP_PROXY="http://proxy.corp:3128"
https_proxy="http://proxy.corp:3129"
NO_PROXY="localhost,.corp"
----

Con esta configuración: * El tráfico no seguro a través de HTTP, como el que va y viene de un registro OCI no seguro, se dirige a través de `\http://proxy.corp:3128`.
  Esto afecta a la obtención de políticas y a las políticas que llaman a capacidades contextuales que tienen resúmenes de manifiestos de imágenes OCI para contenedores en ese repositorio. * El tráfico cifrado a través de HTTPS se dirige a través de `\https://proxy.corp:3129`.
  Por ejemplo, esto incluye la obtención y envío de políticas a cualquier registro OCI seguro, y las mencionadas capacidades contextuales de las políticas. * El tráfico hacia y desde localhost o cualquier dominio bajo `.corp` está exento de las configuraciones anteriores.


== El archivo `sources.yaml`

Para más detalles, consulta la referencia xref:/reference/sources_yaml.adoc[`sources.yaml`].