include::partial$variables.adoc[]
= Capacités d'hôte de Sigstore
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Apprenez à mettre en œuvre les capacités d'hôte de Sigstore en utilisant des stratégies CEL dans Kubewarden pour vérifier les images de conteneurs et appliquer un contrôle d'admission sécurisé.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "rédaction de politiques", "cel", "sigstore", "signature", "vérification"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "rédaction de politiques", "sigstore", "signature", "vérification"]
:sidebar_label: Capacités d'hôte de Sigstore
:current-version: {page-origin-branch}

À titre d'exemple d'une autre utilisation des capacités d'hôte sur `cel-policy` de Kubewarden, créons une stratégie qui vérifie toutes les images de conteneurs dans un Pod en vérifiant leurs signatures sans clé Sigstore.

== Exemple : Stratégie de vérification Sigstore

Cette stratégie vérifiera toutes les images de conteneurs dans le Pod Sigstore et s'assurera que les images sont signées et de confiance.

Dans ce cas, nous vérifierons une signature sans clé Sigstore effectuée dans GitHub Actions. Ces types de signatures sans clé sont liés à l'émetteur OIDC de GitHub lors de la création des certificats cryptographiques, donc nous n'aurons besoin que de connaître l'organisation GitHub sous laquelle l'image de conteneur est publiée. Vous pouvez en savoir plus sur les capacités d'hôte pour Sigstore xref:reference/spec/host-capabilities/02-signature-verifier-policies.adoc[ici].

Pour réaliser cela en CEL, nous utilisons les https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[bibliothèques d'extension CEL de {project-name} pour les capacités d'hôte] dans la stratégie, en particulier la https://pkg.go.dev/github.com/kubewarden/cel-policy/internal/cel/library#Sigstore[fonction `githubAction`].

Comme toujours, nous pouvons commencer par `kwctl` :

[subs="+attributes",console]
----
$ kwctl scaffold manifest -t ClusterAdmissionPolicy \
  registry://ghcr.io/kubewarden/policies/cel-policy:v1.0.0`
----

Que nous pouvons ensuite modifier pour qu'il soit pertinent pour notre stratégie de vérification des conteneurs :

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
----

Maintenant, passons à la partie CEL. Nous allons obtenir une liste d'images de conteneurs dans l'objet Pod actuel, puis vérifier qu'elles sont vérifiées par une signature correspondant à notre organisation choisie (dans ce cas, github.com/opencontainers) :

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
  settings:
    variables:
      - name: containerImages
        expression: |
          object.spec.containers.map(c, c.image)
      - name: containerImagesNotVerified
        expression: |
          variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted())
    validations:
      - expression: |
          size(variables.containerImagesNotVerified) == 0
        messageExpression: "'These container images are not signed by the kubewarden GitHub organization: ' + variables.containerImagesNotVerified.join(', ')"
----

Mais attendez, nous ne devons pas oublier que les InitContainers peuvent également faire partie des Pods. Ajoutons donc une autre variable et validation :

```yaml title="./cel-policy-sigstore.yaml"
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
  settings:
    variables:
      - name: containerImages
        expression: |
          object.spec.containers.map(c, c.image)
      - name: initContainerImages
        expression: |
          has(object.spec.initContainerImages) ? object.spec.initContainers.map(c, c.image) : []
      - name: containerImagesNotVerified
        expression: |
          variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted())
      - name: initContainerImagesNotVerified
        expression: |
          variables.initContainerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted())
    validations:
      - expression: |
          size(variables.containerImagesNotVerified) == 0
        messageExpression: "'Ces images de conteneurs ne sont pas signées par l'organisation GitHub kubewarden : ' + variables.containerImagesNotVerified.join(', ')"
      - expression: |
          size(variables.initContainerImagesNotVerified) == 0
        messageExpression: "'Ces images de conteneurs init ne sont pas signées par l'organisation GitHub kubewarden : ' + variables.initContainerImagesNotVerified.join(', ')"
```

As usual with CEL, we can add several `validations` under
`settings.validations`, and they are evaluated in parallel, joined with an AND
operation, which is short-circuited.

We can now deploy the policy, and try to deploy a Pod with unsigned images:

```console
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: golanci-lint-example
spec:
  containers:
  - name: nginx
    image: ghcr.io/opencontainers/golangci-lint:v1.52.1
    ports:
    - containerPort: 80
EOF
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-cel-sigstore-keyless-verification.kubewarden.admission" denied the request:
  failed to verify image: Callback evaluation failure: no signatures found for image: ghcr.io/opencontainers/golangci-lint:v1.52.1
```
