include::partial$variables.adoc[]
= Distribution d'une stratégie de Gatekeeper avec {project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Distribuez les stratégies de Gatekeeper à travers les clusters Kubernetes en annotant les fichiers de stratégie avec des métadonnées et en les déployant via ClusterAdmissionPolicy.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "gatekeeper", "rego"]
:current-version: {page-origin-branch}

Les stratégies doivent être annotées pour être poussées, et finalement exécutées par le {project-name} `policy-server` dans un cluster Kubernetes.

Annoter et distribuer une stratégie de Gatekeeper est similaire à distribuer une stratégie d'Open Policy Agent.

== Annotation de la stratégie

Vous allez écrire un fichier `metadata.yaml` dans votre répertoire de stratégie avec le contenu suivant :

[subs="+attributes",yaml]
----
rules:
- apiGroups: [""]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["CREATE"]
mutating: false
contextAware: false
executionMode: gatekeeper
annotations:
  io.kubewarden.policy.title: no-default-namespace
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: This policy will reject any resource created inside the default namespace
  io.kubewarden.policy.author: The {short-project-name} Authors
  io.kubewarden.policy.url: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.source: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
      This policy is just an example.

      You can write interesting descriptions about the policy here.
----

Vous pouvez constater que tout est identique aux métadonnées de la version Open Policy Agent, sauf pour le bit `executionMode: gatekeeper`.

Allez-y et annotez la stratégie :

[subs="+attributes",console]
----
$ kwctl annotate policy.wasm --metadata-path metadata.yaml --output-path annotated-policy.wasm
----

== Pousser la stratégie

Poussez votre stratégie vers un registre OCI :

[subs="+attributes",console]
----
$ kwctl push annotated-policy.wasm registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
Policy successfully pushed
----

== Déploiement sur Kubernetes

Vous devez d'abord tirer votre stratégie dans votre dépôt local `kwctl` :

[subs="+attributes",console]
----
$ kwctl pull registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
pulling policy...
----

Vous pouvez maintenant créer une ressource de scaffold `ClusterAdmissionPolicy`:

[subs="+attributes",console]
----
$ kwctl scaffold manifest registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1 --type ClusterAdmissionPolicy
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Utilisez maintenant cette ressource `ClusterAdmissionPolicy` pour déployer votre stratégie sur un cluster Kubernetes.
