include::partial$variables.adoc[]
= Richtlinientests
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-06-18
:page-revdate: {revdate}
:description: Erfahren Sie, wie Sie {admc-name} Richtlinien mit {admc-name} für eine sichere Clusterverwaltung erstellen und testen können.
:doc-persona: ["kubewarden-operator", "kubewarden-policy-developer"]
:doc-topic: ["testing-policies", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "personen", "richtlinienautor", "Clusterbetreiber"]
:sidebar_label: Richtlinientests
:current-version: {page-origin-branch}

== Richtlinientests-Personas

Dieser Abschnitt behandelt das Thema des Testens von {admc-name} Richtlinien.
Es gibt zwei Personas, die daran interessiert sind, Richtlinien zu testen:

* *Richtlinienentwickler*: Sie schreiben eine {admc-short-name} Richtlinie und möchten sicherstellen, dass Ihr Code sich so verhält, wie Sie es erwarten.
* *Clusterbetreiber*: Sie haben eine {admc-short-name} Richtlinie gefunden und möchten die Richtlinieneinstellungen testen und anpassen, bevor Sie sie bereitstellen.
Sie möchten diese Einstellungen weiterhin in Ihren CI/CD-Pipelines und anderen administrativen Aufgaben testen.

Die nächsten Abschnitte der Dokumentation zeigen, wie diese Personas {admc-short-name} Richtlinien testen können.
