include::partial$variables.adoc[]

= Haulerを使用したエアギャップ環境でのインストール
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Haulerを使用して、エアギャップ(された)環境に{project-name}をインストールします。
:keywords: ["{project-name}", Kubewarden, kubernetes, エアギャップインストール, Hauler]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: HOWTO(操作方法)
:doc-topic: オペレーターマニュアル, エアギャップ, インストール, Hauler

このガイドでは、link:https://docs.hauler.dev/docs/intro[Hauler]を使用してエアギャップ(された)環境に{project-name}をインストールする方法を示します。Haulerは、ユーザーがエアギャップ(された)環境でワークロードを実行するのを支援するツールです。アプリに必要なリソースをエアギャップ(された)環境に移動します。

{short-project-name}は、プライベート環境で{short-project-name}を実行するために必要なすべてのリソースを含むマニフェストファイルを提供します。このドキュメントでは、どのようにそれを使用できるかを説明します。Haulerのドキュメントを参照して、詳細を学んでください。

Haulerマニフェストを使用した基本的なワークフローは次のとおりです：

. {short-project-name}のリリースページから取得します。
. {short-project-name}を実行するために必要なすべてのリソースをローカルストアにロードします。
. それらをファイルにエクスポートします。
. ファイルをプライベート環境に移動します。
. プライベート環境内で実行されているHaulerにリソースをロードします。
. インストールプロセスで使用するために、すべてをエアギャップ(された)環境内のレジストリにコピーします。

== HelmチャートのリリースページからHaulerマニフェストをダウンロードします。

{short-project-name}link:https://github.com/kubewarden/helm-charts/releases/[リリースページ]から`hauler_manifest.yml`をダウンロードします。

マニフェストに定義されたリソースをHaulerストアに同期します：

[source,shell]
----
hauler store sync --filename hauler_manifest.yaml
----

Haulerはマニフェストからすべてのリソースをローカルストアにダウンロードします。このプロセスには数分かかります。完了すると、`hauler store info`コマンドで同期されたリソースを確認できます。

== すべての{short-project-name}リソースを含むtarファイルを生成します。

Haulerコマンドを実行して、ストアに以前ロードされたすべてのリソースをファイルにエクスポートします：

[source,shell]
----
hauler store save --filename kubewarden-resources.tar.zst
----

[NOTE]
====

{short-project-name}コンテナイメージはx86_64およびArm®アーキテクチャをサポートしています。したがって、リソースをファイルに保存するときに、このような警告メッセージが表示されることがあります：

[source,shell]
----
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kyverno/policy-reporter:3.3.3]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kyverno/policy-reporter-ui:2.4.1]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/policy-server:v1.27.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/audit-scanner:v1.27.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/rancher/kuberlr-kubectl:v5.0.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/kubewarden-controller:v1.27.0]
----

この警告メッセージを回避するには、`--platform` CLIフラグを設定して、ファイルに保存したいプラットフォームアーキテクチャを定義できます。

====

== tarファイルを隔離された環境に転送します。

{short-project-name}リソースがすべて`kubewarden-resources.tar.zst`にあるので、エアギャップ(された)環境にコピーし、そこでHaulerストアにロードします：

[source,shell]
----
hauler store load --filename kubewarden-resources.tar.zst
# Check if the resources are loaded
hauler store info
----

これで、{short-project-name}をインストールするために必要なすべてのリソースが、隔離された環境のHaulerストアにあります。

== プライベートレジストリに投入します

Haulerストアのリソースを使用するには、それらを内部レジストリで利用可能にする必要があります。Haulerコマンドを使用して、それらをプライベートレジストリにコピーできます。

[source,shell]
----
hauler store copy registry://localhost:5000
----

Haulerを実行して、ストアからすべてのリソースを持つレジストリを開始することもできます。このレジストリは安全ではないため、クラスターの設定を変更する必要があります：

[source,shell]
----
# Find IP address of your host
# hostname -I

# Update registries.yaml for k3s based cluster to allow insecure access
# mirrors:
#   "<HOST_IP>:5000":
#     endpoint:
#       - "http://<HOST_IP>:5000"
# configs:
#   "<HOST_IP>:5000":
#     tls:
#       insecure_skip_verify: true

# Configure policy-server to allow pulling policies from insecure sources
# helm install .. kubewarden-defaults .. --set policyServer.insecureSources[0]=<HOST_IP:5000>

hauler store serve registry
----

これにより、`localhost:5000`アドレスでレジストリが開始されます。この時点から、Skopeoのような他のコマンドを使用して、{short-project-name}によって使用されるすべてのコンテナイメージ、ポリシーモジュール、およびHelmチャートをプライベートレジストリにコピーできます。

== {short-project-name}をインストールします

プライベートレジストリに必要なすべてのものが揃ったので、{short-project-name}をインストールできます。標準の{short-project-name}インストールとの違いは、コンテナイメージとポリシーのレジストリをプライベートレジストリに変更する必要があることです。さらに、OCIアーティファクトからHelmチャートをインストールする必要があります。

{short-project-name}スタックをインストールします：

[source,shell]
----
helm install --wait -n kubewarden kubewarden-crds --create-namespace \
    oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-crds
helm install --wait -n kubewarden kubewarden-controller \
    --set "global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>" \
    oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-controller
----

[CAUTION]
====

`kubewarden-controller`チャートで利用可能なPolicyReporterサブチャートを使用するには、エアギャップ(された)環境でサブチャートに特有の他の値を定義する必要があります。以下に例を示します：

[source,shell]
----
helm install --wait -n kubewarden kubewarden-controller oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-controller \
    --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set auditScanner.policyReporter=true \
    --set policy-reporter.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.image.repository=kyverno/policy-reporter \
    --set policy-reporter.ui.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.ui.image.repository=kyverno/policy-reporter-ui
----

サブチャートを有効にし、Policy Reporterイメージストアの場所でレジストリとリポジトリを構成するために、`auditScanner.policyReporter`と他の4つの値を定義する必要があります。ポリシーレポートサブチャートの値に関する詳細については、\link:https://kyverno.github.io/policy-reporter-docs/getting-started/helm.html[Policy Reporterのドキュメント]を参照してください。

====

[source,shell]
----
helm install --wait -n kubewarden \
  kubewarden-defaults oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-defaults \
  --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>
----

最後に、各ポリシーサーバーを設定して、プライベートレジストリからポリシーを取得する必要があります。ドキュメントのxref:/howtos/policy-servers/02-private-registry.adoc[プライベートレジストリの使用]セクションを参照してください。

これで、クラスター内に{short-project-name}ポリシーを作成できます。ポリシーは、プライベートレジストリで利用可能でなければなりません。

[source,yaml]
----
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://<REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policies/pod-privileged:v0.2.2
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
  mutating: false
EOF
----

[CAUTION]
====

`PolicyServer`リソースは、プライベートレジストリで利用可能なイメージを使用する必要があります。
次に例を示します。

[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: reserved-instance-for-tenant-a
spec:
  image: <REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policy-server:v1.3.0
  replicas:
----

====