include::partial$variables.adoc[]
= Grupos de polĂ­ticas
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Saiba como criar polĂ­ticas complexas combinando polĂ­ticas mais simples por meio de Grupos de PolĂ­ticas, especificamente usando as definiĂ§Ă”es de AdmissionPolicyGroup e ClusterAdmissionPolicyGroup.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["explanations", "policy-group"]
:doc-type: ["explanation"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "grupos de polĂ­ticas", "grupo de polĂ­tica de admissĂŁo de cluster", "grupo de polĂ­tica de admissĂŁo"]
:sidebar_label: Grupos de polĂ­ticas
:sidebar_position: 21
:current-version: {page-origin-branch}

O recurso de grupo de polĂ­ticas permite que os usuĂĄrios criem polĂ­ticas complexas combinando polĂ­ticas mais simples. Ele introduz duas novas DefiniĂ§Ă”es de Recursos Personalizados (CRDs):

* `AdmissionPolicyGroup`: para polĂ­ticas de admissĂŁo que se aplicam a namespaces especĂ­ficos.
* `ClusterAdmissionPolicyGroup`: para polĂ­ticas de admissĂŁo que se aplicam a todo o cluster.

Esses grupos de polĂ­ticas permitem que os usuĂĄrios utilizem polĂ­ticas existentes, reduzindo a necessidade de criaĂ§ĂŁo de polĂ­ticas personalizadas e aumentando a reutilizaĂ§ĂŁo. Ao evitar a duplicaĂ§ĂŁo da lĂłgica de polĂ­ticas, os usuĂĄrios podem simplificar a gestĂŁo e criar polĂ­ticas personalizadas com uma configuraĂ§ĂŁo semelhante a DSL.

Os grupos de polĂ­ticas permitem a avaliaĂ§ĂŁo combinada de mĂșltiplas polĂ­ticas usando operadores lĂłgicos. Isso permite a definiĂ§ĂŁo de lĂłgica complexa. No entanto, enquanto polĂ­ticas comuns podem incluir lĂłgica de mutaĂ§ĂŁo para modificar recursos durante a admissĂŁo, grupos de polĂ­ticas apenas realizam validaĂ§ĂŁo.

A configuraĂ§ĂŁo para grupos de polĂ­ticas Ă© semelhante Ă  das polĂ­ticas comuns. A diferenĂ§a Ă© a adiĂ§ĂŁo dos campos `expression`, `message` e `policies`, e a declaraĂ§ĂŁo de regras contextuais em um local diferente.

Este Ă© um exemplo de um `ClusterAdmissionPolicyGroup` que vocĂȘ pode usar nas prĂłximas seĂ§Ă”es para explicar os diferentes campos:

.Um `ClusterAdmissionPolicyGroup` que rejeita Pods que usam imagens com a tag `latest`, a menos que as imagens sejam assinadas por duas partes confiĂĄveis: Alice e Bob.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  policies:
    signed_by_alice:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
                yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
                -----END PUBLIC KEY-----
    signed_by_bob:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X
                urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==
                -----END PUBLIC KEY-----
    reject_latest:
      module: registry://ghcr.io/kubewarden/policies/trusted-repos:v0.2.0
      settings:
        tags:
          reject:
            - latest
  expression: "reject_latest() || (signed_by_alice() && signed_by_bob())"
  message: "the image is using the latest tag or is not signed by Alice and Bob"
----
======

== Campos de configuraĂ§ĂŁo principais

Esta seĂ§ĂŁo abrange os principais campos de configuraĂ§ĂŁo de um grupo de polĂ­ticas.

=== O atributo `policies`

O campo de polĂ­ticas Ă© um mapa de polĂ­ticas comuns. {project-name} chama polĂ­ticas pelo grupo de polĂ­ticas, para determinar se aceita ou rejeita o recurso em avaliaĂ§ĂŁo. As definiĂ§Ă”es dessas polĂ­ticas sĂŁo uma versĂŁo simplificada das polĂ­ticas comuns {short-project-name}, contendo apenas os atributos `module`, `settings` e `contextAwareResources`. Esses elementos sĂŁo necessĂĄrios para que as polĂ­ticas funcionem dentro de um grupo de polĂ­ticas.

Um nome Ășnico identifica cada polĂ­tica do grupo de polĂ­ticas. Por exemplo, o seguinte trecho define trĂȘs polĂ­ticas: `signed_by_alice`, `signed_by_bob` e `reject_latest_tag`.

[,yaml]
----
policies:
  signed_by_alice:
    module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
    settings: {} # settings for the policy
  signed_by_bob:
    module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
    settings: {} # settings for the policy
  reject_latest_tag:
    module: ghcr.io/kubewarden/policies/trusted-repos-policy:v0.2.0
    settings: {} # settings for the policy
----

[TIP]
====

Um grupo de polĂ­ticas pode incluir a mesma polĂ­tica vĂĄrias vezes com configuraĂ§Ă”es diferentes.

====


=== O atributo `expression`

O atributo `expression` contĂ©m uma declaraĂ§ĂŁo composta pelos identificadores de polĂ­tica unidos por operadores lĂłgicos.

A avaliaĂ§ĂŁo da declaraĂ§ĂŁo `expression` deve resultar em um valor booleano.

A representaĂ§ĂŁo das polĂ­ticas Ă© feita como uma funĂ§ĂŁo nomeada de acordo com o identificador especificado no mapa `.spec.policies`. Os resultados produzidos pela avaliaĂ§ĂŁo das polĂ­ticas sĂŁo entĂŁo avaliados usando os operadores lĂłgicos fornecidos pelo usuĂĄrio.

Estes sĂŁo os operadores suportados:

* `&&`: usado para realizar operaĂ§Ă”es de `AND`
* `||`: usado para realizar operaĂ§Ă”es de `OR`
* `!`: usado para realizar operaĂ§Ă”es de `NOT`

VocĂȘ pode usar parĂȘnteses `( )` para definir prioridades de avaliaĂ§ĂŁo.

Por exemplo, dada a seguinte expressĂŁo:

[,console]
----
reject_latest() || (signed_by_alice() && signed_by_bob())
----

A polĂ­tica rejeita cargas de trabalho que possuem imagens usando a tag `latest`, a menos que tanto Alice quanto Bob tenham assinado as imagens.

=== O atributo `message` e o formato da resposta

O campo `message` especifica a mensagem retornada quando a avaliaĂ§ĂŁo de `expression` resulta em uma rejeiĂ§ĂŁo. A resposta inclui a mensagem, juntamente com os resultados da avaliaĂ§ĂŁo das polĂ­ticas individuais.

[IMPORTANT]
====

A avaliaĂ§ĂŁo das polĂ­ticas que pertencem ao grupo ocorre apenas se necessĂĄrio.

Por exemplo, dada a seguinte expressĂŁo:

[,console]
----
reject_latest() || (signed_by_alice() && signed_by_bob())
----

As polĂ­ticas `signed_by_bob` e `signed_by_alice` nĂŁo sĂŁo avaliadas quando a polĂ­tica `reject_latest` retorna `true`.

Da mesma forma, a polĂ­tica `signed_by_bob` nĂŁo Ă© avaliada se as polĂ­ticas `signed_by_alice` e `reject_latest` retornam `false`.

Isso evita avaliaĂ§Ă”es desnecessĂĄrias de polĂ­ticas no grupo e garante respostas rĂĄpidas Ă s solicitaĂ§Ă”es de admissĂŁo.

====

O sistema envia todos os detalhes da avaliaĂ§ĂŁo das polĂ­ticas do grupo como parte da AdmissionResponse `.status.details.causes` quando uma polĂ­tica de grupo realiza uma rejeiĂ§ĂŁo.

VocĂȘ pode obter detalhes completos de uma solicitaĂ§ĂŁo de admissĂŁo rejeitada aumentando o nĂ­vel de verbosidade de `kubectl`:

[,shell]
----
kubectl -v4 apply -f signed-pod.yml
I0919 18:29:40.251332    4330 helpers.go:246] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"signed-pod.yml\": admission webhook \"clusterwide-demo.kubewarden.admission\" denied the request: the image is using the latest tag or is not signed by Alice and Bob",
  "details": {
    "causes": [
      {
        "message": "Resource signed is not accepted: verification of image testing.registry.svc.lan/busybox:latest failed: Host error: Callback evaluation failure: Image verification failed: missing signatures\nThe following constraints were not satisfied:\nkind: pubKey\nowner: null\nkey: |\n  -----BEGIN PUBLIC KEY-----\n  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X\n  urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==\n  -----END PUBLIC KEY-----\nannotations: null\n",
        "field": "spec.policies.signed_by_bob"
      },
      {
        "message": "not allowed, reported errors: tags not allowed: latest",
        "field": "spec.policies.reject_latest"
      }
    ]
  },
  "code": 400
}]
Error from server: error when creating "signed-pod.yml": admission webhook "clusterwide-demo.kubewarden.admission" denied the request: the image is using the latest tag or is not signed by Alice and Bob
----

A resposta completa de admissĂŁo estĂĄ disponĂ­vel nos logs do Policy Server quando executado em modo de remover. AlĂ©m disso, os detalhes da avaliaĂ§ĂŁo sĂŁo sempre parte dos rastros do OpenTelemetry emitidos pelo Servidor de PolĂ­ticas.

== PolĂ­ticas Contextuais

Outra distinĂ§ĂŁo entre grupos de polĂ­ticas e polĂ­ticas comuns Ă© a localizaĂ§ĂŁo da definiĂ§ĂŁo das regras de recursos contextuais. Cada polĂ­tica em um grupo aceita um campo opcional `contextAwareResources` para especificar os recursos que a polĂ­tica pode acessar durante a avaliaĂ§ĂŁo. Assim como nas polĂ­ticas comuns, vocĂȘ sĂł pode usar as capacidades contextuais definindo um `ClusterAdmissionPolicyGroup`. Isso Ă© por razĂ”es de seguranĂ§a, pois apenas usuĂĄrios nĂŁo privilegiados podem implantar recursos `AdmissionPolicyGroup`. Para mais detalhes, consulte a documentaĂ§ĂŁo das xref:explanations/context-aware-policies.adoc[polĂ­ticas contextuais].

.Um exemplo de um grupo de polĂ­ticas que utiliza uma polĂ­tica contextual.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo-ctx-aware
spec:
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - services
      operations:
        - CREATE
        - UPDATE
  policies:
    unique_service_selector:
      module: registry://ghcr.io/kubewarden/policies/unique-service-selector-policy:v0.1.0
      contextAwareResources:
        - apiVersion: v1
          kind: Service
      settings:
        app.kubernetes.io/name: MyApp
    owned_by_foo_team:
      module: registry://ghcr.io/kubewarden/policies/safe-annotations:v0.2.9
      settings:
        mandatory_annotations:
          - owner
        constrained_annotations:
          owner: "foo-team"
  expression: "unique_service_selector() || (!unique_service_selector() && owned_by_foo_team())"
  message: "the service selector is not unique or the service is not owned by the foo team"
----
======

No exemplo anterior, a polĂ­tica `unique_service_selector` pode acessar o recurso `Service`. No entanto, o `owned_by_foo_team` nĂŁo tem acesso aos recursos do Kubernetes.

== ValidaĂ§ĂŁo de ConfiguraĂ§Ă”es

Quando o servidor de polĂ­ticas inicia, ele valida as configuraĂ§Ă”es tanto dos grupos de polĂ­ticas quanto das polĂ­ticas comuns. No entanto, os grupos de polĂ­ticas passam por uma etapa de validaĂ§ĂŁo adicional para verificar se a expressĂŁo Ă© vĂĄlida e avalia para um valor booleano.

== Scanner de Auditoria

Semelhante aos CRDs AdmissionPolicy e ClusterAdmissionPolicy, o campo `backgroundAudit` indica se deve incluir o grupo de polĂ­ticas durante as xref:../explanations/audit-scanner/audit-scanner.adoc[verificaĂ§Ă”es de auditoria].

== Servidor de PolĂ­ticas

VocĂȘ pode estender o arquivo de configuraĂ§Ă”es `policies.yml` para incluir grupos de polĂ­ticas junto com polĂ­ticas comuns. Assim como nas polĂ­ticas comuns, o download de mĂłdulos ocorre uma vez. VocĂȘ usa o mesmo mĂłdulo de polĂ­tica tanto em um grupo de polĂ­ticas quanto em uma polĂ­tica comum.
