include::partial$variables.adoc[]
= Migrando PolûÙticas do Gatekeeper para {project-name}
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-04-30
:page-revdate: {revdate}
:description: Configure uma polûÙtica {project-name} migrando uma polûÙtica existente do Gatekeeper atravûˋs de duas etapas principais: compilando o cû°digo Rego em WebAssembly.
:keywords: ["{project-name}", kubewarden, gatekeeper]
:doc-persona:
  [kubewarden-operator, kubewarden-integrator, kubewarden-policy-developer]
:doc-type: [howto]
:doc-topic: [operator-manual]

Este guia mostra como converter uma polûÙtica existente do Gatekeeper em uma polûÙtica {project-name}. Este processo envolve duas etapas principais:
. Compile o programa Rego em um mû°dulo WebAssembly (Wasm).
. Distribua o mû°dulo WebAssembly como uma polûÙtica {short-project-name}.

O tutorial de polûÙticas xref:/tutorials/writing-policies/rego/01-intro-rego.adoc[Rego] cobre a maior parte do processo de construûÏûÈo para compilar o cû°digo Rego em um mû°dulo WebAssembly. Este guia foca no processo passo a passo de extrair as DefiniûÏûçes de Recursos Personalizados (CRDs) do Gatekeeper e migrûÀ-las para uma polûÙtica {short-project-name} funcional. Ele utiliza uma polûÙtica de demonstraûÏûÈo bûÀsica do Gatekeeper.

== Prûˋ-requisitos

* link:https://github.com/open-policy-agent/opa/releases[opa]: vocûˆ usa esta ferramenta para compilar o cû°digo em wasm. Este guia foi escrito usando a versûÈo `v1.5.1`.
* link:https://github.com/kubewarden/kwctl/releases[`kwctl`]: ferramenta que vocûˆ usa para preparar e executar o mû°dulo de WebAssembly {short-project-name}.
* link:https://github.com/bats-core/bats-core[`bats`]: ferramenta usada para executar testes de ponta a ponta. Se vocûˆ decidir escrever esse tipo de teste
* link:https://github.com/mikefarah/yq[`yq`]: ferramenta usada para extrair dados de arquivos yaml.

== Antes de migrar suas polûÙticas

Antes de iniciar o processo de migraûÏûÈo das polûÙticas do Gatekeeper, considere usar polûÙticas jûÀ disponûÙveis no {short-project-name} link:https://artifacthub.io/packages/search?kind=13[catalog]. Algumas das link:https://github.com/kubewarden/rego-policies-library[polûÙticas] sûÈo polûÙticas OPA e Gatekeeper publicamente disponûÙveis migradas para {short-project-name}.

Alûˋm disso, dûˆ uma olhada na nossa documentaûÏûÈo de xref:/explanations/comparisons/opa-comparison.adoc[comparaûÏûÈo] entre {short-project-name} e Gatekeeper.

== Etapa 1: Inicialize seu projeto de polûÙtica {short-project-name}

Primeiro, use o Gatekeeper {short-project-name}
link:https://github.com/kubewarden/gatekeeper-policy-template[modelo] para criar
uma estrutura bûÀsica de projeto de polûÙtica. Isso fornece alvos Makefile para construir
e testar sua polûÙtica. Apû°s criar o cû°digo da polûÙtica a partir do modelo,
execute os comandos do Makefile para verificar se a polûÙtica ûˋ construûÙda e os testes sûÈo executados
com sucesso:

[source,console]
----
$ make policy.wasm test
opa build -t wasm -e policy/violation -o bundle.tar.gz policy.rego
tar xvf bundle.tar.gz /policy.wasm
tar: Removing leading `/' from member names
/policy.wasm
rm bundle.tar.gz
touch policy.wasm # opa creates the bundle with unix epoch timestamp, fix it
opa test *.rego
PASS: 2/2
----

== Etapa 2: Migrar o cû°digo da polûÙtica do Gatekeeper

Agora, comece a migrar a polûÙtica do Gatekeeper. Isso envolve converter um
`ConstraintTemplate` e seus recursos associados `Constraint` em uma polûÙtica {short-project-name}. Em um contexto {short-project-name}, considere o `ConstraintTemplate` como o cû°digo kernel da polûÙtica, enquanto as instûÂncias `Constraint` se traduzem em instûÂncias de polûÙtica executando dentro de {short-project-name}.

Primeiro, copie o cû°digo Rego do seu `ConstraintTemplate` para o arquivo `policy.rego` que foi gerado pelo template {short-project-name}. Para este exemplo, vocûˆ deve usar a seguinte polûÙtica de demonstraûÏûÈo link:https://github.com/open-policy-agent/gatekeeper/blob/896d6620f9c16d7a5d91a74a6a4260db8d735640/demo/basic/demo.sh#L1[demo policy] do repositû°rio do Gatekeeper.

[.details]
.YAML da polûÙtica do Gatekeeper
[%collapsible]
====
[source,yaml]
----
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabels
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabels
      validation:
        # Schema for the `+parameters+` field
        openAPIV3Schema:
          type: object
          properties:
            labels:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabels

        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          provided := {label | input.review.object.metadata.labels[label]}
          required := {label | label := input.parameters.labels[_]}
          missing := required - provided
          count(missing) > 0
          msg := sprintf("you must provide labels: %v", [missing])
        }
----
====

Copie o trecho de cû°digo Rego do campo `rego` para o seu arquivo `policy.rego`:

[source,console]
----
cat gatekeeper/demo/basic/templates/k8srequiredlabels_template.yaml | yq ".spec.targets[0].rego" > policy.rego
----

=== Adaptar o cû°digo Rego para {short-project-name}

Vocûˆ precisa garantir que o nome `package` usado dentro do cû°digo Rego seja `policy`.
Este ûˋ o valor esperado em muitos lugares pelo modelo do Gatekeeper {short-project-name}.

Se vocûˆ nûÈo alterûÀ-lo, terûÀ erros ao construir a polûÙtica e executar seus testes de ponta a ponta.

Por exemplo, a polûÙtica de demonstraûÏûÈo que estamos convertendo estûÀ definida dentro do pacote `k8srequiredlabels`, esse valor deve ser alterado para `policy`.

û assim que o conteû¤do do arquivo `policy.rego` deve ser:

[source,rego]
----
package policy

violation[{"msg": msg, "details": {"missing_labels": missing}}] {
provided := {label | input.review.object.metadata.labels[label]}
required := {label | label := input.parameters.labels[_]}
missing := required - provided
count(missing) > 0
msg := sprintf("you must provide labels: %v", [missing])
}
----

Tentar construir o cû°digo apû°s essa alteraûÏûÈo pode revelar novos erros de compilaûÏûÈo:

[source,console]
----
opa build -t wasm -e policy/violation -o bundle.tar.gz policy.rego
error: load error: 2 errors occurred during loading:
policy.rego:3: rego_parse_error: `+if+` keyword is required before rule body
policy.rego:3: rego_parse_error: `+contains+` keyword is required for partial set rules
make: *** [Makefile:4: policy.wasm] Error 1
----

O autor da polûÙtica deve corrigir esses erros para permitir que o CLI `opa` construa o
cû°digo com sucesso. As mudanûÏas especûÙficas podem variar dependendo da versûÈo `opa` e do cû°digo de polûÙtica original. Como estamos migrando uma polûÙtica rego anterior ao OPA v1, precisamos atualizar o cû°digo para ser compatûÙvel com a v1. O cû°digo final `policy.rego` fica assim:

[source,rego]
----
package policy

violation contains {"msg": msg, "details": {"missing_labels": missing}} if {
  provided := {label | input.review.object.metadata.labels[label]}
  required := {label | label := input.parameters.labels[_]}
  missing := required - provided
  count(missing) > 0
  msg = sprintf("you must provide labels: %v", [missing])
}
----

Depois de ajustar o cû°digo, construa a polûÙtica:

[source,console]
----
$ make policy.wasm
opa build -t wasm -e policy/violation -o bundle.tar.gz policy.rego
tar xvf bundle.tar.gz /policy.wasm
tar: Removing leading `/' from member names
/policy.wasm
rm bundle.tar.gz
touch policy.wasm # opa creates the bundle with unix epoch timestamp, fix it
----

HûÀ mais informaûÏûçes sobre como construir polûÙticas do Gatekeeper em nosso xref:/tutorials/writing-policies/rego/gatekeeper/03-build-and-run.adoc[tutorial].

=== Cû°digo da polûÙtica Rego e compatibilidade com OPA v1.0.0

Com o lanûÏamento do OPA (Agente de PolûÙtica Aberta) link:https://github.com/open-policy-agent/opa/releases/tag/v1.0.0[v1.0.0] em dezembro de 2024, uma mudanûÏa significativa foi introduzida em relaûÏûÈo û  sintaxe da polûÙtica Rego.

Anteriormente, `if` para todas as definiûÏûçes de regras e `contains` para regras de mû¤ltiplos valores eram opcionais; agora, sûÈo obrigatû°rios. Essa mudanûÏa afeta a maioria das polûÙticas mais antigas.

Aqui estûÀ um resumo do que vocûˆ precisa saber:

* *OPA v1.0.0 Syntax*: O OPA v1.0.0 exige o uso de `if` para todas as definiûÏûçes de regras e `contains` para regras de mû¤ltiplos valores. PolûÙticas que nûÈo aderirem a essa sintaxe irûÈo falhar.
* *Compatibilidade Retroativa*: Se vocûˆ precisar construir polûÙticas mais antigas que nûÈo utilizam a nova sintaxe v1.0.0, deve fornecer a flag `--v0-compatible` ao comando `opa build`.
* *IntegraûÏûÈo do Gatekeeper*: O Gatekeeper atualizou sua dependûˆncia do OPA para v1.0.0 em sua link:https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.19.0[versûÈo v3.19.0].
* *VersûÈo do Rego nos templates do Gatekeeper*: O Gatekeeper assume que a sintaxe `v0` ûˋ utilizada, a menos que o template especifique explicitamente `version: "v1"` no campo `source` sob `code.engine: Rego`.

Veja link:https://open-policy-agent.github.io/gatekeeper/website/docs/constrainttemplates/#enable-opa-rego-v1-syntax-in-constrainttemplates[esta seûÏûÈo] da documentaûÏûÈo do Gatekeeper para mais detalhes sobre como as versûçes `v0` e `v1` do Rego sûÈo tratadas.

O que isso significa para vocûˆ:

* Se o Gatekeeper CR nûÈo especificar uma versûÈo do Rego, isso implica que `v0` serûÀ usado. Vocûˆ deve construir a polûÙtica usando o comando `OPA_V0_COMPATIBLE=true make`.
* Se o Gatekeeper CR especificar explicitamente `version: "v1"`, vocûˆ deve construir a polûÙtica sem nenhuma variûÀvel de ambiente definida.

== Etapa 3: Atualizar e executar os testes

Embora seja altamente recomendado, os autores de polûÙticas podem pular a criaûÏûÈo de testes para a versûÈo inicial de uma polûÙtica. Se isso se aplica a vocûˆ, precisarûÀ desativar os alvos do Makefile usados para executar os testes. Vocûˆ nûÈo pode remover esses alvos completamente, pois os trabalhos padrûÈo de CI esperam que eles estejam definidos. Em vez disso, vocûˆ deve substituir os comandos que chamam `opa` e `bats` por uma operaûÏûÈo "no-op". Por exemplo, vocûˆ pode usar um comando `echo` para imprimir uma explicaûÏûÈo do porquûˆ os testes nûÈo estûÈo sendo executados.

O template {short-project-name} do Gatekeeper inclui tanto testes unitûÀrios de Rego quanto testes de ponta a ponta (e2e) usando Bats e `kwctl`. Se vocûˆ planeja incluir testes, ambos os conjuntos precisam ser adaptados para sua polûÙtica.

Se sua polûÙtica do Gatekeeper jûÀ possui testes de Rego, vocûˆ pode copiûÀ-los para o arquivo `policy_test.rego`. Esses sûÈo executados automaticamente quando vocûˆ executa o comando `make test`.

[CAUTION]
====
Tenha em mente que quaisquer testes de Rego que vocûˆ escrever em `policy_test.rego` estûÈo sujeitos aos mesmos problemas de compatibilidade detalhados na seûÏûÈo <<_rego_policy_code_and_opa_v1_0_0_compatibility,Rego Policy code and OPA v1.0.0 Compatibility>>.
====

A polûÙtica que vocûˆ estûÀ migrando neste guia nûÈo possui testes; precisamos adicionûÀ-los nû°s mesmos. Portanto, vamos atualizar o arquivo de teste `policy_test.rego` com alguns testes bûÀsicos:

[source,rego]
----
package policy

review_required_labels := {
    "parameters": {"labels": ["test"]},
    "review": {"object": {"metadata": {"labels": {"test": "value"}}}},
}

review_missing_labels := {
    "parameters": {"labels": ["test"]},
    "review": {"object": {"metadata": {"labels": {"other": "value"}}}},
}

test_accept if {
    r = review_required_labels
    res = violation with input as r
    count(res) = 0
}

test_reject if {
    r = review_missing_labels
    res = violation with input as r
    count(res) = 1
}
----

Agora, executar `make test` deve validar sua polûÙtica:

[source,console]
----
$ make policy.wasm test
opa build -t wasm -e policy/violation -o bundle.tar.gz policy.rego
tar xvf bundle.tar.gz /policy.wasm
tar: Removing leading `/' from member names
/policy.wasm
rm bundle.tar.gz
touch policy.wasm # opa creates the bundle with unix epoch timestamp, fix it
opa test *.rego
PASS: 2/2
----

Em seguida, atualize o arquivo de testes e2e (`e2e.bats`):

[source,bash]
----
#!/usr/bin/env bats

@test "accept because required label is present" {
  run kwctl run -e gatekeeper annotated-policy.wasm --settings-path test_data/settings.json --request-path test_data/accept_deploy_request.json

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # request accepted
  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}

@test "reject because required label is missing" {
run kwctl run -e gatekeeper annotated-policy.wasm --settings-path test_data/settings.json --request-path test_data/reject_deploy_request.json

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # request rejected
  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [ $(expr "$output" : '.*message.*you must provide labels: \[test\]') -ne 0 ]
}
----

Vocûˆ precisarûÀ criar os arquivos `test_data/settings.json`, `test_data/accept_deploy_request.json` e `test_data/reject_deploy_request.json` para suportar esses testes.

[.details]
.test_data/settings.json
[%collapsible]
====
[source,json]
----
{
  "labels": ["test"]
}
----
====

NûÈo incluiremos o conteû¤do completo de `accept_deploy_request.json` e `reject_deploy_request.json` aqui, pois `AdmissionRequest` JSON pode ser bastante longo, e queremos manter este guia conciso. No entanto, vocûˆ pode usar o comando xref:/reference/kwctl-cli.adoc#_kwctl_scaffold_admission_request[`kwctl scaffold`] para gerar esses arquivos. A chave para este guia ûˋ que uma solicitaûÏûÈo deve estar sem o rû°tulo necessûÀrio, enquanto a outra deve ter o rû°tulo definido.

Verifique se os testes e2e estûÈo passando:

[source,console]
----
$ make e2e-tests
bats e2e.bats
e2e.bats
  ã accept because required label is present
  ã reject because required label is missing
----

[IMPORTANT]
====
Os parûÂmetros da polûÙtica (por exemplo, rû°tulos neste exemplo) originam-se das configuraûÏûçes da polûÙtica. Isso permite que vocûˆ implante vûÀrias instûÂncias da mesma polûÙtica com diferentes parûÂmetros/configuraûÏûçes, semelhante a como Constraints funcionam no Gatekeeper.
====

== Etapa 4: Prepare `metadata.yml` para distribuiûÏûÈo

Agora que vocûˆ tem uma polûÙtica funcional, prepare o arquivo `metadata.yml` para distribuiûÏûÈo. Este arquivo define anotaûÏûçes com a descriûÏûÈo da polûÙtica, autor, licenûÏa e outras informaûÏûçes essenciais. Crucialmente, ele define o `rules` que especifica quais recursos e verbos a polûÙtica pode validar. Esta informaûÏûÈo direciona o comando `kwctl scaffold` para gerar o manifesto para implantar a polûÙtica em seu cluster.

Os CRDs `Constraints` do Gatekeeper, que sûÈo instûÂncias de polûÙticas definidas em `ConstraintTemplates`, especificam quais recursos uma instûÂncia de polûÙtica avalia.
Portanto, se vocûˆ tiver `Constraints` existentes que aplicam um `ConstraintTemplate`, eles oferecem uma boa referûˆncia para os recursos que vocûˆ deve definir em seu arquivo `metadata.yml`. Por exemplo, no exemplo do Gatekeeper usado anteriormente, o `K8sRequiredLabels` `Constraint` criado a partir do `k8srequiredlabels` `ConstraintTemplate` se aplica a `Namespaces`:

[source,yaml]
----
apiVersion: constraints.gatekeeper.sh/v1beta
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-gk
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    labels: ["gatekeeper"]
----

Com base nisso, atualize a seûÏûÈo `rules` do seu `metadata.yml` para incluir um novo `rule` para validar `namespaces` durante as operaûÏûçes de `CREATE` e `UPDATE`:

[source,yaml]
----
rules:
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
    operations: ["CREATE", "UPDATE"]
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["namespaces"]
    operations: ["CREATE", "UPDATE"]
mutating: false
contextAware: false
executionMode: gatekeeper
backgroundAudit: true
annotations:
  io.artifacthub.displayName: Policy Name
  io.artifacthub.resources: Pod
  io.artifacthub.keywords: pod, cool policy, kubewarden
  io.kubewarden.policy.ociUrl: ghcr.io/yourorg/policies/policy-name
  io.kubewarden.policy.title: policy-name
  io.kubewarden.policy.version: 0.0.1-unreleased
  io.kubewarden.policy.description: Short description
  io.kubewarden.policy.author: "Author name <author-email@example.com>"
  io.kubewarden.policy.url: https://github.com/yourorg/policy-name
  io.kubewarden.policy.source: https://github.com/yourorg/policy-name
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.severity: medium
  io.kubewarden.policy.category: Resource validation
----

Agora, sua polûÙtica estûÀ pronta para distribuiûÏûÈo e implantaûÏûÈo. Consulte a seûÏûÈo xref:/tutorials/writing-policies/rego/gatekeeper/04-distribute.adoc#_pushing_the_policy[Publicando a polûÙtica] do tutorial para aprender como enviûÀ-la para um registro remoto.

Vocûˆ pode criar o manifesto da polûÙtica usando `kwctl`:

[source,console]
----
$ kwctl scaffold manifest --type ClusterAdmissionPolicy annotated-policy.wasm
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: Resource validation
    io.kubewarden.policy.severity: medium
  name: policy-name
spec:
  module: file:///home/jvanz/SUSE/mygatekeeperpolicy/annotated-policy.wasm
  settings: {}
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    resources:
    - deployments
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
    - ''
    apiVersions:
    - v1
    resources:
    - namespaces
    operations:
    - CREATE
    - UPDATE
  mutating: false
----

=== Defina ConfiguraûÏûçes da PolûÙtica

Esta polûÙtica tem parûÂmetros, que o Gatekeeper define dentro do `Constraint`. Vocûˆ precisa atualizar a seûÏûÈo `settings` no manifesto de polûÙtica gerado {short-project-name} para incluir esses parûÂmetros obrigatû°rios. No exemplo a seguir, alûˋm de definir as configuraûÏûçes, vocûˆ pode testar a polûÙtica a partir do registro OCI:

[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: Resource validation
    io.kubewarden.policy.severity: medium
  name: policy-name
spec:
  module: registry://ghcr.io/jvanz/policies/mygatekeeperpolicy:latest
  settings:
    labels:
      - "gatekeeper"
  rules:
    - apiGroups:
        - apps
      apiVersions:
        - v1
      resources:
        - deployments
      operations:
        - CREATE
        - UPDATE
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - namespaces
      operations:
        - CREATE
        - UPDATE
  mutating: false
----

Tente implantar um namespace sem o rû°tulo obrigatû°rio `gatekeeper`:

[source,console]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: your-namespace-name
  labels:
    purpose: demo
EOF
Error from server: error when creating "STDIN": admission webhook "clusterwide-policy-name.kubewarden.admission" denied the request: you must provide labels: [gatekeeper]
----

E outro namespace com o rû°tulo obrigatû°rio:

[source,console]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: your-namespace-name
  labels:
    purpose: demo
    gatekeeper: test
EOF

namespace/your-namespace-name created
----